/* 图表判读练习：每题随机生成一张现场常见的图，回答“看到了什么、下一步做什么”。
   九类图对应工程师日常要读的东西：控制图、机台间对比、晶圆地图、帕累托、分层散点、直方图与 Cpk、变化点、量测设备比对、改善前后对照。
   数据全部为教学设定。成绩只存在本机浏览器。文字就地成对书写 T('中文','日本語')。 */
(function(){
const T=globalThis.T||((zh)=>zh),$=id=>document.getElementById(id),KEY='cmp-fab-chartlab-v1';
const R=Math.random,gauss=()=>{let s=0;for(let i=0;i<12;i++)s+=R();return s-6},pick=a=>a[Math.floor(R()*a.length)],r1=x=>Math.round(x*10)/10,r2=x=>Math.round(x*100)/100;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const mean=a=>a.reduce((x,y)=>x+y,0)/a.length,sd=a=>{const m=mean(a);return Math.sqrt(a.reduce((s,v)=>s+(v-m)**2,0)/(a.length-1))};
const shuffle=a=>{for(let i=a.length-1;i>0;i--){const j=Math.floor(R()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};

/* ---------- SVG 绘图 ---------- */
const W=600,H=320,P={l:54,r:18,t:18,b:40},C={line:'#6de1cc',pt:'#ffd479',bad:'#f08c6a',cl:'#bed7d5',lim:'#ffd479',spec:'#f08c6a',txt:'#bed7d5',grid:'#2a4a57',a:'#6de1cc',b:'#f4b179',c:'#a9b8ff',d:'#e6a8d7'};
const frame=(inner,aria)=>`<svg class="spc" viewBox="0 0 ${W} ${H}" role="img" aria-label="${esc(aria)}">${inner}</svg>`;
const sy=(lo,hi)=>v=>P.t+(hi-v)/(hi-lo)*(H-P.t-P.b),sx=n=>i=>P.l+(i+.5)/n*(W-P.l-P.r);
const txt=(x,y,s,o={})=>`<text x="${x}" y="${y}" fill="${o.fill||C.txt}" font-size="${o.size||11}" text-anchor="${o.anchor||'start'}"${o.rot?` transform="rotate(-90 ${x} ${y})"`:''}>${esc(s)}</text>`;
const hl=(y,color,dash,label)=>`<line x1="${P.l}" x2="${W-P.r}" y1="${y}" y2="${y}" stroke="${color}" stroke-width="1"${dash?` stroke-dasharray="${dash}"`:''}/>`+(label?txt(P.l-4,y+4,label,{anchor:'end',fill:color}):'');
function yTicks(lo,hi,y,step){let out='';for(let v=Math.ceil(lo/step)*step;v<=hi;v+=step)out+=`<line x1="${P.l}" x2="${W-P.r}" y1="${y(v)}" y2="${y(v)}" stroke="${C.grid}" stroke-width="1"/>`+txt(P.l-4,y(v)+4,String(v),{anchor:'end'});return out}
function lineChart(v,o){const lo=o.lo,hi=o.hi,y=sy(lo,hi),x=sx(v.length);let s=yTicks(lo,hi,y,o.step||10);if(o.usl)s+=hl(y(o.usl),C.spec,'',T('规格上限','規格上限'))+hl(y(o.lsl),C.spec,'',T('规格下限','規格下限'));if(o.ucl)s+=hl(y(o.ucl),C.lim,'6 4','UCL')+hl(y(o.lcl),C.lim,'6 4','LCL');if(o.cl)s+=hl(y(o.cl),C.cl,'2 5',T('中心线','中心線'));(o.events||[]).forEach(e=>{s+=`<line x1="${x(e.at)-((W-P.l-P.r)/v.length)/2}" x2="${x(e.at)-((W-P.l-P.r)/v.length)/2}" y1="${P.t}" y2="${H-P.b}" stroke="${C.b}" stroke-width="1.5" stroke-dasharray="4 3"/>`+txt(x(e.at)-((W-P.l-P.r)/v.length)/2+4,P.t+12,e.label,{fill:C.b})});s+=`<polyline fill="none" stroke="${C.line}" stroke-width="2" stroke-linejoin="round" points="${v.map((p,i)=>x(i)+','+y(p)).join(' ')}"/>`;v.forEach((p,i)=>{s+=`<circle cx="${x(i)}" cy="${y(p)}" r="3.5" fill="${o.flag&&o.flag(p,i)?C.bad:C.pt}"/>`});s+=txt(W-P.r,H-8,o.xlabel||T('批次（按时间顺序）→','ロット（時系列）→'),{anchor:'end'});if(o.ylabel)s+=txt(14,H/2,o.ylabel,{rot:1,anchor:'middle'});return frame(s,o.aria)}
function boxplot(groups,o){const all=groups.flatMap(g=>g.vals),lo=Math.floor(Math.min(...all,o.lsl)/5)*5-5,hi=Math.ceil(Math.max(...all,o.usl)/5)*5+5,y=sy(lo,hi),n=groups.length,x=sx(n),bw=(W-P.l-P.r)/n*.4;let s=yTicks(lo,hi,y,5)+hl(y(o.usl),C.spec,'',T('规格上限','規格上限'))+hl(y(o.lsl),C.spec,'',T('规格下限','規格下限'));groups.forEach((g,i)=>{const a=[...g.vals].sort((p,q)=>p-q),q=t=>{const k=(a.length-1)*t,f=Math.floor(k);return a[f]+(a[f+1]-a[f])*(k-f)},q1=q(.25),q2=q(.5),q3=q(.75),cx=x(i);s+=`<line x1="${cx}" x2="${cx}" y1="${y(a[0])}" y2="${y(q1)}" stroke="${C.line}"/><line x1="${cx}" x2="${cx}" y1="${y(q3)}" y2="${y(a[a.length-1])}" stroke="${C.line}"/><rect x="${cx-bw/2}" y="${y(q3)}" width="${bw}" height="${Math.max(1,y(q1)-y(q3))}" fill="#1d4a52" stroke="${C.line}" stroke-width="1.5"/><line x1="${cx-bw/2}" x2="${cx+bw/2}" y1="${y(q2)}" y2="${y(q2)}" stroke="${C.pt}" stroke-width="2"/>`;g.vals.forEach(v=>{s+=`<circle cx="${cx+(R()-.5)*bw*.6}" cy="${y(v)}" r="2" fill="${C.pt}" fill-opacity=".6"/>`});s+=txt(cx,H-P.b+16,g.name,{anchor:'middle'})});s+=txt(14,H/2,o.ylabel,{rot:1,anchor:'middle'});return frame(s,o.aria)}
function waferSVG(points,o){const lo=o.lo,hi=o.hi,col=v=>{const q=Math.max(0,Math.min(1,(v-lo)/(hi-lo)));return q<.5?`rgb(${Math.round(99+27*q*2)},${Math.round(168+56*q*2)},${Math.round(222-29*q*2)})`:`rgb(${Math.round(126+117*(q-.5)*2)},${Math.round(224-54*(q-.5)*2)},${Math.round(193-80*(q-.5)*2)})`};let s=`<circle cx="160" cy="160" r="140" fill="#163b4b" stroke="#a9c6ca" stroke-width="2"/>`;points.forEach(p=>{s+=`<circle cx="${160+p.x*135}" cy="${160+p.y*135}" r="10" fill="${col(p.t)}"><title>${r1(p.t)} nm</title></circle>`});s+=`<path d="M150 298h20" stroke="#d2dedb" stroke-width="4"/>`;const lg=`<defs><linearGradient id="wl" x1="0" x2="1"><stop offset="0" stop-color="${col(lo)}"/><stop offset=".5" stop-color="${col((lo+hi)/2)}"/><stop offset="1" stop-color="${col(hi)}"/></linearGradient></defs><rect x="360" y="140" width="200" height="14" fill="url(#wl)"/>`+txt(360,170,`${lo} nm`)+txt(560,170,`${hi} nm`,{anchor:'end'})+txt(360,120,T('膜厚（49 点）','膜厚（49 点）'))+txt(360,210,T('缺口朝下 · 每个圆点一个测点','ノッチ下向き · 各点が 1 測定点'),{size:10});return `<svg class="spc" viewBox="0 0 600 320" role="img" aria-label="${esc(o.aria)}">${lg}${s}</svg>`}
function paretoSVG(items,o){const total=items.reduce((n,i)=>n+i.n,0),n=items.length,x=sx(n),bw=(W-P.l-P.r)/n*.6,y=sy(0,Math.max(...items.map(i=>i.n))*1.15),yp=sy(0,100);let s='',cum=0;const pts=[];items.forEach((it,i)=>{cum+=it.n;const pc=cum/total*100;pts.push(x(i)+','+yp(pc));s+=`<rect x="${x(i)-bw/2}" y="${y(it.n)}" width="${bw}" height="${H-P.b-y(it.n)}" fill="${i<o.hi?C.line:'#3d6570'}"/>`+txt(x(i),y(it.n)-5,String(it.n),{anchor:'middle'})+txt(x(i),H-P.b+16,it.name,{anchor:'middle',size:10})+txt(x(i),yp(pc)-8,Math.round(pc)+'%',{anchor:'middle',fill:C.pt,size:10})});s+=hl(yp(80),C.spec,'4 3','80%')+`<polyline fill="none" stroke="${C.pt}" stroke-width="2" points="${pts.join(' ')}"/>`+pts.map(p=>`<circle cx="${p.split(',')[0]}" cy="${p.split(',')[1]}" r="3.5" fill="${C.pt}"/>`).join('');s+=txt(14,H/2,T('缺陷数 / 累计占比','欠陥数 / 累積比率'),{rot:1,anchor:'middle'});return frame(s,o.aria)}
function scatterSVG(pts,o){const y=sy(o.ylo,o.yhi),x=v=>P.l+(v-o.xlo)/(o.xhi-o.xlo)*(W-P.l-P.r);let s=yTicks(o.ylo,o.yhi,y,o.ystep||10);for(let v=o.xlo;v<=o.xhi;v+=o.xstep)s+=txt(x(v),H-P.b+14,String(v),{anchor:'middle'});if(o.diag)s+=`<line x1="${x(o.xlo)}" y1="${y(o.xlo)}" x2="${x(o.xhi)}" y2="${y(o.xhi)}" stroke="${C.cl}" stroke-dasharray="4 4"/>`+txt(x(o.xhi)-6,y(o.xhi)+14,'y = x',{anchor:'end'});pts.forEach(p=>{s+=`<circle cx="${x(p.x)}" cy="${y(p.y)}" r="4" fill="${p.c||C.pt}" fill-opacity=".85"/>`});(o.legend||[]).forEach((l,i)=>{s+=`<rect x="${P.l+8+i*130}" y="${P.t+4}" width="10" height="10" fill="${l.c}"/>`+txt(P.l+22+i*130,P.t+13,l.name)});s+=txt(W-P.r,H-6,o.xlabel,{anchor:'end'})+txt(14,H/2,o.ylabel,{rot:1,anchor:'middle'});return frame(s,o.aria)}
function histSVG(vals,o){const bins=[];for(let b=o.lo;b<o.hi;b+=o.bin)bins.push({lo:b,n:vals.filter(v=>v>=b&&v<b+o.bin).length});const y=sy(0,Math.max(...bins.map(b=>b.n))*1.2),x=v=>P.l+(v-o.lo)/(o.hi-o.lo)*(W-P.l-P.r);let s='';bins.forEach(b=>{s+=`<rect x="${x(b.lo)+1}" y="${y(b.n)}" width="${x(b.lo+o.bin)-x(b.lo)-2}" height="${H-P.b-y(b.n)}" fill="${b.lo+o.bin<=o.lsl||b.lo>=o.usl?C.bad:C.line}"/>`});for(let v=o.lo;v<=o.hi;v+=10)s+=txt(x(v),H-P.b+14,String(v),{anchor:'middle'});s+=`<line x1="${x(o.lsl)}" x2="${x(o.lsl)}" y1="${P.t}" y2="${H-P.b}" stroke="${C.spec}" stroke-width="1.5"/><line x1="${x(o.usl)}" x2="${x(o.usl)}" y1="${P.t}" y2="${H-P.b}" stroke="${C.spec}" stroke-width="1.5"/><line x1="${x(o.m)}" x2="${x(o.m)}" y1="${P.t}" y2="${H-P.b}" stroke="${C.pt}" stroke-dasharray="4 3"/>`+txt(x(o.lsl)+3,P.t+12,'LSL '+o.lsl,{fill:C.spec})+txt(x(o.usl)-3,P.t+12,'USL '+o.usl,{fill:C.spec,anchor:'end'})+txt(x(o.m)+3,P.t+28,T('均值 ','平均 ')+r1(o.m),{fill:C.pt})+txt(W-P.r,H-6,T('膜厚 nm','膜厚 nm'),{anchor:'end'})+txt(14,H/2,T('片数','枚数'),{rot:1,anchor:'middle'});return frame(s,o.aria)}
function dotSVG(groups,o){const all=groups.flatMap(g=>g.vals),lo=Math.floor(Math.min(...all)/5)*5-5,hi=Math.ceil(Math.max(...all)/5)*5+5,y=sy(lo,hi),x=sx(groups.length),bw=90;let s=yTicks(lo,hi,y,5);if(o.usl)s+=hl(y(o.usl),C.spec,'',T('规格上限','規格上限'));groups.forEach((g,i)=>{const cx=x(i),m=mean(g.vals);g.vals.forEach((v,k)=>{s+=`<circle cx="${cx-30+k*15}" cy="${y(v)}" r="5" fill="${C.pt}"/>`});s+=`<line x1="${cx-bw/2}" x2="${cx+bw/2}" y1="${y(m)}" y2="${y(m)}" stroke="${C.line}" stroke-width="2"/>`+txt(cx+bw/2+4,y(m)+4,T('均值 ','平均 ')+r1(m),{fill:C.line})+txt(cx,H-P.b+16,g.name,{anchor:'middle'})});s+=txt(14,H/2,T('膜厚 nm','膜厚 nm'),{rot:1,anchor:'middle'});return frame(s,o.aria)}

/* ---------- 九类题目 ---------- */
const causes=[T('突然的设定或校准变化（压力失准、量测模型更新、换错配方）','設定や校正の急な変化（圧力のずれ、測定モデルの更新、レシピの取り違え）'),T('耗材逐渐劣化（修整盘磨钝、垫堵塞、流量缓慢下降）','消耗品の緩やかな劣化（ドレッサー摩耗、パッドの目詰まり、流量の緩やかな低下）'),T('过程不稳定（夹持、来料膜厚波动、量测重复性变差）','工程の不安定化（保持、投入膜厚のばらつき、測定の繰り返し性の悪化）'),T('单批事件（来料、操作失误）：先复测，再判断','単一ロットの事象（投入材料、操作ミス）：まず再測定してから判断'),T('过程正常：不调整，继续监控（避免过度调整）','工程は正常：調整せず監視を続ける（過剰調整を避ける）')];
const DRILLS=[
 {id:'spc',name:T('控制图判异','管理図の判定'),make(){const pat=pick(['shift','shift','trend','trend','spread','spike','none','none']),n=24,cl=200,sg=3.5,k=8+Math.floor(R()*8),dir=R()<.5?1:-1,v=[];for(let i=0;i<n;i++){let x=cl+gauss()*sg;if(pat==='shift'&&i>=k)x+=dir*sg*(2.2+R()*.8);if(pat==='trend'&&i>=k)x+=dir*(i-k)*sg*.35;if(pat==='spread'&&i>=k)x=cl+gauss()*sg*2.4;if(pat==='spike'&&i===k)x=cl+dir*sg*(3.5+R());v.push(r1(x))}const idx={shift:0,trend:1,spread:2,spike:3,none:4}[pat];return {aria:T('膜厚控制图','膜厚の管理図'),context:T('某台 CMP 机台最近 24 批的膜厚控制图（M1 在线量测）。中心线 200，控制界限 ±3σ，规格 185–215。','ある CMP 装置の直近 24 ロットの膜厚管理図（M1 インライン測定）。中心線 200、管理限界 ±3σ、規格 185–215。'),chart:lineChart(v,{lo:180,hi:220,cl,ucl:r1(cl+3*sg),lcl:r1(cl-3*sg),usl:215,lsl:185,ylabel:T('膜厚 nm','膜厚 nm'),aria:T('膜厚控制图','膜厚管理図'),flag:p=>Math.abs(p-cl)>3*sg}),questions:[{q:T('过程发生了什么？','工程に何が起きましたか。'),options:[T('均值突然阶跃','平均が急にシフトした'),T('均值逐渐漂移','平均が徐々にドリフトしている'),T('波动变大，均值没变','ばらつきが増えた（平均は不変）'),T('只有一个孤立的异常点','孤立した異常点が 1 つだけ'),T('正常，只有随机波动','正常。ランダムなばらつきのみ')],answer:idx,why:T('看形状：阶跃是台阶，漂移是斜坡，波动变大是上下摆幅同时变宽，孤立点前后都正常。判异规则（连续同侧、2σ 外 2/3 点、3σ 外 1 点）是把这些形状量化的方法。','形で見る：シフトは段差、ドリフトは坂、ばらつき増大は上下の振れ幅が同時に広がる、孤立点は前後が正常。判定ルール（連続同側、2σ外 2/3 点、3σ外 1 点）はこれらの形を数値化したもの。')},{q:T('最可能的原因方向，以及下一步？','最も可能性の高い原因の方向と、次の一手は？'),options:causes,answer:idx,why:T('阶跃对应“某个时刻改变了什么”，去查变化点；漂移对应“什么在慢慢耗损”，去查耗材；波动变大要查稳定性和量测；孤立点先复测；正常的过程不要动它。','シフトは「ある時点で何かが変わった」→変化点を確認。ドリフトは「何かが徐々に消耗」→消耗品を確認。ばらつき増大は安定性と測定を確認。孤立点はまず再測定。正常な工程には手を出さない。')}],insight:T('现场每天第一件事就是看控制图。报警后按 OCAP（异常处置流程）响应，先确认量测，再查变化点，最后才停机。看到一个点偏高就去调参数，叫过度调整，会把波动越调越大。','現場では毎日まず管理図を見ます。アラーム後は OCAP（異常時対応フロー）に従い、まず測定を確認し、次に変化点を確認し、最後に停止します。1 点が高いだけでパラメータを触るのは「過剰調整」で、ばらつきをかえって大きくします。')}}},
 {id:'tools',name:T('机台间对比','号機間の比較'),make(){const tools=['A','B','C','D'],bad=Math.floor(R()*4),mode=pick(['mean','mean','spread','both','none']),groups=tools.map((t,i)=>{const m=200+(i===bad&&mode!=='spread'&&mode!=='none'?(R()<.5?-1:1)*6:0),s=3+(i===bad&&(mode==='spread'||mode==='both')?5:0);return {name:'Tool '+t,vals:Array.from({length:12},()=>r1(m+gauss()*s))}});return {aria:T('四台机台的膜厚箱线图','4 台の膜厚箱ひげ図'),context:T('四台 CMP 机台本周各 12 批的膜厚箱线图（同一产品、同一配方）。箱体为四分位区间，横线为中位数，点为各批。规格 185–215。','4 台の CMP 装置の今週 12 ロットずつの膜厚箱ひげ図（同一製品・同一レシピ）。箱は四分位範囲、横線は中央値、点は各ロット。規格 185–215。'),chart:boxplot(groups,{usl:215,lsl:185,ylabel:T('膜厚 nm','膜厚 nm'),aria:T('箱线图','箱ひげ図')}),questions:[{q:T('哪台机台需要优先查看？','どの号機を優先して確認しますか。'),options:[...tools.map(t=>'Tool '+t),T('四台都正常','4 台とも正常')],answer:mode==='none'?4:bad,why:T('机台间对比看两件事：箱体的位置（均值）和箱体加须的长度（波动）。和其他三台明显不同的那一台就是要查的对象。','号機間の比較で見るのは 2 つ：箱の位置（平均）と、箱＋ひげの長さ（ばらつき）。他の 3 台と明らかに違う 1 台が確認対象。')},{q:T('它的问题属于哪一类？','その問題はどの種類ですか。'),options:[T('均值偏移（位置不同，宽度相近）','平均のずれ（位置が違い、幅は同程度）'),T('波动偏大（位置相近，宽度更宽）','ばらつきが大きい（位置は同程度、幅が広い）'),T('均值偏移且波动偏大','平均のずれとばらつき増大の両方'),T('没有异常','異常なし')],answer:{mean:0,spread:1,both:2,none:3}[mode],why:T('均值偏移多半是设定与实际不一致（压力、流量、时间）或耗材状态不同，可以通过校准或补偿解决；波动偏大是稳定性问题，补偿解决不了，要找波动的来源。','平均のずれは設定と実測の不一致（圧力・流量・時間）や消耗品の状態差が多く、校正や補正で対応できる。ばらつきの増大は安定性の問題で、補正では解決せず、ばらつきの源を探す必要がある。')}],insight:T('日语叫「機差」。多台机台跑同一产品时，工程师每周都要比对机台间的差异，把偏离的机台拉回来，这叫机台匹配（tool matching）。','日本語では「機差」。複数の号機で同じ製品を流すとき、エンジニアは毎週号機間の差を比較し、ずれた号機を合わせ込みます。これを tool matching と呼びます。')}}},
 {id:'wafer',name:T('晶圆地图','ウェーハマップ'),make(){const pat=pick(['edgeThin','edgeThick','centerThin','tilt','random','spot']),rings=[[0,1],[.33,8],[.66,16],[.92,24]],phi=R()*Math.PI*2,pts=[];let id=0;for(const [rad,cnt] of rings)for(let i=0;i<cnt;i++){const th=i/cnt*Math.PI*2;let t=200+gauss()*1.1;if(pat==='edgeThin')t-=14*rad**4;if(pat==='edgeThick')t+=12*rad**4;if(pat==='centerThin')t-=9*(1-rad*rad);if(pat==='tilt')t+=9*rad*Math.cos(th-phi);if(pat==='random')t=200+gauss()*2.6;pts.push({x:rad*Math.cos(th),y:rad*Math.sin(th),t,id:id++})}if(pat==='spot'){const k=25+Math.floor(R()*20);for(const j of [k,k+1,k+2])pts[j].t-=11}const q1={edgeThin:0,edgeThick:1,centerThin:2,tilt:3,spot:4,random:5}[pat],q2={edgeThin:0,edgeThick:0,centerThin:1,tilt:2,spot:3,random:4}[pat];return {aria:T('晶圆膜厚地图','ウェーハ膜厚マップ'),context:T('一片晶圆研磨后的 49 点膜厚地图。目标 200 nm，颜色越红越厚、越蓝越薄。','研磨後ウェーハの 49 点膜厚マップ。目標 200 nm。赤いほど厚く、青いほど薄い。'),chart:waferSVG(pts,{lo:186,hi:214,aria:T('晶圆地图','ウェーハマップ')}),questions:[{q:T('分布形态是？','分布の形は？'),options:[T('边缘一圈偏薄','エッジ一周が薄い'),T('边缘一圈偏厚','エッジ一周が厚い'),T('中心偏薄','中心が薄い'),T('单侧倾斜：一边薄、对面厚','片側に傾斜：一方が薄く、反対側が厚い'),T('只有局部几个相邻的点异常','隣接する数点だけが異常'),T('随机分布，没有规律','ランダムで規則性なし')],answer:q1,why:T('先看有没有随半径变化的规律（同心圆），再看有没有方向性（一边到另一边），最后看有没有局部的点。三种形态对应的原因完全不同。','まず半径方向の規則性（同心円）を見て、次に方向性（一方から他方へ）を見て、最後に局所的な点を見る。3 つの形はそれぞれ原因が異なる。')},{q:T('最可能的原因方向？','最も可能性の高い原因の方向は？'),options:[T('边缘相关部件：保持环、边缘压力区','エッジ関連の部品：リテーナリング、エッジゾーンの圧力'),T('中心压力区的设定','センターゾーンの圧力設定'),T('研磨头或垫的单侧不平','研磨ヘッドまたはパッドの片側の不平行'),T('局部异物或划伤：送缺陷检查','局所的な異物やスクラッチ：欠陥検査へ'),T('正常波动，无需处置','正常なばらつき。対処不要')],answer:q2,why:T('同心圆形态由分区压力和保持环决定；单侧倾斜是机械对准的问题；局部点通常是异物或划伤，要用缺陷检查设备看；随机分布就是正常的片内波动。','同心円の形はゾーン圧力とリテーナリングで決まる。片側の傾斜は機械的なアライメントの問題。局所的な点は異物やスクラッチが多く、欠陥検査装置で確認する。ランダムな分布は正常な面内ばらつき。')}],insight:T('均值达标不等于晶圆合格。工程师看量测结果时，先看地图再看均值，因为分布形态直接指向机台的哪个部件。游戏的自主实验模式里，保持环磨损那一关就是典型的边缘偏薄。','平均が目標内でもウェーハが合格とは限りません。エンジニアは測定結果を見るとき、平均より先にマップを見ます。分布の形が装置のどの部品を指しているかを示すからです。ゲームの自主実験モードで、リテーナリング摩耗のケースが典型的なエッジ薄です。')}}},
 {id:'pareto',name:T('帕累托图','パレート図'),make(){const names=shuffle([T('划伤','スクラッチ'),T('颗粒','パーティクル'),T('研磨液残留','スラリー残渣'),T('腐蚀','腐食'),T('水痕','ウォーターマーク'),T('其他','その他')]),total=200,shares=[.42+R()*.14,.2+R()*.1,.08+R()*.07];const rest=1-shares.reduce((a,b)=>a+b,0),items=names.map((nm,i)=>({name:nm,n:Math.round(total*(i<3?shares[i]:rest/3*(.6+R()*.8)))})).sort((a,b)=>b.n-a.n);let cum=0,k=0;const tot=items.reduce((n,i)=>n+i.n,0);for(const it of items){cum+=it.n;k++;if(cum/tot>=.8)break}return {aria:T('缺陷帕累托图','欠陥のパレート図'),context:T('上周缺陷检查抓到的缺陷按类型统计，柱为数量，折线为累计占比。','先週の欠陥検査で検出された欠陥を種類別に集計。棒が個数、折れ線が累積比率。'),chart:paretoSVG(items,{hi:k,aria:T('帕累托图','パレート図')}),questions:[{q:T('资源有限，先处理哪一类？','リソースが限られている。まずどの種類に取り組みますか。'),options:items.map(i=>i.name),answer:0,why:T('帕累托的用法就是把有限的人力压在占比最大的一类上。先解决它，总缺陷数下降最快。','パレート図の使い方は、限られた人手を最も比率の大きい種類に集中させること。それを先に解決すれば、総欠陥数が最も速く減る。')},{q:T('累计占比达到 80%，需要前几类？','累積比率が 80% に達するのは上位何種類まで？'),options:['1','2','3','4'].map(x=>x+T(' 类',' 種類')),answer:k-1,why:T('读折线与 80% 线的交点。通常前两三类就占了八成，这就是“重点志向”的依据。','折れ線と 80% 線の交点を読む。通常は上位 2〜3 種類で 8 割を占め、これが「重点志向」の根拠になる。')}],insight:T('帕累托图是 QC 七种工具之一，日企现场的周会几乎必有一张。它决定的是“先做什么”，而不是“为什么”。找原因要接着用分层和鱼骨图。','パレート図は QC 七つ道具の一つで、日本の現場の週次会議にはほぼ必ず出てきます。決めるのは「まず何をするか」であって「なぜか」ではありません。原因を探すには、続けて層別や特性要因図を使います。')}}},
 {id:'strat',name:T('分层散点','層別散布図'),make(){const mode=pick(['real','mix','one']),pts=[],legend=[{name:T('产品 P','製品 P'),c:C.a},{name:T('产品 Q','製品 Q'),c:C.b}];for(let i=0;i<40;i++){const isQ=i%2===1,age=mode==='mix'?(isQ?1300+R()*1100:R()*1000):R()*2400,base=isQ?120:80,slope=mode==='real'?-.008:mode==='one'&&isQ?-.009:0;pts.push({x:Math.round(age),y:r1(base+slope*age+gauss()*3),c:isQ?C.b:C.a})}return {aria:T('去除速率与研磨垫使用量的散点图','研磨レートとパッド使用量の散布図'),context:T('去除速率（RR）对研磨垫使用量的散点图，按产品分色。两种产品本来就用不同配方，RR 水平不同。','研磨レート（RR）とパッド使用量の散布図。製品ごとに色分け。2 製品はもともとレシピが異なり、RR の水準も違う。'),chart:scatterSVG(pts,{xlo:0,xhi:2400,xstep:600,ylo:60,yhi:140,ystep:20,legend,xlabel:T('研磨垫使用量（片）','パッド使用量（枚）'),ylabel:T('去除速率 nm/min','研磨レート nm/min'),aria:T('分层散点图','層別散布図')}),questions:[{q:T('按产品分层来看，研磨垫使用量对去除速率有影响吗？','製品ごとに層別して見ると、パッド使用量は研磨レートに影響していますか。'),options:[T('两种产品都随使用量下降','2 製品とも使用量とともに低下'),T('分层后都没有变化；整体看像有关系，只是两种产品的使用量区间不同','層別するとどちらも変化なし。全体で関係があるように見えるのは、2 製品の使用量の範囲が違うだけ'),T('只有一种产品下降','1 製品だけ低下')],answer:{real:0,mix:1,one:2}[mode],why:T('把两种颜色分开看各自的斜率。混在一起时，产品构成会制造出并不存在的相关，也会掩盖真实存在的相关。','2 色を分けてそれぞれの傾きを見る。混ぜて見ると、製品構成が存在しない相関を作り出したり、実在する相関を隠したりする。')}],insight:T('分层（層別）是 QC 七种工具里最不起眼、却最常救人的一个。看到相关先问：数据里混了几种产品、几台机台、几个班次？分开再看一次。','層別は QC 七つ道具の中で最も地味ですが、最もよく人を救います。相関を見たらまず問う：データには何種類の製品、何台の号機、何交替のシフトが混ざっているか。分けてもう一度見る。')}}},
 {id:'cpk',name:T('直方图与 Cpk','ヒストグラムと Cpk'),make(){const off=pick([-6,-4,-2,0,0,2,4,6]),sg=pick([2.5,3.2,4.2,5.5,7]),vals=Array.from({length:60},()=>r1(200+off+gauss()*sg)),m=mean(vals),s=sd(vals),cpk=r2(Math.min(215-m,m-185)/(3*s)),band=cpk<1?0:cpk<1.33?1:cpk<1.67?2:3,prob=cpk>=1.33?3:(Math.abs(m-200)>=3&&s>=4.5)?2:Math.abs(m-200)>=3?0:1;return {aria:T('膜厚直方图','膜厚ヒストグラム'),context:T('某工序最近 60 批膜厚的直方图，规格 185–215（中心 200）。红色柱为超出规格。','ある工程の直近 60 ロットの膜厚ヒストグラム。規格 185–215（中心 200）。赤い棒は規格外。'),chart:histSVG(vals,{lo:175,hi:225,bin:2.5,lsl:185,usl:215,m,aria:T('直方图','ヒストグラム')}),questions:[{q:T('工序能力 Cpk 大约在哪个区间？','工程能力 Cpk はどの範囲？'),options:[T('小于 1.0（一定会出不良）','1.0 未満（不良が必ず出る）'),'1.0 – 1.33','1.33 – 1.67',T('1.67 以上','1.67 以上')],answer:band,why:T(`Cpk = min(USL − 均值, 均值 − LSL) ÷ 3σ。这组数据均值 ${r1(m)}、σ ${r1(s)}，Cpk ≈ ${cpk}。看图的方法：均值到较近那条规格线之间能放下几个“3σ”。`,`Cpk = min(USL − 平均, 平均 − LSL) ÷ 3σ。このデータは平均 ${r1(m)}、σ ${r1(s)}、Cpk ≈ ${cpk}。図の見方：平均から近い方の規格線までに「3σ」がいくつ入るか。`)},{q:T('如果 Cpk 不够，主要问题是什么？','Cpk が不足しているなら、主な問題は？'),options:[T('偏心：均值离规格中心远，波动本身不大','偏り：平均が規格中心から遠く、ばらつき自体は小さい'),T('波动大：均值居中，但分布太宽','ばらつき：平均は中心にあるが分布が広すぎる'),T('两者都有','両方'),T('能力充足，不需要处理','能力は十分。対処不要')],answer:prob,why:T('偏心靠调整设定就能改善，比较容易；波动大要找波动的来源，通常更难。两者的处置方向不同，所以要先分清。','偏りは設定の調整で改善でき、比較的容易。ばらつきはその源を探す必要があり、通常はより難しい。対処の方向が違うので、まず区別する。')}],insight:T('Cpk 是月度例会上概括一个工序状态的那个数字，一般要求 1.33 以上。新工艺移交量产时，Cpk 达标是验收条件之一。','Cpk は月次会議で工程の状態を一言で表す数字で、一般に 1.33 以上が求められます。新プロセスを量産へ移管する際、Cpk の達成は受け入れ条件の一つです。')}}},
 {id:'events',name:T('变化点','変化点'),make(){const labels=shuffle([T('更换研磨垫','パッド交換'),T('研磨液换批次','スラリーロット切替'),T('更换修整盘','ドレッサー交換')]),ev=[{at:7,label:labels[0]},{at:15,label:labels[1]},{at:23,label:labels[2]}],mode=pick(['ev','ev','ev','none','other']),cul=Math.floor(R()*3),start=mode==='ev'?ev[cul].at:mode==='other'?11:99,dir=R()<.5?1:-1,kind=R()<.5?'shift':'trend',v=[];for(let i=0;i<30;i++){let x=200+gauss()*3;if(i>=start)x+=kind==='shift'?dir*8:dir*(i-start)*1.1;v.push(r1(x))}const ans=mode==='ev'?cul:mode==='none'?3:4;return {aria:T('带维护事件标记的膜厚趋势','メンテナンス事象つきの膜厚推移'),context:T('30 批的膜厚趋势，竖虚线标出了这期间的三次维护或物料变更。','30 ロットの膜厚推移。縦の点線はこの期間の 3 回のメンテナンスまたは資材変更。'),chart:lineChart(v,{lo:180,hi:220,cl:200,usl:215,lsl:185,events:ev,ylabel:T('膜厚 nm','膜厚 nm'),aria:T('趋势图','推移図')}),questions:[{q:T('过程的变化是从哪里开始的？','工程の変化はどこから始まっていますか。'),options:[...ev.map(e=>T('从「'+e.label+'」之后','「'+e.label+'」の後から')),T('没有明显变化','明確な変化なし'),T('有变化，但起点和这三次事件都对不上','変化はあるが、起点は 3 つの事象のどれとも一致しない')],answer:ans,why:T('找变化的起点，再对照事件的时间。起点紧跟某次事件，它就是首要嫌疑；起点和事件对不上，说明还有没记录下来的变化，要去问。','変化の起点を探し、事象の時刻と照らす。起点がある事象の直後なら、それが第一容疑者。起点が事象と合わないなら、記録されていない変化があるはずで、聞き取りが必要。')}],insight:T('这就是 4M 变化点管理：看到异常先问“最近什么变了”。所以现场要求每一次维护、换料、改配方都留下时间记录，控制图上才对得上。','これが 4M 変化点管理です。異常を見たらまず「最近何が変わったか」を問う。だから現場では、メンテナンス・資材変更・レシピ変更のたびに時刻の記録を残すことが求められ、管理図と照合できるようにしています。')}}},
 {id:'msa',name:T('量测设备比对','測定機の比較'),make(){const mode=pick(['bias','noise','ok']),pts=[];for(let i=0;i<15;i++){const t=190+R()*20,m2=r1(t+gauss()*.5),m1=r1(mode==='bias'?t-6+gauss()*.5:mode==='noise'?t+gauss()*3.5:t+gauss()*.5);pts.push({x:m1,y:m2})}const a={bias:0,noise:1,ok:2}[mode];return {aria:T('M1 与 M2 量测同一批晶圆的散点图','同じウェーハを M1 と M2 で測定した散布図'),context:T('同一批 15 片晶圆，先用 M1 再用 M2 量测膜厚（M2 刚用标准片校准过）。横轴 M1，纵轴 M2，虚线为 y = x。','同じ 15 枚のウェーハを M1、次に M2 で測定（M2 は標準ウェーハで校正済み）。横軸 M1、縦軸 M2、点線は y = x。'),chart:scatterSVG(pts,{xlo:180,xhi:215,xstep:5,ylo:180,yhi:215,ystep:5,diag:1,xlabel:'M1 nm',ylabel:'M2 nm',aria:T('设备比对','測定機比較')}),questions:[{q:T('两台设备的关系是？','2 台の関係は？'),options:[T('系统偏差：点整体偏离 y = x，但排列紧密','系統的な偏り：点は全体が y = x からずれているが、並びは密'),T('重复性差：点围绕 y = x 散得很开','繰り返し性が悪い：点が y = x の周りに大きく散らばる'),T('一致：点紧贴 y = x','一致：点は y = x に沿っている')],answer:a,why:T('偏离直线的方向一致、距离一致，是偏差（准确度问题）；杂乱地散开，是重复性（精密度问题）。两者可以同时存在，处置完全不同。','線からのずれの方向と距離が一定なら偏り（正確さの問題）。乱雑に散らばるなら繰り返し性（精密さの問題）。両方が同時に存在することもあり、対処はまったく異なる。')},{q:T('下一步？','次の一手は？'),options:[T('用标准片确认后校准 M1，校准前的读数重新量测','標準ウェーハで確認してから M1 を校正し、校正前の読み値は再測定'),T('做 M1 的重复性评估（Gauge R&R），在此之前 M1 的数据不能用于判断','M1 の繰り返し性評価（Gauge R&R）を実施。それまで M1 のデータは判断に使わない'),T('无需处置，两台可以互换使用','対処不要。2 台は互換的に使える')],answer:a,why:T('偏差可以校准掉；重复性差校准也没用，要修设备或换设备。','偏りは校正で除ける。繰り返し性の悪さは校正しても直らず、装置の修理や交換が必要。')}],insight:T('这就是量测系统分析（MSA）。游戏里“消失的 18 纳米”和“读数正常，就真的正常吗”两关，练的都是先怀疑量测。','これが測定システム解析（MSA）です。ゲームの「消えた 18 ナノメートル」と「測定値が正常なら、本当に正常なのか」の 2 ケースは、どちらもまず測定を疑う練習です。')}}},
 {id:'ab',name:T('改善前后对照','改善前後の比較'),make(){const d=pick([0,-1.5,-3,-6,-9,-12,4]),before=Array.from({length:5},()=>r1(212+gauss()*3)),after=Array.from({length:5},()=>r1(212+d+gauss()*3)),diff=mean(after)-mean(before),se=Math.sqrt(sd(before)**2/5+sd(after)**2/5),t=Math.abs(diff)/se,ans=diff>2?2:t>2.3?0:1;return {aria:T('改善前后各五片的膜厚点图','改善前後各 5 枚の膜厚ドットプロット'),context:T('膜厚偏高（目标 200，规格上限 215）。做了一项改善后，前后各加工 5 片。目标是让膜厚降下来。','膜厚が高め（目標 200、規格上限 215）。改善を 1 つ実施し、前後で 5 枚ずつ処理。目標は膜厚を下げること。'),chart:dotSVG([{name:T('改善前','改善前'),vals:before},{name:T('改善后','改善後'),vals:after}],{usl:215,aria:T('前后对照','前後比較')}),questions:[{q:T('这项改善的效果可信吗？','この改善の効果は信頼できますか。'),options:[T('可信：前后差异远大于片间波动','信頼できる：前後の差がウェーハ間のばらつきより十分大きい'),T('不能下结论：差异在片间波动范围内，需要更多试片','結論できない：差はウェーハ間のばらつきの範囲内。もっと枚数が必要'),T('结果变差了：膜厚反而升高','悪化した：膜厚がかえって上がった')],answer:ans,why:T(`均值差 ${r1(diff)} nm，片间波动约 ±${r1((sd(before)+sd(after))/2)} nm。只有当差异明显大于波动时才能说“有效”。这就是 t 检验的直觉：差异 ÷ 波动。`,`平均差 ${r1(diff)} nm、ウェーハ間ばらつき約 ±${r1((sd(before)+sd(after))/2)} nm。差がばらつきより明らかに大きいときだけ「効果あり」と言える。これが t 検定の直感：差 ÷ ばらつき。`)}],insight:T('游戏里要求“同一方案重复 3 片”就是这个道理。现场汇报改善效果时，只给前后各一片的数字，会被问“片间波动多大？”。','ゲームで「同じ条件で 3 枚繰り返す」ことを求めるのはこのためです。現場で改善効果を報告するとき、前後 1 枚ずつの数字だけを出すと「ウェーハ間のばらつきはどれくらい？」と聞かれます。')}}}
];

/* ---------- 界面 ---------- */
let mode='random',cur=null,picked=[],done=false,stats=load();
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')||{}}catch(e){return {}}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(stats))}catch(e){}}
function toast(s){const t=$('toast');t.textContent=s;t.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>t.hidden=true,3500)}
function tabs(){$('caseTabs').innerHTML=`<button data-mode="random" class="${mode==='random'?'selected':''}">${T('随机出题','ランダム出題')}</button>`+DRILLS.map(d=>{const s=stats[d.id];return `<button data-mode="${d.id}" class="${mode===d.id?'selected':''}">${d.name}${s?` <small>${s.ok}/${s.n}</small>`:''}</button>`}).join('')}
function next(){const d=mode==='random'?pick(DRILLS):DRILLS.find(x=>x.id===mode);cur={drill:d,...d.make()};picked=cur.questions.map(()=>null);done=false;render()}
function render(){const q=cur;$('card').innerHTML=`<div class="headRow"><span class="overline">${q.drill.name}</span><p class="small">${q.context}</p></div>${q.chart}${q.questions.map((qq,i)=>`<h3>${i+1}. ${qq.q}</h3><div class="answerGrid" data-q="${i}">${qq.options.map((o,j)=>`<button data-opt="${j}" class="${picked[i]===j?'picked':''}">${o}</button>`).join('')}</div>`).join('')}<div class="rowActions"><button class="primary" id="check" ${picked.some(p=>p===null)?'disabled':''}>${T('检查答案','答え合わせ')}</button><button id="skip">${T('换一题','別の問題')}</button></div><div id="result"></div>`}
function check(){const q=cur;let ok=0;q.questions.forEach((qq,i)=>{const grid=document.querySelector(`.answerGrid[data-q="${i}"]`);grid.querySelectorAll('button').forEach(b=>{const j=Number(b.dataset.opt);b.disabled=true;if(j===qq.answer)b.classList.add('right');else if(j===picked[i])b.classList.add('wrong')});if(picked[i]===qq.answer)ok++});const s=stats[q.drill.id]||(stats[q.drill.id]={n:0,ok:0});s.n++;if(ok===q.questions.length)s.ok++;save();done=true;$('check').disabled=true;$('result').innerHTML=`<div class="notice ${ok===q.questions.length?'good':''}"><b>${ok===q.questions.length?T('全对','全問正解'):T(`答对 ${ok} / ${q.questions.length}`,`正解 ${ok} / ${q.questions.length}`)}</b></div>${q.questions.map((qq,i)=>`<p><b>${i+1}.</b> ${qq.why}</p>`).join('')}<div class="notice"><b>${T('现场对应','現場との対応')}</b><br>${q.insight}</div><div class="rowActions"><button class="primary" id="nextBtn">${T('下一题 →','次の問題 →')}</button></div>`;tabs();$('nextBtn').focus()}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.mode){mode=b.dataset.mode;tabs();next();return}if(b.dataset.opt!==undefined&&!done){const i=Number(b.closest('.answerGrid').dataset.q);picked[i]=Number(b.dataset.opt);b.parentElement.querySelectorAll('button').forEach(x=>x.classList.toggle('picked',x===b));$('check').disabled=picked.some(p=>p===null);return}if(b.id==='check')check();if(b.id==='skip'||b.id==='nextBtn')next();if(b.id==='helpButton')$('labDialog').showModal();if(b.id==='dlgClose')$('labDialog').close();if(b.id==='langButton')setLang(LANG==='ja'?'zh':'ja');if(b.id==='resetStats'){stats={};save();tabs();toast(T('成绩已清空。','成績をリセットしました。'))}});
$('help').innerHTML=`<h3>${T('这是什么练习','この練習について')}</h3><p>${T('工程师的大部分判断都从一张图开始。这里每题随机生成一张现场常见的图，问两件事：看到了什么、下一步做什么。九类图分别对应：SPC 判异、机台匹配、分区压力与部件、重点志向、分层、工序能力、变化点管理、量测系统分析、改善效果的判断。','エンジニアの判断の多くは 1 枚の図から始まります。ここでは毎回、現場でよく見る図をランダムに生成し、2 つを問います：何が見えるか、次に何をするか。9 種類の図はそれぞれ、SPC 判定、号機マッチング、ゾーン圧力と部品、重点志向、層別、工程能力、変化点管理、測定システム解析、改善効果の判断に対応します。')}</p><h3>${T('怎么用','使い方')}</h3><p>${T('先自己判断再点“检查答案”。答错的题型多练几次。每类的成绩显示在上方按钮里，只存在本机。建议每天 10 题，用日语把“看到了什么、下一步做什么”说一遍。','まず自分で判断してから「答え合わせ」を押す。間違えた種類は繰り返し練習する。種類ごとの成績は上のボタンに表示され、この端末にだけ保存されます。1 日 10 問、「何が見えるか、次に何をするか」を日本語で口に出すのがおすすめです。')}</p><p class="small">${T('全部数据为随机生成的教学设定，不是实际设备数据。图形的判读规则是通行的做法，各公司的具体阈值和流程会有差别。','データはすべてランダム生成の学習用設定で、実際の装置データではありません。図の読み方は一般的な方法で、具体的なしきい値や手順は会社ごとに異なります。')}</p><div class="rowActions"><button id="resetStats">${T('清空成绩','成績をリセット')}</button></div>`;
tabs();next();
})();
