/* Fixed educational scenarios. No live fab control or AI grading. */
(function(root){
const T=root.T||((zh)=>zh);
const sources=[['desk','metrology','tool','desk'],['desk','desk','metrology','tool'],['desk','metrology','lead','tool'],['desk','tool','metrology','tool'],['desk','tool','metrology','lab'],['desk','tool','metrology','lead']];
const stations=[{id:'lead',name:T('晨会 · 林前辈','朝会 · 林先輩'),short:T('晨会','朝会'),x:20,y:35,icon:'☀',room:T('团队区','チームエリア')},{id:'tool',name:T('CMP 机台 · 小野','CMP装置 · 小野さん'),short:T('机台巡检','装置点検'),x:50,y:35,icon:'⚙',room:T('设备区','装置エリア')},{id:'metrology',name:T('量测室 · 陈工','測定室 · 陳さん'),short:T('量测检查','測定チェック'),x:80,y:35,icon:'◈',room:T('量测区','測定エリア')},{id:'desk',name:T('我的工位','自席'),short:T('数据与报告','データとレポート'),x:20,y:65,icon:'▤',room:T('办公区','オフィスエリア')},{id:'lab',name:T('工程实验台','実験台'),short:T('受控验证','管理下の検証'),x:50,y:65,icon:'⌬',room:T('实验区','実験エリア')},{id:'break',name:T('休息角','休憩コーナー'),short:T('休息恢复','休憩・回復'),x:80,y:65,icon:'☕',room:T('休息区','休憩エリア')},{id:'exit',name:T('打卡下班','退勤'),short:T('下班','退勤'),x:93,y:50,icon:'⇥',room:'出口'}];
const newShift=()=>({minute:510,energy:100,briefed:false,routine:false,problem:null,hyp:null,initialHyp:null,opened:[],tests:[],valid:false,fix:null,pm:null,notes:'',talked:[],breaks:0,report:false,clocked:false,studied:false,studyWrong:0,log:[],xpAward:0,quizMiss:0});
const fresh=()=>{const g={version:2,day:1,xp:0,rapport:{lead:0,tool:0,metrology:0},history:[],position:{x:50,y:51},shift:newShift(),muted:true};ensureOrder(g);return g};
/* 案例顺序：每 6 天一轮，一轮内 6 个案例各出现一次、顺序随机；第一轮第 1 天固定为案例 0 作为入门。顺序存在 g.order，读档后不变。 */
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function ensureOrder(g){const loop=Math.floor((g.day-1)/6);if(Array.isArray(g.order)&&g.order.length===6&&g.orderLoop===loop)return;g.order=loop===0?[0,...shuffle([1,2,3,4,5])]:shuffle([0,1,2,3,4,5]);g.orderLoop=loop;}
const caseIndex=g=>{const i=(g.day-1)%6;return Array.isArray(g.order)&&g.order.length===6?g.order[i]:i};
const levels=[[T('见习工程师','見習いエンジニア'),0],[T('数据观察者','データ観察者'),100],[T('工艺调查员','プロセス調査員'),230],[T('验证实践者','検証実践者'),380],[T('改善推动者','改善推進者'),550],[T('资深学员','上級研修生'),750]];
const rank=g=>levels.filter(x=>g.xp>=x[1]).at(-1)[0];
const time=g=>`${String(Math.floor(g.shift.minute/60)).padStart(2,'0')}:${String(g.shift.minute%60).padStart(2,'0')}`;
function score(g,c){const s=g.shift,ix=caseIndex(g),required=c.required.every(i=>s.opened.includes(i));const change=s.opened.includes([0,1,2,3,1,1][ix]);return [
 [T('问题定义','問題定義'),s.problem===0?10:0,10],[T('变化与差异','変化と差異'),change?10:0,10],[T('数据请求','データ要求'),Math.round(s.opened.filter(i=>c.required.includes(i)).length/c.required.length*15),15],[T('假设质量','仮説の質'),s.hyp===c.answer?15:0,15],[T('验证设计','検証設計'),s.valid?Math.max(8,15-s.tests.filter(i=>!c.tests[i].good).length*3):0,15],[T('根因证据','根本原因のエビデンス'),s.valid&&required&&s.hyp===c.answer?15:0,15],[T('纠正措施','是正処置'),s.fix===c.fix?10:0,10],[T('再发防止','再発防止'),s.pm===c.pm?10:0,10]]}
function spend(g,time,energy,label){if(g.shift.report)throw Error(T('今日已结案，请前往出口下班。','本日は完了済みです。出口で退勤してください。'));if(g.shift.energy<energy)throw Error(T('专注力不足，先去休息角恢复一下。','集中力が足りません。まず休憩コーナーで少し回復してください。'));g.shift.minute+=time;g.shift.energy-=energy;g.shift.log.push({at:timeString(g.shift.minute),text:label});}
function timeString(v){return `${String(Math.floor(v/60)).padStart(2,'0')}:${String(v%60).padStart(2,'0')}`}
function choose(g,key,n,c){if(!['problem','hyp','fix','pm'].includes(key)||!Number.isInteger(n)||n<0||n>=3)throw Error(T('无效选择','無効な選択です'));if(g.shift.report)throw Error(T('已结案，判断已锁定。','完了済みのため、判断は確定されています。'));g.shift[key]=n;if(key==='hyp'&&g.shift.initialHyp===null)g.shift.initialHyp=n;}
function brief(g){if(g.shift.briefed)throw Error(T('已参加晨会','朝会には参加済みです'));if(g.shift.problem===null||g.shift.hyp===null)throw Error(T('先选择问题定义和暂定假设。','まず問題定義と暫定仮説を選択してください。'));spend(g,15,4,T('晨会：明确今日调查目标','朝会：本日の調査目標を確認'));g.shift.briefed=true;}
function routine(g,correct){if(!g.shift.briefed)throw Error(T('先参加晨会，了解今日工作。','まず朝会に参加して、本日の業務を確認してください。'));if(g.shift.routine)throw Error(T('今日巡检已完成','本日の点検は完了済みです'));spend(g,correct?15:5,correct?6:2,correct?T('完成机台开工巡检','装置の始業点検を完了'):T('巡检判断需要修正','点検の判断に修正が必要'));if(correct)g.shift.routine=true;else g.shift.quizMiss++;}
function unlock(g,c,i,station){if(!Number.isInteger(i)||i<0||i>=c.evidence.length)throw Error(T('无效调查编号','無効な調査番号です'));if(!g.shift.briefed||!g.shift.routine)throw Error(T('先完成晨会和机台巡检。','まず朝会と装置点検を完了してください。'));if(sources[caseIndex(g)][i]!==station)throw Error(T('请前往对应工作站取证。','該当するステーションでエビデンスを取得してください。'));if(g.shift.opened.includes(i))return;spend(g,c.evidence[i].cost,7,T(`取得证据 E${i+1}：${c.evidence[i].name}`,`エビデンス E${i+1} を取得：${c.evidence[i].name}`));g.shift.opened.push(i);}
function test(g,c,i){if(!Number.isInteger(i)||i<0||i>=c.tests.length)throw Error(T('无效实验','無効な実験です'));if(g.shift.opened.length<2)throw Error(T('至少收集两项证据，再设计实验。','少なくとも 2 件のエビデンスを集めてから、実験を設計してください。'));if(g.shift.tests.includes(i)||g.shift.valid)throw Error(T('实验已执行，请回工位整理结论。','実験は実施済みです。自席に戻って結論をまとめてください。'));spend(g,25,12,c.tests[i].good?T('完成受控验证','管理下の検証を完了'):T('实验设计复核：证据仍不足','実験設計の見直し：エビデンスがまだ不足'));g.shift.tests.push(i);g.shift.valid=c.tests[i].good;}
function talk(g,id){if(!['lead','tool','metrology'].includes(id))throw Error(T('这里没有同事','ここには同僚がいません'));if(!g.shift.briefed)throw Error(T('先完成晨会。','まず朝会を完了してください。'));if(g.shift.talked.includes(id))return false;spend(g,10,2,T(`与${stations.find(s=>s.id===id).name.split(' · ')[1]}交流`,`${stations.find(s=>s.id===id).name.split(' · ')[1]}と会話`));g.shift.talked.push(id);g.rapport[id]=(g.rapport[id]||0)+1;return true;}
function rest(g){if(g.shift.report)throw Error(T('今天已结案，可以下班休息了。','本日は完了済みです。退勤して休んでください。'));if(g.shift.energy===100)throw Error(T('现在精力充足，休息角随时欢迎你。','今は集中力が十分です。休憩コーナーはいつでも利用できます。'));g.shift.minute+=20;g.shift.energy=Math.min(100,g.shift.energy+35);g.shift.breaks++;g.shift.log.push({at:time(g),text:T('休息 20 分钟，恢复 35 点专注力','20 分休憩し、集中力を 35 回復')});}
function submit(g,c){const s=g.shift;if(s.report)throw Error(T('已经结案','すでに完了済みです'));{const miss=[[!s.routine,T('机台巡检','装置点検')],[s.opened.length<2,T(`取证（已有 ${s.opened.length} 项，需要 2 项）`,`エビデンス取得（現在 ${s.opened.length} 件、2 件必要）`)],[!s.tests.length,T('在实验台做一次实验','実験台での実験 1 回')],[s.problem===null,T('问题定义','問題定義')],[s.hyp===null,T('当前优先假设','現在の最優先仮説')],[s.fix===null,T('纠正措施','是正処置')],[s.pm===null,T('防止再次发生','再発防止')]].filter(x=>x[0]).map(x=>x[1]);if(miss.length)throw Error(T('还不能提交，缺：','まだ提出できません。不足：')+miss.join(T('、','、')));}spend(g,20,8,T('完成结案报告，准备交班','最終報告を完了し、引き継ぎを準備'));s.report=true;const total=score(g,c).reduce((n,r)=>n+r[1],0);s.xpAward=total+10+s.talked.length*2;g.xp+=s.xpAward;return total;}
function clockout(g,c){if(!g.shift.report)throw Error(T('先回工位完成结案报告。','まず自席に戻って最終報告を完了してください。'));if(g.shift.clocked)return;g.shift.clocked=true;g.history.push({day:g.day,case:caseIndex(g),score:score(g,c).reduce((n,r)=>n+r[1],0),xp:g.shift.xpAward,minute:g.shift.minute});}
function study(g,correct){if(!g.shift.clocked)throw Error(T('下班后可以温习术语','用語の復習は退勤後にできます'));if(g.shift.studied)throw Error(T('今日温习已完成','本日の復習は完了済みです'));if(correct){g.shift.studied=true;g.xp+=5;}else g.shift.studyWrong++;}
function nextDay(g){if(!g.shift.clocked)throw Error(T('还没有打卡下班','まだ退勤していません'));g.day++;g.shift=newShift();g.position={x:50,y:51};ensureOrder(g);}
function normalize(raw){if(!raw||raw.version!==2||!Number.isInteger(raw.day)||raw.day<1||!raw.shift||!Array.isArray(raw.history))return fresh();const g={...fresh(),...raw,shift:{...newShift(),...raw.shift}};if(!Number.isFinite(g.xp)||!Number.isFinite(g.shift.energy)||!Number.isFinite(g.shift.minute))return fresh();g.position={x:Math.max(7,Math.min(93,Number(g.position?.x)||50)),y:Math.max(32,Math.min(68,Number(g.position?.y)||51))};if(!Array.isArray(raw.order)||raw.order.length!==6){g.order=[0,1,2,3,4,5];g.orderLoop=Math.floor((g.day-1)/6)}else ensureOrder(g);return g;}
root.CMP_RPG={fresh,newShift,caseIndex,ensureOrder,stations,sources,levels,rank,time,score,choose,brief,routine,unlock,test,talk,rest,submit,clockout,study,nextDay,normalize};
})(globalThis);
