/* 轮廓调整练习界面（中文 / 日本語，使用 i18n.js 的 T）。逻辑在 profilesim.js。 */
const P=CMP_PROFILE,PKEY='cmp-fab-profile-v1',$=id=>document.getElementById(id);
let store={current:0,states:{},stars:{}},toastTimer=null;
try{const raw=JSON.parse(localStorage.getItem(PKEY)||'null');if(raw&&raw.states&&typeof raw.current==='number')store={current:Math.max(0,Math.min(P.CASES.length-1,raw.current)),states:raw.states,stars:raw.stars||{}}}catch(e){}
const st=()=>store.states[store.current]||(store.states[store.current]=P.fresh(store.current));
function persist(){try{localStorage.setItem(PKEY,JSON.stringify(store))}catch(e){}}
function toast(s){clearTimeout(toastTimer);(h=>{if($('toast').parentNode!==h)h.appendChild($('toast'))})(document.querySelector('dialog[open]')||document.body);$('toast').textContent=s;$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,3800)}
function dialog(title,area,body){$('dlgTitle').textContent=title;$('dlgArea').textContent=area;$('dialogBody').innerHTML=body;if(!$('labDialog').open)$('labDialog').showModal();$('labDialog').scrollTop=0}
const ERR={'err.zone':T('分区压力超出范围。','ゾーン圧力が範囲外です。'),'err.ring':T('保持环压力超出范围。','リテーナリング圧力が範囲外です。'),'err.time':T('研磨时间超出范围。','研磨時間が範囲外です。'),'err.slip':T('保持环压力低于边缘区的 0.9 倍：晶圆有滑出风险，机台拒绝运行。','リテーナリング圧力がエッジゾーンの 0.9 倍未満です。ウェーハ飛び出しのリスクがあるため、装置が処理を拒否しました。'),'err.budget':T('本关的监控片额度用完了。点“重来本关”。','この練習のモニターウェーハ枠を使い切りました。「この練習をやり直す」を押してください。'),'err.cleared':T('本关已过关。','この練習はクリア済みです。')};
const DEBRIEF=[
 T('这台机台的固有特征是“中心快”。降低中心区（Z1、Z2）、略提高外侧区，就能拉平。平均去除量会跟着变，所以最后用研磨时间把膜厚拉回目标。','この号機はもともとセンターファストの傾向がありました。中心側のゾーン（Z1、Z2）を下げ、外側を少し上げると平坦になります。平均除去量も変わるので、最後に研磨時間で膜厚を狙い値に戻します。'),
 T('边缘快的原因在保持环压力偏低：垫在晶圆边缘回弹，边缘被多磨。只降 Z4 会连 0.8 半径附近一起拉低；提高保持环压力才是针对最外圈的手段。','エッジファストの原因はリテーナリング圧力が低いことでした。パッドがウェーハのエッジで跳ね返り、エッジが余分に削れます。Z4 だけを下げると半径 0.8 付近まで一緒に下がってしまいます。最外周に効くのはリテーナリング圧力です。'),
 T('半径中段偏慢（甜甜圈形）。对应的是 Z2。注意各区的影响会渗到相邻区，所以调 Z2 之后 Z1、Z3 往往要反向微调一点。','半径の中間部が遅い（ドーナツ形）ケースでした。対応するのは Z2 です。各ゾーンの影響は隣のゾーンにもにじむため、Z2 を上げた後は Z1 と Z3 を少し逆方向に微調整する必要が出ます。'),
 T('两个问题叠在一起：中心快 + 保持环压力过高导致边缘慢。先把它们分开看——先调保持环压力处理最外圈，再调各区处理整体坡度。一次改一样，才看得出每一步的效果。','二つの問題が重なっていました。センターファストと、リテーナリング圧力が高すぎることによるエッジスローです。分けて考えるのがコツです。まずリテーナリング圧力で最外周を直し、次に各ゾーンで全体の傾きを直します。一度に一つずつ変えると、各ステップの効果が見えます。'),
 T('最外圈不仅偏快，而且每一片都不一样。不重复的问题靠调配方解决不了：同样的设定，这片合格、下一片不合格。原因是保持环磨损。先做重复确认，发现不重复就去查硬件，是这一关要练的判断。','最外周が速いだけでなく、1枚ごとに値が変わっていました。再現しない問題はレシピ調整では解決できません。同じ設定でも、合格する枚としない枚が出ます。原因はリテーナリングの摩耗でした。まず繰り返しで再現性を確認し、再現しなければハードを疑う。これがこの練習で身につけたい判断です。')];

function headSVG(s){
  const avg=s.zones.reduce((a,b)=>a+b,0)/4,col=(p,ref=avg)=>{const q=Math.max(0,Math.min(1,(p-ref)/1.2+.5));return `rgb(${Math.round(60+185*q)},${Math.round(150+40*q)},${Math.round(200-110*q)})`},R=[34,64,88,104];
  return `<svg class="headSvg" viewBox="0 0 260 260" role="img" aria-label="${T('研磨头俯视示意：四个同心压力区和外圈保持环','研磨ヘッドの上面図：4つの同心ゾーンと外周のリテーナリング')}"><circle cx="130" cy="130" r="122" fill="none" stroke="${col(s.ring,1.5*s.zones[3])}" stroke-width="12"/>${[3,2,1,0].map(i=>`<circle cx="130" cy="130" r="${R[i]}" fill="${col(s.zones[i])}" stroke="#102b38" stroke-width="2"/>`).join('')}${[0,1,2,3].map(i=>`<text x="130" y="${130-(i?R[i-1]+(R[i]-R[i-1])/2:0)+4}" text-anchor="middle" font-size="12" fill="#0e2630" font-weight="700">Z${i+1}</text>`).join('')}<text x="130" y="16" text-anchor="middle" font-size="11" fill="#d8e6e2">${T('保持环','リテーナリング')}</text></svg>`;
}
function slider(id,label,val,[lo,hi,step],unit){return `<div class="knob"><label for="s-${id}">${label} <span class="small">${unit}</span></label><input class="num" id="n-${id}" data-set="${id}" type="number" min="${lo}" max="${hi}" step="${step}" value="${val}"><input id="s-${id}" data-set="${id}" type="range" min="${lo}" max="${hi}" step="${step}" value="${val}"></div>`}
function chartSVG(s){
  const cur=s.runs.at(-1),prev=s.runs.at(-2),W=620,H=260,x0=46,x1=W-14,y0=18,y1=H-34;
  if(!cur)return `<p class="small chartEmpty">${T('还没有数据。先保持原设定研磨 1 片，读出轮廓的形状。','まだデータがありません。まず設定を変えずに1枚研磨して、プロファイルの形を読み取りましょう。')}</p>`;
  const all=[...cur.points,...(prev?prev.points:[])].map(p=>p.removal),mid=cur.mean,span=Math.max(12,Math.max(...all.map(v=>Math.abs(v-mid)))*1.25),lo=mid-span,hi=mid+span;
  const X=x=>x0+(x+1)/2*(x1-x0),Y=v=>y1-(v-lo)/(hi-lo)*(y1-y0),line=run=>run.points.map(p=>`${X(p.x)},${Y(p.removal)}`).join(' ');
  const band=mid*P.SPEC.nu/100*2; /* ±2σ 目标带，仅作视觉参考 */
  return `<svg class="spc" viewBox="0 0 ${W} ${H}" role="img" aria-label="${T('沿直径的去除量轮廓','直径方向の除去量プロファイル')}"><rect x="${x0}" y="${Y(mid+band)}" width="${x1-x0}" height="${Y(mid-band)-Y(mid+band)}" fill="#79dbc122"/><line x1="${x0}" x2="${x1}" y1="${Y(mid)}" y2="${Y(mid)}" class="center"/><text x="4" y="${Y(mid)+4}" class="axis">${Math.round(mid)}</text><text x="4" y="${Y(hi)+10}" class="axis">${Math.round(hi)}</text><text x="4" y="${Y(lo)}" class="axis">${Math.round(lo)}</text>${[-1,-.5,0,.5,1].map(v=>`<line x1="${X(v)}" x2="${X(v)}" y1="${y0}" y2="${y1}" class="daySep"/><text x="${X(v)}" y="${H-14}" text-anchor="middle" class="axis">${v===0?T('中心','中心'):v}</text>`).join('')}${prev?`<polyline points="${line(prev)}" fill="none" stroke="#8aa7ad" stroke-width="1.5" stroke-dasharray="5 4"/>`:''}<polyline points="${line(cur)}" class="trace"/>${cur.points.map(p=>`<circle cx="${X(p.x)}" cy="${Y(p.removal)}" r="3.2" class="okpt"><title>r=${p.x}：${p.removal} nm</title></circle>`).join('')}</svg><p class="small axisNote">${T('横轴：半径位置（−1 … +1，边缘排除 3 mm）· 纵轴：去除量 nm。研磨头图：颜色越暖表示该区压力相对越高。','横軸：半径位置（−1 … +1、エッジ除外 3 mm）· 縦軸：除去量 nm。ヘッド図は、色が暖かいほどそのゾーンの圧力が相対的に高いことを示します。')}</p><div class="chartLegend"><span class="lg center">${T('本片平均','この枚の平均')}</span><span class="lg prev">${T('上一片（虚线）','前の1枚（破線）')}</span><span class="lg bandLg">${T('参考带 ±2%','目安の帯 ±2%')}</span></div>`;
}
function render(){
  const s=st(),cur=s.runs.at(-1),prev=s.runs.at(-2),left=P.BUDGET-s.used;
  $('caseTabs').innerHTML=P.CASES.map((c,i)=>`<button data-case="${i}" class="${i===store.current?'selected':''}">${T('练习','練習')} ${i+1} <span class="stars">${'★'.repeat(store.stars[i]||0)}${'☆'.repeat(3-(store.stars[i]||0))}</span></button>`).join('');
  $('controls').innerHTML=`<div class="toolHead"><h2>${T('研磨头设定','研磨ヘッドの設定')}</h2><span class="toolState ${left<=3?'isDown':''}">${T(`监控片额度 ${left} / ${P.BUDGET}`,`モニターウェーハ枠 ${left} / ${P.BUDGET}`)}</span></div><p class="small">${T('目标：平均膜厚 195–205 nm，片内非均匀度 ≤ 1.0%，并且<b>同一设定连续两片</b>都合格。先跑一片基准，读出形状，再决定调哪里。','目標：平均膜厚 195–205 nm、面内不均一性 ≤ 1.0%、かつ<b>同じ設定で2枚連続</b>合格すること。まず1枚ベースラインを取り、形を読んでから、どこを調整するか決めます。')}</p><div class="headRow">${headSVG(s)}<div class="zoneList">${[0,1,2,3].map(i=>slider('z'+i,`Z${i+1} ${[T('中心','中心'),T('中间','中間'),T('外侧','外側'),T('边缘','エッジ')][i]}`,s.zones[i],P.LIMITS.zone,'psi')).join('')}</div></div>${slider('ring',T('保持环压力','リテーナリング圧力'),s.ring,P.LIMITS.ring,'psi')}${slider('time',T('研磨时间','研磨時間'),s.time,P.LIMITS.time,'s')}<div class="runControls"><button class="primary" data-do="polish" ${s.cleared?'disabled':''}>${T('▶ 研磨 1 片','▶ 1枚研磨')}<small>−${P.COST.run}</small></button><button data-do="inspect" ${s.cleared?'disabled':''}>${T('检查研磨头与保持环','ヘッドとリテーナリングを点検')}<small>−${P.COST.inspect}</small></button><button data-do="ring" ${s.cleared?'disabled':''}>${T('更换保持环','リテーナリング交換')}<small>−${P.COST.ring}</small></button><button data-do="reset">${T('重来本关','この練習をやり直す')}</button></div>${s.inspected?`<div class="notice ${s.wear>.2?'':'good'}">${s.wear>.2?T('检查结果：保持环内缘磨损严重，超过管理值。','点検結果：リテーナリング内周の摩耗が大きく、管理値を超えています。'):T('检查结果：保持环磨损在管理值以内，研磨头膜无异常。','点検結果：リテーナリングの摩耗は管理値内で、メンブレンにも異常はありません。')}</div>`:''}`;
  const tile=(label,val,bad)=>`<div class="metricTile ${bad?'fail':''}"><small>${label}</small><strong>${val}</strong></div>`;
  $('results').innerHTML=`<div class="toolHead"><h2>${T('直径扫描结果','直径スキャン結果')}</h2>${cur?`<span class="toolState ${cur.pass?'':'isDown'}">${cur.pass?T('本片合格','この枚は合格'):T('本片不合格','この枚は不合格')}</span>`:''}</div>${chartSVG(s)}${cur?`<div class="resultMetrics">${tile(T('平均膜厚 nm','平均膜厚 nm'),cur.thickness,cur.thickness<P.SPEC.lo||cur.thickness>P.SPEC.hi)}${tile(T('非均匀度 %','面内不均一性 %'),cur.nu.toFixed(2),cur.nu>P.SPEC.nu)}${tile(T('最大−最小 nm','最大−最小 nm'),cur.range,false)}${tile(T('与上一片的非均匀度差','前の1枚との差 %'),prev?(cur.nu-prev.nu>0?'+':'')+(cur.nu-prev.nu).toFixed(2):'—',false)}</div>`:''}${s.cleared?`<div class="notice good"><b>${T('过关','クリア')} ${'★'.repeat(P.stars(s))}</b>（${T(`用了 ${s.used} 个额度`,`使用枠 ${s.used}`)}）<p>${DEBRIEF[store.current]}</p>${store.current<P.CASES.length-1?`<button class="primary" data-case="${store.current+1}">${T('下一关 →','次の練習へ →')}</button>`:`<p>${T('五关全部完成。','5つの練習をすべて完了しました。')}</p>`}</div>`:cur&&cur.pass?`<div class="notice">${T('这一片合格了。不要改设定，再跑一片确认能重复。','この枚は合格です。設定を変えずにもう1枚研磨して、再現することを確認しましょう。')}</div>`:''}`;
  $('history').innerHTML=`<h3>${T('试片记录','ウェーハ記録')}</h3>${s.runs.length?`<div class="tableWrap"><table class="simTable"><thead><tr><th>#</th><th>Z1</th><th>Z2</th><th>Z3</th><th>Z4</th><th>${T('保持环','リング')}</th><th>${T('时间 s','時間 s')}</th><th>${T('膜厚 nm','膜厚 nm')}</th><th>${T('非均匀度 %','不均一性 %')}</th><th>${T('判定','判定')}</th></tr></thead><tbody>${[...s.runs].reverse().map(r=>`<tr><td>${r.id}${r.replaced?' ◎':''}</td>${r.zones.map(z=>`<td>${z}</td>`).join('')}<td>${r.ring}</td><td>${r.time}</td><td class="${r.thickness<P.SPEC.lo||r.thickness>P.SPEC.hi?'fail':''}">${r.thickness}</td><td class="${r.nu>P.SPEC.nu?'fail':''}">${r.nu.toFixed(2)}</td><td class="${r.pass?'pass':'fail'}">${r.pass?'OK':'NG'}</td></tr>`).join('')}</tbody></table></div><p class="small">${T('◎ = 更换保持环之后的试片。','◎ = リテーナリング交換後のウェーハ。')}</p>`:`<p class="small">${T('还没有试片。','まだウェーハがありません。')}</p>`}`;
  persist();
}
function help(){dialog(T('轮廓调整怎么练','プロファイル調整の進め方'),'HOW TO',T('<h3>这是在练什么</h3><p>研磨头把晶圆背面分成几个同心的压力区，各区压力可以单独设定，用来修正“中心快”或“边缘快”的去除轮廓。把径向轮廓调平，是 CMP 工艺工程师最日常的工作之一。</p><h3>怎么读图</h3><p>图是沿晶圆直径扫描的去除量。中间高就是中心快，两端翘就是边缘快，中段凹就是中段慢。虚线是上一片，用来看你这一步改动的效果。</p><h3>几条经验</h3><p>① 先跑一片基准再动手。② 一次只改一样，否则看不出谁起了作用。③ 各区的影响会渗到相邻区，不是一刀切。④ 保持环压力主要影响最外圈：相对边缘区越高，边缘越慢；太低晶圆会滑出，机台会拒绝运行。⑤ 调区压会改变平均去除量，最后用时间把膜厚拉回目标。⑥ 合格一片不算数，同一设定连续两片合格才过关。⑦ 如果同样的设定每片结果都不一样，那不是配方问题。</p><p class="small">区的数量、影响范围和全部数值都是游戏设定，真实研磨头的分区和响应因机型而异。</p>','<h3>何を練習するか</h3><p>研磨ヘッドはウェーハ裏面を複数の同心ゾーンに分け、ゾーンごとに圧力を設定できます。これでセンターファストやエッジファストといった除去プロファイルを補正します。半径方向のプロファイルを平坦にすることは、CMPプロセスエンジニアの最も日常的な仕事の一つです。</p><h3>グラフの読み方</h3><p>グラフはウェーハ直径方向にスキャンした除去量です。中央が高ければセンターファスト、両端が上がっていればエッジファスト、中間がへこんでいれば中間部が遅い状態です。破線は前の1枚で、今回の変更の効果を確認するためのものです。</p><h3>コツ</h3><p>① まず1枚ベースラインを取ってから調整する。② 一度に変えるのは一つだけ。そうしないと何が効いたのか分かりません。③ 各ゾーンの影響は隣のゾーンにもにじみます。④ リテーナリング圧力は主に最外周に効きます。エッジゾーンに対して高いほどエッジは遅くなり、低すぎるとウェーハが飛び出すため、装置が処理を拒否します。⑤ ゾーン圧力を変えると平均除去量も変わるので、最後に研磨時間で膜厚を狙い値に戻します。⑥ 1枚合格しただけでは不十分で、同じ設定で2枚連続合格してクリアです。⑦ 同じ設定なのに1枚ごとに結果が変わるなら、それはレシピの問題ではありません。</p><p class="small">ゾーンの数、影響範囲、数値はすべてゲーム用の設定です。実際の研磨ヘッドのゾーン構成と応答は機種によって異なります。</p>'))}
document.addEventListener('input',e=>{const k=e.target.dataset.set;if(!k)return;const s=st(),v=Number(e.target.value);if(!Number.isFinite(v))return;if(k==='ring')s.ring=v;else if(k==='time')s.time=Math.round(v);else s.zones[Number(k[1])]=Math.round(v*10)/10;const other=$((e.target.type==='range'?'n-':'s-')+k);if(other)other.value=e.target.value;const hs=document.querySelector('.headSvg');if(hs)hs.outerHTML=headSVG(s);persist()});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;
  try{
    if(b.dataset.case!==undefined){store.current=Number(b.dataset.case);render();return}
    const s=st();
    if(b.dataset.do==='polish'){const r=P.polish(s);if(s.cleared){store.stars[store.current]=Math.max(store.stars[store.current]||0,P.stars(s));toast(T('过关！','クリア！'))}else toast(r.pass?T('合格。再跑一片确认重复性。','合格。もう1枚で再現性を確認しましょう。'):T('已研磨，看图。','研磨しました。グラフを確認してください。'))}
    else if(b.dataset.do==='inspect')P.inspect(s);
    else if(b.dataset.do==='ring'){P.replaceRing(s);toast(T('保持环已更换。','リテーナリングを交換しました。'))}
    else if(b.dataset.do==='reset')store.states[store.current]=P.fresh(store.current);
    else return;
    render();
  }catch(err){toast(ERR[err.message]||err.message)}
});
$('langButton').onclick=()=>{persist();setLang(LANG==='ja'?'zh':'ja')};$('helpButton').onclick=help;$('dlgClose').onclick=()=>$('labDialog').close();
render();if(!Object.keys(store.stars).length&&!st().runs.length)help();
