/* 学习记录页：把各模式保存在本浏览器里的进度汇总成一页，可打印或另存为 PDF。
   只读取数据，不修改任何存档。全部数据来自本设备的 localStorage，是自我记录，不是第三方认证。 */
const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=k=>{try{return JSON.parse(localStorage.getItem(k)||'null')}catch(e){return null}};
const JA=LANG==='ja',KB=CMP_KB,S=CMP_SIM;
const drillsAll=[...KB.drills,...(globalThis.CMP_FLOW?CMP_FLOW.drills:[]),...(globalThis.CMP_SAFETY?CMP_SAFETY.drills:[])].filter((d,i,a)=>a.findIndex(x=>x.id===d.id)===i);
function render(){
  const g=read('cmp-fab-practical-v1'),line=read('cmp-fab-line-v1'),prof=read('cmp-fab-profile-v1'),def=read('cmp-fab-defects-v1'),time=read('cmp-fab-time')||{};
  const hist=(g&&Array.isArray(g.history)?g.history:[]).filter(h=>h.simArchive),learn=(g&&g.learn)||{},dr=learn.drills||{},fm=learn.fmea||{};
  const best=S.scenarios.map((sc,i)=>{const hs=hist.filter(h=>h.case===i);return {title:sc.title,plays:hs.length,best:hs.length?Math.max(...hs.map(h=>h.score)):null,wafers:hs.reduce((n,h)=>n+h.simArchive.runs.length,0)}});
  const lineDays=line&&line.state&&Array.isArray(line.state.history)?line.state.history:[];
  const lvl=[T('还讲不清','まだ説明できない'),T('基本能讲','だいたい説明できる'),T('能流利讲','流暢に説明できる')];
  const practiced=drillsAll.filter(d=>dr[d.id]),fluent=practiced.filter(d=>dr[d.id].level===2);
  const fmRows=KB.fmea.filter(r=>fm[r.id]&&fm[r.id].s&&fm[r.id].o&&fm[r.id].d).map(r=>({r,v:fm[r.id],rpn:fm[r.id].s*fm[r.id].o*fm[r.id].d})).sort((a,b)=>b.rpn-a.rpn);
  const mins=Object.values(time).reduce((a,b)=>a+(Number(b)||0),0),pageName={index:T('研修中心与手册','研修センターとハンドブック'),shift:T('量产值班','量産シフト'),profile:T('轮廓调整练习','プロファイル調整ラボ'),defects:T('缺陷图练习','欠陥マップラボ')};
  const avg=a=>a.length?Math.round(a.reduce((x,y)=>x+y,0)/a.length):'—';
  const none=`<p class="muted">${T('还没有记录。','まだ記録がありません。')}</p>`;
  $('sheet').innerHTML=`
<header class="recHead"><div><h1>${T('CMP 学习记录','CMP 学習記録')}</h1><p class="muted">Fab Days · CMP Learning Simulator</p></div><div class="recMeta"><label>${T('姓名','氏名')}<input id="recName" value="${esc(read('cmp-fab-record-name')||'')}" placeholder="${T('（打印前填写）','（印刷前に入力）')}"></label><span>${T('生成日期','作成日')}：${new Date().toLocaleDateString(JA?'ja-JP':'zh-CN')}</span></div></header>
<section><h2>${T('1. 概要','1. 概要')}</h2><div class="recTiles"><div><b>${best.filter(b=>b.plays).length} / 6</b><span>${T('完成的研修场景','完了した研修シナリオ')}</span></div><div><b>${hist.length}</b><span>${T('研修天数','研修日数')}</span></div><div><b>${lineDays.length}</b><span>${T('量产值班天数','量産シフト日数')}</span></div><div><b>${fluent.length} / ${drillsAll.length}</b><span>${T('能流利讲的面试题','流暢に説明できる想定問答')}</span></div><div><b>${mins?(mins/60).toFixed(1)+' h':'—'}</b><span>${T('累计使用时间','累計使用時間')}</span></div></div></section>
<section><h2>${T('2. 研修中心：六个故障场景','2. 研修センター：6つの異常シナリオ')}</h2><table><thead><tr><th>#</th><th>${T('场景','シナリオ')}</th><th>${T('次数','回数')}</th><th>${T('最高实验习惯分','実験習慣スコア最高点')}</th><th>${T('使用试片','使用ウェーハ')}</th></tr></thead><tbody>${best.map((b,i)=>`<tr><td>${i+1}</td><td>${esc(b.title)}</td><td>${b.plays||'—'}</td><td>${b.best??'—'}</td><td>${b.wafers||'—'}</td></tr>`).join('')}</tbody></table><p class="muted">${T('评分项：基准记录、可追溯试验、单变量对照、重复确认、最终方案达标、量测核查（满分 100）。','評価項目：ベースライン、追跡可能な試験、一因子比較、繰り返し確認、最終案の合格、測定の検証（100 点満点）。')}</p></section>
<section><h2>${T('3. 专项练习','3. 専用ラボ')}</h2><table><thead><tr><th>${T('练习','ラボ')}</th><th>${T('结果','結果')}</th></tr></thead><tbody><tr><td>${T('轮廓调整（分区压力，5 关）','プロファイル調整（ゾーン圧力、5 問）')}</td><td>${prof&&prof.stars&&Object.keys(prof.stars).length?[0,1,2,3,4].map(i=>`${i+1}: ${'★'.repeat(prof.stars[i]||0)||'—'}`).join('　'):'—'}</td></tr><tr><td>${T('缺陷图判读（8 题，每题 100 分）','欠陥マップ判読（8 問、各 100 点）')}</td><td>${def&&def.best&&Object.keys(def.best).length?[0,1,2,3,4,5,6,7].map(i=>`${i+1}: ${def.best[i]??'—'}`).join('　'):'—'}</td></tr></tbody></table></section>
<section><h2>${T('4. 量产值班','4. 量産シフト')}</h2>${lineDays.length?`<p>${T(`值班 ${lineDays.length} 天，平均 ${avg(lineDays.map(d=>d.score.total))} 分，最高 ${Math.max(...lineDays.map(d=>d.score.total))} 分；解决异常 ${lineDays.reduce((n,d)=>n+d.revealed.length,0)} 件；不良流出 ${lineDays.reduce((n,d)=>n+d.kpi.escape,0)} 批，误报废 ${lineDays.reduce((n,d)=>n+d.kpi.falseScrap,0)} 批。`,`シフト ${lineDays.length} 日、平均 ${avg(lineDays.map(d=>d.score.total))} 点、最高 ${Math.max(...lineDays.map(d=>d.score.total))} 点。解決した異常 ${lineDays.reduce((n,d)=>n+d.revealed.length,0)} 件、不良流出 ${lineDays.reduce((n,d)=>n+d.kpi.escape,0)} ロット、誤廃棄 ${lineDays.reduce((n,d)=>n+d.kpi.falseScrap,0)} ロット。`)}</p><table><thead><tr><th>${T('天','日')}</th><th>${T('总分','総合')}</th><th>${T('合格出货','良品出荷')}</th><th>${T('报废','廃棄')}</th><th>${T('不良流出','不良流出')}</th><th>${T('停机 h','停止 h')}</th><th>Cpk A / B</th><th>${T('交接记录','引き継ぎ')}</th></tr></thead><tbody>${lineDays.slice(-10).map(d=>`<tr><td>${d.day}</td><td>${d.score.total}</td><td>${d.kpi.good}</td><td>${d.kpi.scrap+d.kpi.falseScrap}</td><td>${d.kpi.escape}</td><td>${d.kpi.down}</td><td>${d.cpk?(d.cpk.A??'—')+' / '+(d.cpk.B??'—'):'—'}</td><td>${d.note&&d.note.trim()?'✓':'—'}</td></tr>`).join('')}</tbody></table>${lineDays.length>10?`<p class="muted">${T('只显示最近 10 天。','直近 10 日分のみ表示。')}</p>`:''}`:none}</section>
<section><h2>${T('5. 面试问答的自我评估','5. 面接想定問答の自己評価')}</h2>${practiced.length?`<table><thead><tr><th>${T('问题','質問')}</th><th>${T('练习次数','練習回数')}</th><th>${T('自评','自己評価')}</th><th>${T('写了自己的回答','自分の回答を記入')}</th></tr></thead><tbody>${practiced.map(d=>`<tr><td>${JA?d.qJa:d.qZh}</td><td>${dr[d.id].n}</td><td>${lvl[dr[d.id].level]||'—'}</td><td>${learn.answers&&learn.answers[d.id]&&learn.answers[d.id].text.trim()?'✓':'—'}</td></tr>`).join('')}</tbody></table>`:none}</section>
<section><h2>${T('6. FMEA 练习：我的风险排序','6. FMEA 演習：自分で付けたリスク順位')}</h2>${fmRows.length?`<table><thead><tr><th>${T('失效模式','故障モード')}</th><th>S</th><th>O</th><th>D</th><th>RPN</th></tr></thead><tbody>${fmRows.map(x=>`<tr><td>${JA?x.r.modeJa:x.r.mode}</td><td>${x.v.s}</td><td>${x.v.o}</td><td>${x.v.d}</td><td>${x.rpn}</td></tr>`).join('')}</tbody></table>`:none}</section>
${mins?`<section><h2>${T('7. 使用时间','7. 使用時間')}</h2><p>${Object.entries(time).map(([k,v])=>`${pageName[k]||k}: ${(v/60).toFixed(1)} h`).join('　·　')}</p><p class="muted">${T('只统计页面在前台显示的时间，从加入计时功能之后开始累计。','ページが前面に表示されている時間のみを集計しています。計測機能の追加以降の累計です。')}</p></section>`:''}
<footer class="recFoot">${T('本记录由模拟器根据保存在本设备浏览器里的数据自动生成，属于自我记录，不是第三方的认证。模拟器中的数值均为教学用设定，不是实际设备数据。','この記録は、この端末のブラウザに保存されたデータからシミュレーターが自動生成したものです。自己記録であり、第三者による認定ではありません。シミュレーター内の数値はすべて教育用の設定であり、実際の装置データではありません。')}</footer>`;
}
document.addEventListener('input',e=>{if(e.target.id==='recName'){try{localStorage.setItem('cmp-fab-record-name',JSON.stringify(e.target.value))}catch(err){}}});
$('printButton').onclick=()=>window.print();$('langButton').onclick=()=>setLang(JA?'zh':'ja');
render();
