const E=CMP_RPG, KEY='cmp-fab-days-v2';
let game=E.fresh(),saveWorks=true;
try{const raw=JSON.parse(localStorage.getItem(KEY)||'null');game=E.normalize(raw&&raw.sim?null:raw)}catch(e){saveWorks=false}
const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const caseNow=()=>CASES[E.caseIndex(game)],shift=()=>game.shift;
let target=null,openPlace=null,keys=new Set(),frameAt=0,toastTimer=null,briefIntro=true,noteTimer=null;
const people={lead:{name:T('林前辈','林先輩'),role:T('工艺导师','プロセス指導担当'),initial:'林'},tool:{name:T('小野','小野さん'),role:T('设备工程师','設備エンジニア'),initial:'野'},metrology:{name:T('陈工','陳さん'),role:T('量测工程师','測定エンジニア'),initial:T('陈','陳')}};
const morning=[
 T('欢迎来到研修中心。今天先别急着改研磨时间。请把“观察到什么”和“认为为什么”分开写，拿证据来找我。','研修センターへようこそ。今日は、いきなり研磨時間を変えるのはやめましょう。「何を観察したか」と「なぜそう考えるか」を分けて書き、エビデンスを持って私のところに来てください。'),
 T('今天我们沿着晶圆走过的路线调查。别因为最后在检查站看见缺陷，就假定缺陷一定在研磨时产生。','今日はウェーハが通ってきた経路に沿って調査します。最後の検査工程で欠陥が見つかったからといって、研磨中に発生したと決めつけないでください。'),
 T('日报上的平均值让大家有点紧张。你先问问：这两天比较的，到底是不是同一群产品？','日報の平均値を見て、みんな少し緊張しています。まず確認しましょう。この 2 日間で比較しているのは、本当に同じ製品群でしょうか？'),
 T('全部合格，也不代表过程一直稳定。先读控制计划，再决定如何响应今天的趋势。','すべて合格でも、工程がずっと安定しているとは限りません。まずコントロールプランを読み、それから今日の傾向にどう対応するかを決めましょう。'),
 T('今天可以用工程试片做实验。先把你要区分的因素讲清楚，再安排运行顺序和重复次数。','今日は評価用ウェーハで実験ができます。まず切り分けたい因子を明確にし、それから実行順序と繰り返し回数を決めてください。'),
 T('耗材还没坏，也是一种信息。今天不要只找一个更换片数，要解释这个决定有哪些证据和不确定性。','消耗品がまだ壊れていないことも、ひとつの情報です。今日は交換枚数をひとつ決めるだけでなく、その判断にどんなエビデンスと不確かさがあるのかを説明してください。')
];
const talkHints={lead:[T('什么数据会推翻你现在的假设？在行动前先写下来，能防止只寻找支持自己的证据。','どんなデータが出たら、今の仮説は否定されますか？行動する前に書き出しておくと、自分に都合のよいエビデンスばかり探すのを防げます。'),T('你可以改变主意。工程师的价值是让结论随证据变得更准确。','考えを変えてもかまいません。エンジニアの価値は、エビデンスに合わせて結論をより正確にしていくことにあります。'),T('别把相关性直接写成根因。用一个能区分候选原因的实验来收尾。','相関をそのまま根本原因と書かないでください。原因候補を切り分けられる実験で締めくくりましょう。')],tool:[T('设备设定值和实际反馈要一起看。无报警，不等于所有工艺条件都稳定。','装置の設定値と実測値は必ずセットで見てください。アラームなしは、すべてのプロセス条件が安定しているという意味ではありません。'),T('同一现象在几台机台上出现？先做机台间差异比较，别一上来就换全部耗材。','同じ現象は何台の号機で出ていますか？まず号機間差を比較しましょう。いきなり消耗品を全部交換するのはやめてください。'),T('临时恢复与根因验证可以是两件事。换了东西变好，还要解释究竟哪个变量起作用。','暫定復旧と根本原因の検証は別の話です。何かを交換して良くなっても、結局どの変数が効いたのかを説明する必要があります。')],metrology:[T('先确认单位、测点、样本和量测方法一致。看起来精确的数据，也可能不可比。','まず単位、測定点、サンプル、測定方法がそろっているか確認してください。精密に見えるデータでも、比較できないことがあります。'),T('重复性好，不代表绝对准确。必要时找独立参考或交叉量测。','繰り返し性が良くても、絶対値が正確とは限りません。必要に応じて、独立した基準やクロス測定で確認してください。'),T('看均值的时候，也别忘了分布、位置和样本量。没有观察到，不等于不存在。','平均値を見るときは、分布、位置、サンプル数も忘れないでください。観察されなかったことは、存在しないことと同じではありません。')]};
const routineQuestions=[
 [T('接班时看到“配方未变、无报警”，你先确认什么？','引き継ぎ時に「レシピ変更なし・アラームなし」と聞きました。まず何を確認しますか？'),[T('只看设定页面即可','設定画面だけ見ればよい'),T('核对产品与配方，再看实际压力、流量及量测版本','製品とレシピを照合し、実際の研磨圧力・スラリー流量と測定レシピの版も確認する'),T('马上把时间缩短 9%','すぐに研磨時間を 9% 短縮する')],1,T('设定记录、实际反馈与量测条件都应纳入检查。','設定の記録、実測値、測定条件のすべてを確認対象に含めるべきです。')],
 [T('最终检查发现颗粒增加，巡检记录应该保留什么？','最終検査でパーティクルの増加が見つかりました。点検記録には何を残すべきですか？'),[T('只有最终颗粒总数','最終的なパーティクル総数だけ'),T('只保留异常班别','異常があったシフトの分だけ'),T('缺陷类型、位置、加工路线和各步骤时间','欠陥の種類、位置、加工ルート、各工程の時刻')],2,T('完整路线和时间能帮助定位缺陷形成步骤。','ルートと時刻がすべて残っていれば、欠陥が発生した工程の特定に役立ちます。')],
 [T('两种产品使用不同配方，你如何看 RR 日报？','2 つの製品は異なるレシピを使っています。RR の日報をどう見ますか？'),[T('先按产品和配方分组，再看总体','まず製品とレシピごとに層別し、その後で全体を見る'),T('把两种产品合并成一个控制图','2 つの製品を 1 枚の管理図にまとめる'),T('直接按最高 RR 调整全部产品','最も高い RR に合わせて全製品を調整する')],0,T('只有可比群体，才能支持产品内工艺变化的判断。','比較可能な群どうしでなければ、製品内のプロセス変化は判断できません。')],
 [T('控制界限与产品规格有什么区别？','管理限界と製品規格の違いは何ですか？'),[T('完全相同','まったく同じ'),T('控制界限看过程变化，规格看产品要求','管理限界は工程の変化を見るもの、規格は製品への要求を見るもの'),T('只要产品合格就不用控制图','製品が合格なら管理図は不要')],1,T('预先定义的控制图规则提供过程变化信号。','あらかじめ定めた管理図のルールが、工程変化のシグナルを示します。')],
 [T('今天要验证未知的参数组合，先做什么？','今日は未知のパラメータの組み合わせを検証します。まず何をしますか？'),[T('直接拿量产批次尝试','量産ロットでそのまま試す'),T('同时改所有可疑变量','疑わしい変数をすべて同時に変える'),T('在批准的工程试验范围内确定因素、重复和顺序','承認された評価実験の範囲内で、因子・繰り返し・順序を決める')],2,T('先明确验证设计与适用边界，再运行试验。','まず検証の設計と適用範囲を明確にしてから、実験を行います。')],
 [T('记录修整器寿命，应该保留什么？','コンディショナーの寿命を記録するとき、何を残すべきですか？'),[T('累计负荷、品质趋势、维护时间和是否已漂移','累積負荷、品質の傾向、メンテナンス時刻、ドリフトの有無'),T('只保留已经坏掉的耗材','壊れた消耗品の記録だけ'),T('只写全厂平均片数','工場全体の平均枚数だけ')],0,T('没有失效的记录也提供寿命下界信息。','故障していない記録も、寿命の下限に関する情報になります。')]
];
const studyQuestions=[
 [T('Bias（系统性偏差）指什么？','Bias（かたより・系統誤差）とは何ですか？'),[T('每次测量都有固定方向的偏移','測定のたびに一定方向のずれが生じること'),T('测量次数不足','測定回数が足りないこと'),T('晶圆一定被多磨了','ウェーハが必ず研磨されすぎていること')],0],
 [T('Queue Time 指什么？','Queue Time とは何ですか？'),[T('研磨液浓度','スラリー濃度'),T('工程步骤之间的等待时间','工程と工程の間の待ち時間'),T('晶圆半径','ウェーハの半径')],1],
 [T('Product Mix 指什么？','Product Mix とは何ですか？'),[T('产品构成和比例','製品の構成と比率'),T('研磨液混合温度','スラリーの混合温度'),T('缺陷位置','欠陥の位置')],0],
 [T('SPC 的主要用途是什么？','SPC の主な用途は何ですか？'),[T('自动修改规格','規格を自動で変更する'),T('证明所有产品都合格','すべての製品が合格だと証明する'),T('监测过程变化并触发调查','工程の変化を監視し、調査のきっかけにする')],2],
 [T('交互作用意味着什么？','交互作用とは何を意味しますか？'),[T('两个因素必须互不影响','2 つの因子が互いに影響しないこと'),T('一个因素的影响取决于另一个因素的水平','ある因子の効果が、別の因子の水準によって変わること'),T('两个参数都在规格外','2 つのパラメータがどちらも規格外であること')],1],
 [T('右删失的样本意味着什么？','右側打ち切りのサンプルとは何を意味しますか？'),[T('在最后观察时已经失效','最後の観察時点ですでに故障している'),T('只知道寿命超过最后观察时间','寿命が最後の観察時点より長いことだけが分かる'),T('数据完全没有价值','データにまったく価値がない')],1]
];
function save(){try{localStorage.setItem(KEY,JSON.stringify(game))}catch(e){saveWorks=false}if($('saveNote'))$('saveNote').textContent=saveWorks?T('进度自动保存在当前浏览器。','進行状況はこのブラウザに自動保存されます。'):T('当前浏览器无法保存；离开页面会丢失本次进度。','このブラウザでは保存できません。ページを離れると、今回の進行状況は失われます。')}
function toast(s){clearTimeout(toastTimer);(h=>{if($('toast').parentNode!==h)h.appendChild($('toast'))})(document.querySelector('dialog[open]')||document.body);$('toast').textContent=s;$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,4200)}
function objectives(){const s=shift();return [
 {label:T('参加晨会','朝会に参加'),done:s.briefed,to:'lead'},
 {label:T('完成机台巡检','装置点検を完了'),done:s.routine,to:'tool'},
 {label:T(`收集证据 ${s.opened.length}/4`,`エビデンス収集 ${s.opened.length}/4`),done:s.opened.length>=2,to:nextEvidenceStation()},
 {label:T('设计验证实验','検証実験を設計'),done:s.valid,to:'lab'},
 {label:T('写结案报告','最終報告を作成'),done:s.report,to:'desk'},
 {label:T('交班 · 打卡下班','引き継ぎ · 退勤'),done:s.clocked,to:'exit'}]}
function nextEvidenceStation(){const i=caseNow().required.find(i=>!shift().opened.includes(i));return E.sources[E.caseIndex(game)][i===undefined?0:i]}
function nextTask(){const tasks=objectives();return tasks.find(t=>!t.done)||tasks.at(-1)}
function hud(){const s=shift(),c=caseNow();$('week').textContent=T(`研修第 ${Math.floor((game.day-1)/6)+1} 周${game.day>6?' · 复训':''}`,`研修 第 ${Math.floor((game.day-1)/6)+1} 週${game.day>6?' · 再研修':''}`);$('day').textContent='DAY '+String(game.day).padStart(2,'0');$('clock').textContent=E.time(game);$('period').textContent=s.minute>=1050?T('加班中','残業中'):s.minute>=780?T('午后','午後'):T('早班','午前');$('energyText').textContent=s.energy+' / 100';$('energyBar').style.width=s.energy+'%';$('energyBar').style.background=s.energy<25?'#f4b179':'var(--mint)';$('energyMeter').setAttribute('aria-valuenow',s.energy);$('rank').textContent=E.rank(game);$('xp').textContent=game.xp;$('missionTitle').textContent=caseTitle();$('missionBrief').textContent=s.briefed?c.brief:T('今日事件已到达。先去团队区听晨会，明确调查目标。','本日の案件が届いています。まずチームエリアで朝会に参加し、調査目標を確認しましょう。');const tasks=objectives(),next=tasks.findIndex(t=>!t.done);$('tasks').innerHTML=tasks.map((t,i)=>`<button class="task ${t.done?'complete':''} ${i===next?'current':''}" data-go="${t.to}"><span>${t.done?'✓':i+1}</span>${t.label}</button>`).join('');$('nextHint').textContent=s.clocked?T('辛苦了。打开调查手帐查看今日总结，准备下一天。','お疲れさまでした。調査ノートを開いて本日のまとめを確認し、次の日に備えましょう。'):s.energy<15?T('专注力有点低，去右下角休息一下。','集中力が下がっています。右下の休憩コーナーで少し休みましょう。'):s.report?T('报告已交。走到右侧出口，打卡下班。','報告は提出済みです。右側の出口へ行き、退勤しましょう。'):!s.briefed?T('下一步：点击地图左上方「晨会」。','次のステップ：マップ左上の「朝会」をクリックしてください。'):!s.routine?T('下一步：到 CMP 机台完成开工巡检。','次のステップ：CMP装置で始業点検を完了してください。'):s.opened.length<2?T('至少收集两项证据。点击工作站，查看那里能提供什么资料。','エビデンスを 2 件以上集めましょう。ステーションをクリックして、そこで得られる資料を確認してください。'):!s.valid?T('工程实验台已开放。有效验证需要隔离变量，而不是只试着把参数改好。','実験台が使えるようになりました。有効な検証には変数の切り分けが必要です。パラメータを変えて良くなるか試すだけでは不十分です。'):T('证据准备好了。回工位整理判断，也可补充其他调查。','エビデンスがそろいました。自席に戻って判断を整理しましょう。追加の調査もできます。');$('relations').innerHTML=Object.entries(people).map(([id,p])=>`<div class="relation"><span class="initial">${p.initial}</span><b>${p.name}</b><small>${T('默契','信頼度')} ${game.rapport[id]||0}</small></div>`).join('');$('latestLog').textContent=s.log.length?s.log.at(-1).at+'　'+s.log.at(-1).text:T('08:30　来到研修中心，准备参加晨会。','08:30　研修センターに到着。朝会に参加する準備をします。');$('intro').hidden=s.briefed||!briefIntro;const nextId=nextTask().to;$('stations').innerHTML=E.stations.map(st=>`<button class="station ${st.id===nextId?'quest':''}" data-go="${st.id}" style="left:${st.x}%;top:${st.id==='exit'?st.y:st.y+(st.y<50?-2:2)}%" aria-label="${T(`前往${st.name}`,`${st.name}へ移動`)}">${st.id===nextId?'<span class="questdot">!</span>':''}${st.icon} ${st.short}</button>`).join('');updatePosition();save();}
function nearest(){return E.stations.map(s=>({...s,d:Math.hypot((game.position.x-s.x)*1.5,game.position.y-s.y)})).sort((a,b)=>a.d-b.d)[0]}
function updatePosition(){const p=game.position;$('player').style.left=p.x+'%';$('player').style.top=p.y+'%';const n=nearest(),near=n&&n.d<8;$('interact').textContent=near?'E · '+n.short:T('走近工作站','ステーションに近づく');$('interact').disabled=!near;$('place').textContent=near?n.room:T('中央通道','中央通路');document.querySelectorAll('.station').forEach(el=>el.classList.toggle('near',near&&el.dataset.go===n.id));}
function go(id){const st=E.stations.find(s=>s.id===id);if(!st)throw Error(T('未知工作站','不明なステーションです'));if(game.shift.clocked){showNight();return}closeDialog(false);briefIntro=false;$('intro').hidden=true;target={x:st.x,y:st.y,station:id};$('destination').hidden=false;$('destination').style.left=st.x+'%';$('destination').style.top=st.y+'%';$('world').focus({preventScroll:true});}
function closeDialog(focus=true){$('workDialog').close();openPlace=null;keys.clear();if(focus)$('world').focus({preventScroll:true});}
function showDialog(title,area,body,place){keys.clear();target=null;$('destination').hidden=true;$('player').classList.remove('walking');openPlace=place;$('dialogTitle').textContent=title;$('dialogArea').textContent=area;$('dialogBody').innerHTML=body;if(!$('workDialog').open)$('workDialog').showModal();}
function speech(id,text){const p=people[id];return `<div class="speech"><div class="portrait" aria-hidden="true">${p.initial}</div><div><b>${p.name} · ${p.role}</b><p>${text}</p></div></div>`}
function choices(name,items,val,disabled=false){const shiftIndex=(game.day+name.length)%items.length;return '<div class="choices">'+items.map((_,j)=>(j+shiftIndex)%items.length).map(i=>`<label class="choice"><input type="radio" name="${name}" value="${i}" ${val===i?'checked':''} ${disabled?'disabled':''}><span>${items[i]}</span></label>`).join('')+'</div>'}
function table(e){return `<div class="tableWrap"><table><thead><tr>${e.head.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${e.rows.map(r=>`<tr>${r.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="small">${e.note}</p>`}
function caseChart(){const c=caseNow(),y=v=>122-(v-c.range[0])/(c.range[1]-c.range[0])*96,x=i=>35+i*70;return `<div class="caseMetric"><span>${c.metric[0]}</span><strong>${c.metric[1]}</strong><span>${c.metric[2]}</span></div><svg class="trend" viewBox="0 0 560 160" role="img" aria-label="${T('趋势数据','トレンドデータ')} ${c.trend.join('、')} ${c.unit}"><line x1="35" x2="535" y1="${y(c.baseline)}" y2="${y(c.baseline)}" stroke="#83a3a7" stroke-dasharray="4 4"/><text x="3" y="${y(c.baseline)-4}" fill="#bdd0d1" font-size="12">${c.baseline}</text><polyline points="${c.trend.map((v,i)=>`${x(i)},${y(v)}`).join(' ')}" stroke="#82dfc5" stroke-width="2.5" fill="none"/>${c.trend.map((v,i)=>`<circle cx="${x(i)}" cy="${y(v)}" r="3" fill="#ffe0a0"/><text x="${x(i)}" y="${y(v)-12}" fill="#f2edcf" font-size="12" text-anchor="middle">${v}</text><text x="${x(i)}" y="150" fill="#aec4c9" font-size="12" text-anchor="middle">${E.caseIndex(game)===5?(i+1)*200:i+1}</text>`).join('')}</svg><p class="small">${c.scope} ${T('横轴：','横軸：')}${E.caseIndex(game)===5?T('累计修整时间（min）','累積コンディショニング時間（min）'):T('批次序号','ロット順')}。</p>`}
function costButton(action,text,time,energy,disabled=false,extra=''){return `<div class="rowActions"><button class="primary" data-do="${action}" ${disabled?'disabled':''} ${extra}>${text}</button><span class="cost">${time} min · ${T('专注力','集中力')} −${energy}</span></div>`}
function evidenceList(){const c=caseNow(),s=shift(),src=E.sources[E.caseIndex(game)];return `<h3>${T('证据清单','エビデンス一覧')} · ${s.opened.length} / ${c.evidence.length}</h3><div class="tableWrap"><table><thead><tr><th>${T('编号','番号')}</th><th>${T('资料','資料')}</th><th>${T('在哪里取得','取得場所')}</th><th>${T('状态','状態')}</th></tr></thead><tbody>${c.evidence.map((e,i)=>{const st=E.stations.find(x=>x.id===src[i]);return `<tr><td>E${i+1}</td><td>${e.name}</td><td>${st.icon} ${st.name}</td><td>${s.opened.includes(i)?T('✓ 已收集','✓ 取得済み'):s.report?T('未取得','未取得'):`<button data-go="${st.id}">${T('前往','移動')}</button>`}</td></tr>`}).join('')}</tbody></table></div><p class="small">${T('资料分散在不同的工作站，要走过去申请。每项都消耗时间和专注力；先想清楚要回答什么问题，再决定查哪一项。「什么时候变的、变了什么」通常是最该先查的。','資料は各ステーションに分かれており、その場で申請します。どれも時間と集中力を消費するので、何を確かめたいのかを決めてから取得しましょう。「いつ、何が変わったか」は、たいてい最初に確認すべき項目です。')}</p>`}
function evidenceAt(id){const c=caseNow(),s=shift(),arr=c.evidence.map((e,i)=>({e,i})).filter(x=>E.sources[E.caseIndex(game)][x.i]===id);if(!arr.length)return '';return '<h3>'+T('这里可以取得的资料','ここで入手できる資料')+'</h3>'+arr.map(({e,i})=>`<section class="section"><div class="evidenceHead"><h3>E${i+1} · ${e.name}</h3><span>${s.opened.includes(i)?T('已收集','取得済み'):T('未解锁','未取得')}</span></div>${s.opened.includes(i)?table(e):`<p class="small">${T(`向${id==='desk'?T('数据系统','データシステム'):T('该工作站','このステーション')}申请这组资料，比较异常与正常条件。`,`${id==='desk'?T('数据系统','データシステム'):T('该工作站','このステーション')}にこの資料を申請し、異常時と正常時の条件を比較します。`)}</p>${costButton('evidence',T('获取资料','資料を取得'),e.cost,7,!s.routine||s.report,`data-eid="${i}"`)}${!s.routine?'<p class="locked">'+T('完成晨会和机台巡检后开放。','朝会と装置点検の完了後に利用できます。')+'</p>':''}`}</section>`).join('')}
function talkBlock(id){if(!people[id]||!shift().briefed)return '';const n=game.rapport[id]||0,done=shift().talked.includes(id);return `<section class="section"><h3>${T(`和${people[id].name}聊聊`,`${people[id].name}と話す`)}</h3><p class="small">${T('每天一次交流增加默契；不直接透露案例答案。','1 日 1 回の会話で信頼度が上がります。ケースの答えを直接教えてもらえるわけではありません。')}</p>${done?`<p>${talkHints[id][(n-1)%3]}</p><span class="small">${T('今日已交流 · 默契','本日は会話済み · 信頼度')} ${n}</span>`:costButton('talk',T('请教一个工作建议','仕事のアドバイスをもらう'),10,2,shift().report,`data-person="${id}"`)}</section>`}
function notebookFields(){const c=caseNow(),s=shift();return `<h3>${T('当前优先假设','現在の最有力仮説')}</h3><p class="small">${T('新证据出现后可以修改。改变想法不扣分，证据链才重要。','新しいエビデンスが出たら変更できます。考えを変えても減点されません。大切なのはエビデンスのつながりです。')}</p>${choices('hyp',c.hypotheses,s.hyp,s.report)}<label for="rpgNotes"><h3>${T('我的推理笔记','推論メモ')}</h3></label><textarea id="rpgNotes" ${s.report?'readonly':''} placeholder="${T('我看到了什么？什么证据支持或反对我的假设？下一步如何验证？','何を観察しましたか？どのエビデンスが仮説を支持、または否定していますか？次にどう検証しますか？')}">${esc(s.notes)}</textarea><p class="small">${T('自由笔记供复盘，不参与自动评分。','自由メモは振り返り用で、自動採点の対象にはなりません。')}</p>`}
/* 案例标题会暗示原因，结案前只显示“Day N 的案例”。 */
function caseTitle(){return shift().report?caseNow().title:T(`Day ${game.day} 的案例`,`Day ${game.day} の案件`)}
function stationBody(id){const c=caseNow(),s=shift(),ix=E.caseIndex(game);if(id==='lead'){return speech('lead',morning[ix])+(!s.briefed?`<h3>${T('今日事件','本日の案件')} · ${caseTitle()}</h3><p>${c.brief}</p>${caseChart()}<h3>${T('你如何定义今天的问题？','今日の問題をどう定義しますか？')}</h3>${choices('problem',c.problem,s.problem)}<h3>${T('先提出一个暂定假设','まず暫定仮説を立てましょう')}</h3>${choices('hyp',c.hypotheses,s.hyp)}${costButton('brief',T('确认任务，开始工作','任務を確認して仕事を始める'),15,4)}<p class="small">${T('先保留你的判断。后面可以修改假设；现在不会公布答案。','この判断はいったん保存されます。仮説は後から変更できます。答えはまだ公開されません。')}</p>`:`<div class="notice good">${T('晨会已完成。今日目标：','朝会は完了しました。本日の目標：')}${c.problem[s.problem]}</div>${evidenceAt(id)}${talkBlock(id)}<button data-go="tool">${T('去设备区 →','装置エリアへ →')}</button>`)}
if(id==='tool'){const q=routineQuestions[ix];return speech('tool',T('设备交给你看数据，我来配合现场确认。今天我们先把基础巡检做好。','装置のデータはあなたに見てもらい、現場での確認は私がサポートします。今日はまず基本の点検をしっかり行いましょう。'))+(!s.routine?`<section class="section"><h3>${T('每日开工巡检','毎日の始業点検')}</h3><p>${q[0]}</p>${q[1].map((text,i)=>`<div class="rowActions"><button data-do="routine" data-choice="${i}" ${!s.briefed?'disabled':''}>${text}</button></div>`).join('')}<p class="small">${T('正确完成：15 min · 专注力 −6。错误尝试：5 min · −2，可重新判断。','正解：15 min · 集中力 −6。不正解：5 min · −2、やり直せます。')}</p>${!s.briefed?'<div class="notice">'+T('先参加晨会，再来接手巡检。','まず朝会に参加してから、点検を引き継いでください。')+'<button data-go="lead">'+T('去晨会','朝会へ')+'</button></div>':''}</section>`:'<div class="notice good">'+T('✓ 今日巡检完成。记录实际条件，未擅自修改机台参数。','✓ 本日の点検が完了しました。実際の条件を記録し、装置パラメータは勝手に変更していません。')+'</div>')+evidenceAt(id)+talkBlock(id)}
if(id==='metrology')return speech('metrology',T('欢迎。先说清楚你希望比较哪些样品、测点和条件；单独一个数值很难解释问题。','ようこそ。まず、どのサンプル・測定点・条件を比較したいのかをはっきりさせてください。数値ひとつだけでは、問題の説明は難しいです。'))+evidenceAt(id)+talkBlock(id);
if(id==='desk')return `<p>${T('你的分析工位。整理已解锁的数据，修正判断，再写一份能够交班的报告。','あなたの分析用の自席です。取得済みのデータを整理して判断を見直し、引き継ぎできる報告書を書きましょう。')}</p>${evidenceList()}${evidenceAt(id)}<details><summary>${T('查看今日原始现象与趋势','本日の初期現象とトレンドを見る')}</summary><p>${c.brief}</p>${caseChart()}</details>${notebookFields()}${s.report?reviewHTML():`<section class="section"><h3>${T('结案报告','最終報告')}</h3><p class="small">${T('需要巡检完成、至少两项证据和一次实验尝试。没有有效验证也能交报告，但会在专业评分中体现。','点検の完了、2 件以上のエビデンス、1 回の実験実施が必要です。有効な検証がなくても報告は提出できますが、専門スコアに反映されます。')}</p><h3>${T('纠正措施','是正処置')}</h3>${choices('fix',c.fixes,s.fix)}<h3>${T('防止再次发生','再発防止')}</h3>${choices('pm',c.prevent,s.pm)}<div class="notice" id="submitCheck">${submitCheck()}</div>${costButton('submit',T('提交报告 · 查看复盘','報告を提出 · 振り返りを見る'),20,8)}<p class="small">${T('提交后锁定今天的判断，不会因重复点击再次获得经验。','提出すると本日の判断は確定します。繰り返しクリックしても経験値(XP)は再度もらえません。')}</p></section>`}`;
if(id==='lab')return `<div class="notice">${T('工程实验台使用教学试片。先收集至少两项证据，再选择能区分假设的实验。','実験台では教育用ウェーハを使います。まずエビデンスを 2 件以上集めてから、仮説を切り分けられる検証実験を選んでください。')}</div>${evidenceAt(id)}<h3>${T('设计你的验证','検証を設計する')}</h3>${c.tests.map((_,j)=>(j+game.day)%3).map(i=>`<section class="section"><h3>${c.tests[i].name}</h3>${s.tests.includes(i)?`<div class="notice ${c.tests[i].good?'good':''}">${c.tests[i].result}</div>`:costButton('test',T('申请并执行试验','実験を申請して実施'),25,12,s.opened.length<2||s.valid||s.report,`data-tid="${i}"`)}</section>`).join('')}${hypVerdict()}${s.valid?'<button class="primary" data-go="desk">'+T('带着结果回工位 →','結果を持って自席へ戻る →')+'</button>':''}`;
if(id==='break')return `<div class="speech"><div class="portrait">☕</div><div><b>${T('休息时间，也属于工作的一部分','休憩も仕事のうちです')}</b><p>${T('把视线从数据上移开一会儿。恢复专注后，再检查自己的假设。','しばらくデータから目を離しましょう。集中力が戻ったら、もう一度自分の仮説を確かめてください。')}</p></div></div><p>${T('当前专注力：','現在の集中力：')}<strong>${s.energy} / 100</strong></p><div class="rowActions"><button class="primary" data-do="rest" ${s.report||s.energy===100?'disabled':''}>${T('休息 20 分钟 · 恢复 35','20 分休憩 · 35 回復')}</button></div><p class="small">${T('可以多次休息，不会卡住关卡。时钟只随工作行动推进，移动和阅读不消耗时间。','休憩は何度でもでき、進行不能になることはありません。時計は作業アクションでのみ進み、移動や閲覧では時間を消費しません。')}</p><p class="safetyNote">${T('地图把休息区和工作区放在同一画面仅为游戏简化。实际厂区应遵守洁净区隔离、更衣和饮食规定。','休憩エリアと作業エリアを同じ画面に置いているのは、ゲーム上の簡略化です。実際の工場では、クリーンルームの区画分け、更衣、飲食に関するルールを守ってください。')}</p>`;
if(id==='exit')return s.report?`<h3>${T('今天的报告已经交好了。','本日の報告は提出済みです。')}</h3><p>${T('打卡后结算当天成长，晚上还可以温习一个术语。','退勤すると本日の成長が集計されます。夜には用語をひとつ復習できます。')}</p><button class="primary" data-do="clockout">${T('打卡下班 →','退勤する →')}</button>`:`<h3>${T('先把今天的工作交接好','まず本日の仕事を引き継ぎましょう')}</h3><p>${T('你还没有提交结案报告。回工位补上证据、实验和处理建议，再下班。','最終報告がまだ提出されていません。自席に戻ってエビデンス、実験、処置の提案をそろえてから退勤しましょう。')}</p><button data-go="desk">${T('返回我的工位','自席に戻る')}</button>`;return '';}
function openStation(id){const st=E.stations.find(s=>s.id===id);if(!st)return;if(Math.hypot((game.position.x-st.x)*1.5,game.position.y-st.y)>=8){go(id);return}showDialog(st.name,st.room+' / '+E.time(game),stationBody(id),id)}
/* 提交前确认：计分用的是此刻选中的判断。不透露答案，只提醒“晨会的暂定假设还没复核过”这类容易漏掉的事。 */
/* 有效验证完成后，明确告诉玩家：实验结果支不支持此刻选中的假设。真实实验也会给出这个反馈；不说明哪一个才对。 */
function hypVerdict(){const c=caseNow(),s=shift();if(!s.valid||s.hyp===null)return '';const name='「'+c.hypotheses[s.hyp]+'」';return s.hyp===c.answer?`<div class="notice good">✓ ${T(`实验结果支持你当前的优先假设${name}。`,`実験結果は、現在の最優先仮説${name}を支持しています。`)}</div>`:`<div class="notice">⚠ ${T(`实验结果不支持你当前的优先假设${name}。如果它是真的，这次验证不会得到这样的结果。回工位重读证据，在「当前优先假设」里重新选择——改变想法不扣分。`,`実験結果は、現在の最優先仮説${name}を支持していません。この仮説が正しければ、今回の検証でこのような結果にはなりません。自席でエビデンスを読み直し、「現在の最優先仮説」で選び直してください。考えを変えても減点されません。`)}</div>`}
function submitCheck(){const c=caseNow(),s=shift(),q=(list,i)=>i===null?T('未选择','未選択'):'「'+list[i]+'」',stale=s.hyp!==null&&s.hyp===s.initialHyp&&(s.opened.length>0||s.tests.length>0);return `<b>${T('提交前确认','提出前の確認')}</b><br>${T('问题定义：','問題定義：')}${q(c.problem,s.problem)}<br>${T('最终假设：','最終仮説：')}${q(c.hypotheses,s.hyp)}${stale?'<br>⚠ '+T('这仍是晨会时选的暂定假设，之后没有改过。计分只看提交时选中的这一项（占 30 分）；请对照已取得的证据和实验结果，在上方「当前优先假设」里确认或修改。','これは朝会で選んだ暫定仮説のままで、その後変更されていません。採点は提出時に選ばれている仮説だけを見ます（30 点分）。取得したエビデンスと実験結果に照らして、上の「現在の最優先仮説」で確認・修正してください。'):''}${hypVerdict()}${T('有效验证：','有効な検証：')}${s.valid?T('已完成','完了'):T('尚未完成（验证设计与根因证据共 30 分）','未完了（検証設計と根本原因のエビデンスで計 30 点）')}`}
/* 复盘里逐项说明失分原因：选了什么、参考是什么、缺了哪项证据。只在结案后显示。 */
function lossReasons(){const c=caseNow(),s=shift(),q=(list,i)=>i===null?T('未选择','未選択'):'「'+list[i]+'」',ev=i=>'E'+(i+1)+'「'+c.evidence[i].name+'」'+T('（在「','（「')+E.stations.find(x=>x.id===E.sources[E.caseIndex(game)][i]).name+T('」取得）','」で取得）'),change=[0,1,2,3,1,1][E.caseIndex(game)],missing=c.required.filter(i=>!s.opened.includes(i)),bad=s.tests.filter(i=>!c.tests[i].good).length,hypOk=s.hyp===c.answer;
return [T(`你选的是${q(c.problem,s.problem)}；参考是${q(c.problem,0)}。`,`あなたの選択は${q(c.problem,s.problem)}、参考は${q(c.problem,0)}です。`),
T(`没有查看 ${ev(change)}，它记录了本关“什么变了”。`,`${ev(change)} を確認していません。今回「何が変わったか」の記録です。`),
T(`关键证据缺 ${missing.map(ev).join('、')}。`,`重要なエビデンス ${missing.map(ev).join('、')} が不足しています。`),
T(`你提交时选中的假设是${q(c.hypotheses,s.hyp)}，参考结论是${q(c.hypotheses,c.answer)}。`,`提出時に選ばれていた仮説は${q(c.hypotheses,s.hyp)}、参考の結論は${q(c.hypotheses,c.answer)}です。`)+(s.hyp===s.initialHyp?T('这是晨会时选的暂定假设，之后没有在工位的「当前优先假设」里改过——改变想法不扣分，但计分只看提交时选中的那一项。','これは朝会で選んだ暫定仮説のままで、自席の「現在の最優先仮説」で変更されていません。考えを変えても減点されませんが、採点は提出時の選択だけを見ます。'):'')+' '+T(`与它矛盾的证据：${c.required.map(i=>ev(i)+'——'+c.evidence[i].note).join(' ')}`,`これと矛盾するエビデンス：${c.required.map(i=>ev(i)+'——'+c.evidence[i].note).join(' ')}`),
s.valid?T(`有效验证已完成，但之前做过 ${bad} 次无法隔离因素的实验，每次扣 3 分。`,`有効な検証は完了しましたが、その前に因子を切り分けられない実験を ${bad} 回行い、1 回につき 3 点減点されました。`):T('没有完成有效验证：做过的实验都不能隔离候选因素。','有効な検証が完了していません。実施した実験はいずれも候補因子を切り分けられませんでした。'),
T('这一项要同时满足三个条件：','この項目は 3 つの条件を同時に満たす必要があります：')+[[T('关键证据齐全','重要なエビデンスがそろっている'),!missing.length],[T('完成有效验证','有効な検証が完了'),s.valid],[T('最终假设与参考结论一致','最終仮説が参考の結論と一致'),hypOk]].map(([t,ok])=>(ok?'✓ ':'✗ ')+t).join('　')+(hypOk?'':T('。所以假设选错会同时丢掉「假设质量」和这一项，共 30 分。','。そのため、仮説を誤ると「仮説の質」とこの項目の計 30 点を同時に失います。')),
T(`你选的是${q(c.fixes,s.fix)}；参考是${q(c.fixes,c.fix)}。`,`あなたの選択は${q(c.fixes,s.fix)}、参考は${q(c.fixes,c.fix)}です。`),
T(`你选的是${q(c.prevent,s.pm)}；参考是${q(c.prevent,c.pm)}。`,`あなたの選択は${q(c.prevent,s.pm)}、参考は${q(c.prevent,c.pm)}です。`)]}
/* 8D 报告练习：结案后按 D1–D8 自己写一遍，再对照参考填法。内容只存在本机浏览器；可导出成文本文件。
   refs 是长度为 8 的参考填法（HTML 字符串），由各模式按本关数据生成。 */
const D8_KEY='cmp-fab-8d-v1';
const d8Steps=()=>[
 [T('D1 组建团队','D1 チーム編成'),T('谁负责、谁参与？这个问题需要哪几个部门的视角？','誰が担当し、誰が参加するか。この問題にはどの部門の視点が必要か。')],
 [T('D2 描述问题','D2 問題の記述'),T('只写事实，不写推测：什么现象、哪台设备、从哪一批开始、幅度多大、影响多少。注意区分“读数变了”和“晶圆变了”。','事実だけを書き、推測は書かない：どんな現象か、どの装置か、どのロットからか、どの程度か、影響範囲は。「読み値が変わった」と「ウェーハが変わった」を区別する。')],
 [T('D3 临时对策','D3 暫定処置'),T('原因查清之前，先做什么防止损失扩大？必须能撤回、不引入新风险。','原因が分かる前に、被害の拡大を防ぐために何をするか。元に戻せて、新しいリスクを持ち込まないこと。')],
 [T('D4 查明根本原因','D4 根本原因の究明'),T('列出假设；每个假设“如果成立应该看到什么、实际看到什么”；用什么实验验证了；再连续问几次“为什么”，问到流程或标准这一层。','仮説を挙げ、それぞれ「成り立つなら何が見えるはずか、実際に何が見えたか」を書く。どの実験で検証したか。さらに「なぜ」を繰り返し、手順や標準の層まで掘り下げる。')],
 [T('D5 永久对策','D5 恒久対策'),T('针对 D4 的每个根本原因各写一条对策。','D4 の根本原因それぞれに対して、対策を 1 つずつ書く。')],
 [T('D6 实施并验证','D6 実施と効果確認'),T('对策做了之后，用什么数据证明它有效？写数字。','対策の実施後、どのデータで効果を証明するか。数字で書く。')],
 [T('D7 防止再发、横向展开','D7 再発防止・水平展開'),T('同类问题还可能出现在哪里？要更新哪些标准、点检、FMEA？','同種の問題は他にどこで起こり得るか。どの標準、点検、FMEA を更新するか。')],
 [T('D8 总结','D8 まとめ'),T('结论是什么？如果当初按直觉处理会怎样？学到了什么？','結論は何か。直感のまま対応していたらどうなったか。何を学んだか。')]];
function d8Load(){try{return JSON.parse(localStorage.getItem(D8_KEY)||'{}')||{}}catch(e){return {}}}
function d8Save(all){try{localStorage.setItem(D8_KEY,JSON.stringify(all))}catch(e){}}
let d8Refs={};
function eightDHTML(key,title,refs){d8Refs[key]={title,refs};const mine=d8Load()[key]||{},steps=d8Steps(),filled=steps.filter((_,i)=>(mine['d'+(i+1)]||'').trim()).length;return `<section class="section" id="d8-${key}"><h3>${T('8D 报告练习','8D レポート練習')} · ${filled} / 8</h3><p class="small">${T('用 8D 的格式把这一关重新写一遍。先自己写，再展开每一步下面的「参考填法」对照。内容自动保存在本机；不计分。','このケースを 8D の形式で書き直してみましょう。まず自分で書き、その後で各ステップの「参考記入例」を開いて比べます。内容はこの端末に自動保存され、採点はされません。')}</p>${steps.map(([name,hint],i)=>`<h3 style="margin-top:18px">${name}</h3><p class="small">${hint}</p><textarea data-d8key="${key}" data-d8i="${i+1}" style="min-height:84px" placeholder="${T('在这里写……','ここに記入……')}">${esc(mine['d'+(i+1)]||'')}</textarea><details><summary>${T('参考填法','参考記入例')}</summary><div class="small">${refs[i]}</div></details>`).join('')}<div class="rowActions" style="margin-top:16px"><button data-d8export="${key}">${T('导出我的 8D（文本文件）','自分の 8D を書き出す（テキスト）')}</button><button data-d8export="${key}" data-withref="1">${T('导出：我的 8D + 参考填法','書き出し：自分の 8D ＋ 参考記入例')}</button></div></section>`}
document.addEventListener('input',e=>{const k=e.target.dataset?.d8key;if(!k)return;const all=d8Load();(all[k]??={})['d'+e.target.dataset.d8i]=e.target.value;all[k].updated=new Date().toISOString();d8Save(all)});
document.addEventListener('click',e=>{const b=e.target.closest('[data-d8export]');if(!b)return;const key=b.dataset.d8export,info=d8Refs[key];if(!info)return;const mine=d8Load()[key]||{},strip=h=>{const d=document.createElement('div');d.innerHTML=h.replace(/<br\s*\/?>/g,'\n').replace(/<\/(p|li|tr)>/g,'\n');return d.textContent.replace(/\n{3,}/g,'\n\n').trim()},lines=['8D Report · '+info.title,T('（教学模拟案例，非实际工作数据）','（学習用シミュレーションの事例。実務データではありません）'),''];d8Steps().forEach(([name],i)=>{lines.push('■ '+name,(mine['d'+(i+1)]||'').trim()||T('（未填写）','（未記入）'));if(b.dataset.withref)lines.push('',T('〔参考填法〕','〔参考記入例〕'),strip(info.refs[i]));lines.push('')});const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+lines.join('\n').replace(/\r?\n/g,'\r\n')],{type:'text/plain;charset=utf-8'}));a.download='8D_'+info.title.replace(/[\\/:*?"<>|\s]+/g,'_')+'.txt';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),2000);toast(T('已导出。','書き出しました。'))});
/* 剧情模式：参考填法由本关数据自动生成 */
function caseD8Refs(c){const li=a=>'<ul>'+a.map(x=>'<li>'+x+'</li>').join('')+'</ul>',good=c.tests.find(t=>t.good),bad=c.tests.filter(t=>!t.good),wrongFix=c.fixes.filter((_,i)=>i!==c.fix);return [
 li([T('工艺（负责人）：我','プロセス（担当）：自分'),T('设备：小野','装置：小野さん'),T('量测：陈工','測定：陳さん'),T('指导：林前辈','指導：林先輩')])+T('同一个现象可能来自工艺、设备或量测。只有一方参与，调查范围就会局限在那一方。','同じ現象でも、原因はプロセス・装置・測定のいずれにもあり得ます。一部門だけでは、調査範囲がその部門に偏ります。'),
 '<p>'+c.brief+'</p>'+li([c.metric[0]+'：'+c.metric[1]+'（'+c.metric[2]+'）',T('最近各批：','直近の推移：')+c.trend.join(' → ')+' '+c.unit,c.scope,T('要确认的事：','確認すべきこと：')+c.problem[0]]),
 li([T('扣留受影响的批次：暂不放行，也不报废。','影響を受けたロットをホールド：リリースも廃棄もしない。'),T('原因确认之前不改配方、不换耗材。','原因が確認できるまで、レシピ変更や消耗品交換はしない。')])+T('这一关里不该做的：','このケースでやってはいけないこと：')+li(wrongFix),
 '<p><b>'+T('关键证据','決め手のエビデンス')+'</b></p>'+li(c.required.map(i=>'E'+(i+1)+' '+c.evidence[i].name+'：'+c.evidence[i].note))+'<p><b>'+T('假设','仮説')+'</b></p>'+li(c.hypotheses.map((h,i)=>(i===c.answer?'✓ ':'✗ ')+h))+'<p><b>'+T('有效的验证','有効な検証')+'</b>：'+good.name+'<br>'+good.result+'</p><p><b>'+T('不能用的验证','使えない検証')+'</b></p>'+li(bad.map(t=>t.name+'：'+t.result))+T('然后继续问“为什么”：为什么这个原因会发生？为什么没有被提前发现？问到流程、标准或监控这一层。','さらに「なぜ」を続けます：なぜその原因が起きたのか。なぜ事前に見つけられなかったのか。手順・標準・監視の層まで掘り下げます。'),
 li([T('纠正：','是正：')+c.fixes[c.fix],T('预防：','予防：')+c.prevent[c.pm]]),
 '<p>'+good.result+'</p>'+T('再加上：对策实施后连续观察若干批，确认读数回到正常范围、控制图无报警。要写具体数字，不写“效果良好”。','加えて：対策後に数ロット連続で観察し、読み値が正常範囲に戻り、管理図にアラームが出ないことを確認します。「効果良好」ではなく具体的な数字で書きます。'),
 li([c.prevent[c.pm],T('横向展开：其他机台、其他量测设备、其他产品有没有同样的风险？','水平展開：他の号機、他の測定機、他の製品に同じリスクはないか。'),T('更新 FMEA：把这次的失效模式补进去，重新评估发生度和检出度。','FMEA の更新：今回の故障モードを追加し、発生度と検出度を再評価する。'),T('更新异常处置流程（OCAP）：下次出现同样的现象，先查什么。','異常時対応フロー（OCAP）の更新：次に同じ現象が出たとき、まず何を確認するか。')]),
 '<p>'+c.lesson+'</p><p lang="ja">'+c.jp+'</p>'];}
function refreshStation(){if(openPlace&&E.stations.some(s=>s.id===openPlace))showDialog(E.stations.find(s=>s.id===openPlace).name,E.stations.find(s=>s.id===openPlace).room+' / '+E.time(game),stationBody(openPlace),openPlace)}
function reviewHTML(){const c=caseNow(),s=shift(),rows=E.score(game,c),total=rows.reduce((n,r)=>n+r[1],0);const weaknesses=[T('把需要确认的现象和原因分开，不要先下结论。','確認すべき現象と原因を分けて考え、先に結論を出さないようにしましょう。'),T('补查本关变化记录或关键分层资料。','このケースの変更履歴、または重要な層別データを追加で確認しましょう。'),T('还缺关键对照资料，先补齐证据。','重要な比較データが不足しています。まずエビデンスをそろえましょう。'),T('最终假设与案例证据不一致，回头检查反例。','最終仮説がケースのエビデンスと一致していません。反例を見直しましょう。'),T('设计能隔离候选因素的实验，避免同时改变多个条件。','原因候補を切り分けられる実験を設計し、複数の条件を同時に変えないようにしましょう。'),T('关键对照、有效验证和一致结论三者缺一不可。','重要な比較データ、有効な検証、一貫した結論の 3 つがすべて必要です。'),T('处理措施要对应已经证实的问题，并包含受影响产品的评估。','処置は実証された問題に対応させ、影響を受けた製品の評価も含めましょう。'),T('把经验变成监控、验收和维护规则。','得られた知見を、監視・受入・メンテナンスのルールに落とし込みましょう。')];return `<section class="section"><div class="scoreHero"><img src="assets/junior-engineer.png" alt="${T('工程师','エンジニア')}"><div><strong>${total}<small style="font-size:16px"> / 100</small></strong><p>+${s.xpAward} XP · ${E.rank(game)}</p></div></div><p class="small">${T('经验＝专业得分 + 巡检 10 + 每位同事交流 2。自由笔记不计分；专业分数不受默契值影响。','経験値(XP)＝専門スコア + 点検 10 + 同僚との会話 1 人につき 2。自由メモは採点されません。専門スコアは信頼度の影響を受けません。')}</p><div class="scoreGrid">${rows.map(r=>`<div class="scoreRow">${r[0]}<b>${r[1]} / ${r[2]}</b><div class="meter"><i style="width:${r[1]/r[2]*100}%"></i></div></div>`).join('')}</div><h3>${T('前辈的复盘','先輩の振り返り')}</h3><p>${c.lesson}</p>${rows.some(r=>r[1]<r[2])?`<h3>${T('失分原因','減点の理由')}</h3>`:''}${(reasons=>rows.map((r,i)=>r[1]<r[2]?`<p class="small"><b>${r[0]}（${r[1]} / ${r[2]}）：</b>${esc(reasons[i])} <i>${weaknesses[i]}</i></p>`:'').join(''))(lossReasons())}<details><summary>${T('展开参考结论与处理建议','参考の結論と処置案を表示')}</summary><p>${T('结论：','結論：')}${c.hypotheses[c.answer]}。</p><p>${T('纠正：','是正：')}${c.fixes[c.fix]}。</p><p>${T('预防：','予防：')}${c.prevent[c.pm]}。</p></details><h3>${T('面试时可以这样说','面接ではこう言えます')}</h3><p class="jp" lang="ja">${c.jp}</p><p class="small">${c.terms}</p>${eightDHTML('case-'+E.caseIndex(game),c.title,caseD8Refs(c))}${!s.clocked?'<button class="primary" data-go="exit">'+T('收好报告，走去下班 →','報告をしまって退勤へ向かう →')+'</button>':''}</section>`}
function showNotebook(tab='evidence'){const c=caseNow(),s=shift();let body=`<div class="bookTabs"><button data-book="evidence">${T('证据与笔记','エビデンスとメモ')}</button><button data-book="log">${T('工作记录','作業記録')}</button><button data-book="growth">${T('成长档案','成長記録')}</button>${s.clocked?'<button data-do="night">'+T('今日总结','本日のまとめ')+'</button>':''}</div>`;if(tab==='evidence')body+=`<h3>${caseTitle()}</h3><p>${c.brief}</p>${caseChart()}${s.briefed?evidenceList():''}${s.opened.length?s.opened.map(i=>`<section class="section"><h3>E${i+1} · ${c.evidence[i].name}</h3>${table(c.evidence[i])}</section>`).join(''):'<p class="notice">'+T('还没有证据。先去晨会，再到各工作站调查。','まだエビデンスがありません。まず朝会に参加し、それから各ステーションで調査しましょう。')+'</p>'}${s.briefed?notebookFields():''}${s.tests.map(i=>`<section class="section"><h3>${T('试验记录','実験記録')}</h3><p>${c.tests[i].result}</p></section>`).join('')}${s.report?reviewHTML():''}`;if(tab==='log')body+=`<h3>${T('今日工作轨迹','本日の作業履歴')}</h3>${s.log.length?s.log.map(l=>`<div class="logEntry"><time>${l.at}</time><span>${esc(l.text)}</span></div>`).join(''):'<p>'+T('还未开始今日工作。','本日の作業はまだ始まっていません。')+'</p>'}`;if(tab==='growth')body+=`<h3>${E.rank(game)} · ${game.xp} XP</h3><p class="small">${T('称号表示游戏研修进度，不是实际职业资质。默契每位同事每天最多增加一次。','称号はゲーム内の研修の進み具合を示すもので、実際の職業資格ではありません。信頼度は同僚 1 人につき 1 日 1 回まで上がります。')}</p><div class="history">${E.levels.map(([name,xp])=>`<div class="stamp"><strong>${game.xp>=xp?'✓':'◇'}</strong>${name}<br><small>${xp} XP</small></div>`).join('')}</div><h3>${T('已经完成的工作日','完了した勤務日')}</h3>${game.history.length?game.history.map(h=>`<div class="logEntry"><time>Day ${h.day}</time><span>${CASES[h.case].title} · ${h.score} ${T('分','点')} · +${h.xp} XP</span></div>`).join(''):'<p class="small">'+T('完成报告并打卡下班后，记录会出现在这里。','報告を完了して退勤すると、ここに記録が表示されます。')+'</p>'}`;showDialog(T('调查手帐','調査ノート'),T('NOTEBOOK / 当前浏览器存档','NOTEBOOK / このブラウザに保存'),body,'book:'+tab)}
function showNight(){const s=shift(),q=studyQuestions[E.caseIndex(game)],c=caseNow();if(!s.clocked)return;showDialog(T('下班后的时间','退勤後のひととき'),'END OF DAY '+game.day,`<span class="overline">${T('今日研修完成','本日の研修完了')}</span><h3 class="nightTitle">${T(`辛苦了，${E.rank(game)}。`,`お疲れさまでした、${E.rank(game)}。`)}</h3><p>${T(`你完成了「${c.title}」。明天，带着今天学到的判断方法继续工作。`,`「${c.title}」を完了しました。明日も、今日学んだ判断の進め方を生かして仕事を続けましょう。`)}</p>${reviewHTML()}<section class="section"><h3>${T('睡前读一页术语本','寝る前に用語ノートを 1 ページ')}</h3>${s.studied?'<div class="notice good">'+T('✓ 今日温习完成，获得 5 XP。','✓ 本日の復習が完了し、5 XP を獲得しました。')+'</div>':`<p>${q[0]}</p>${q[1].map((v,i)=>`<div class="rowActions"><button data-do="study" data-choice="${i}">${v}</button></div>`).join('')}<p class="small">${T('可选温习，不影响今天的专业评分。完成后 +5 XP，仅可领取一次。','復習は任意で、本日の専門スコアには影響しません。完了すると +5 XP（1 回のみ）。')}</p>`}</section><button class="primary" data-do="nextday">${T(`休息，开始第 ${game.day+1} 天 →`,`休んで ${game.day+1} 日目を始める →`)}</button><p class="small">${game.day%6===0?T('六个主线案例已完成。下一天开始新一轮相同案例复训，比较自己的推理进步。','メインの 6 ケースを完了しました。次の日からは同じケースで再研修が始まります。自分の推論の上達を比べてみましょう。'):T('下一天的事件：','次の日の案件：')+CASES[game.day%6].title}</p>`,'night')}
function guide(){showDialog(T('怎么玩晶圆厂日记','ファブ日記の遊び方'),'MOVEMENT + INVESTIGATION',`<h3>${T('像生活 RPG 一样，过工程师的一天','生活系 RPG のように、エンジニアの 1 日を過ごす')}</h3><p>${T('用 <b>WASD / 方向键</b>移动，走近工作站按 <b>E</b>。也可以直接点地图上的工作站，角色会自动走过去；手机可用方向按钮。','<b>WASD / 矢印キー</b>で移動し、ステーションに近づいて <b>E</b> を押します。マップ上のステーションを直接クリックすると、キャラクターが自動で歩いていきます。スマートフォンでは方向ボタンが使えます。')}</p><div class="section"><h3>${T('一天的安排','1 日の流れ')}</h3><p>${T('① 晨会领任务 → ② 机台巡检 → ③ 不同工位取证 → ④ 工程实验 → ⑤ 工位写报告 → ⑥ 出口打卡下班。','① 朝会で任務を受ける → ② 装置点検 → ③ 各ステーションでエビデンス収集 → ④ 検証実験 → ⑤ 自席で最終報告を作成 → ⑥ 出口で退勤。')}</p><p>${T('资料来源分散在不同工位。随时打开调查手帐查看已获得的证据，并修正假设。','資料は各ステーションに分散しています。いつでも調査ノートを開いて、取得済みのエビデンスを確認し、仮説を見直せます。')}</p></div><h3>${T('专注力、时间与成长','集中力・時間・成長')}</h3><p>${T('工作消耗专注力；休息角每次用 20 分钟恢复 35 点。时钟只随行动推进，阅读和移动不计时。超过 17:30 会显示加班，但不会强制结束或锁死关卡。','作業をすると集中力を消費します。休憩コーナーでは 1 回 20 分で 35 回復します。時計はアクションでのみ進み、閲覧や移動では進みません。17:30 を過ぎると残業と表示されますが、強制終了や進行不能にはなりません。')}</p><p>${T('专业评分来自证据与推理。每天巡检、与同事交流、结案和可选温习可获得成长；不能重复提交刷同一天奖励。','専門スコアはエビデンスと推論で決まります。毎日の点検、同僚との会話、最終報告、任意の復習で経験値(XP)が得られます。同じ日の報酬を繰り返し提出して稼ぐことはできません。')}</p><h3>${T('这是一版六天主线 RPG','6 日間のメインストーリー RPG です')}</h3><p>${T('包含移动、工作站、伙伴交流、每日任务、休息、经验称号和晚上温习。第七天起进入相同案例的复训。角色采用走路轻动画；未做四方向逐帧动作。','移動、ステーション、同僚との会話、毎日のタスク、休憩、経験値と称号、夜の復習が含まれます。7 日目からは同じケースの再研修に入ります。キャラクターは簡易的な歩行アニメーションで、4 方向のコマ送り動作はありません。')}</p><p class="small">${T('进度仅保存在当前浏览器。固定剧情和规则评分，不接入 AI 自动判读。游戏地图、人物及数据为教学模拟，真实工作应遵循企业程序。参考：','進行状況はこのブラウザにのみ保存されます。ストーリーは固定で、採点はルールベースです。AI による自動判定は使いません。マップ、人物、データは教育用のシミュレーションです。実際の業務では会社の手順に従ってください。参考：')}<a href="https://www.itl.nist.gov/div898/handbook/pmc/section3/pmc31.htm" target="_blank" rel="noopener">${T('NIST 控制图','NIST 管理図')}</a>、<a href="https://www.itl.nist.gov/div898/handbook/pri/section3/pri333.htm" target="_blank" rel="noopener">${T('全因子试验','完全実施要因計画（実験計画法）')}</a>。</p><p><a href="cases.html">${T('进入原来的六关经典训练模式 →','従来の 6 ステージ・クラシック研修モードへ（中文）→')}</a></p>`,'guide')}
function act(action,button){try{const c=caseNow(),s=shift();switch(action){case 'brief':E.brief(game);toast(T('晨会完成。去机台找小野做巡检。','朝会が終わりました。CMP装置で小野さんと点検をしましょう。'));break;case 'routine':{const q=routineQuestions[E.caseIndex(game)],ok=Number(button.dataset.choice)===q[2];E.routine(game,ok);toast(ok?T('巡检完成！现在可以去各工位取证。','点検完了！各ステーションでエビデンスを集められます。'):q[3]);break}case 'evidence':E.unlock(game,c,Number(button.dataset.eid),openPlace);toast(T('资料已放入调查手帐。','資料を調査ノートに保存しました。'));break;case 'test':E.test(game,c,Number(button.dataset.tid));toast(s.valid?T('受控验证完成。可以继续补证据或回工位结案。','管理下の検証が完了しました。エビデンスを追加するか、自席に戻って最終報告をまとめましょう。'):T('实验还不能区分原因，看看反馈后重新设计。','この実験では原因を切り分けられません。結果を確認して設計し直しましょう。'));break;case 'talk':{const id=button.dataset.person;E.talk(game,id);toast(T('与'+people[id].name+'的默契 +1',people[id].name+'との信頼度 +1'));break}case 'rest':E.rest(game);toast(T('稍作休息，专注力恢复了。','少し休憩して、集中力が回復しました。'));break;case 'submit':{const total=E.submit(game,c);toast(T('报告已提交：'+total+' 分，+'+s.xpAward+' XP','報告を提出しました：'+total+' 点、+'+s.xpAward+' XP'));break}case 'clockout':E.clockout(game,c);hud();showNight();return;case 'study':{const q=studyQuestions[E.caseIndex(game)],ok=Number(button.dataset.choice)===q[2];E.study(game,ok);toast(ok?T('温习完成，+5 XP。','復習完了、+5 XP。'):T('再想一想，也可以回手帐复习术语。','もう一度考えてみましょう。調査ノートで用語を復習することもできます。'));hud();showNight();return}case 'nextday':E.nextDay(game);briefIntro=true;closeDialog();hud();toast(T('新的一天。今天的任务已经送到晨会桌。','新しい 1 日です。本日の任務が朝会テーブルに届いています。'));return;case 'night':showNight();return;}hud();refreshStation();}catch(e){toast(e.message)}}
document.addEventListener('change',e=>{if(['problem','hyp','fix','pm'].includes(e.target.name)){try{E.choose(game,e.target.name,Number(e.target.value),caseNow());save();if($('submitCheck'))$('submitCheck').innerHTML=submitCheck()}catch(err){toast(err.message)}}});
document.addEventListener('input',e=>{if(e.target.id==='rpgNotes'&&!shift().report){game.shift.notes=e.target.value;clearTimeout(noteTimer);noteTimer=setTimeout(save,200)}});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.go)go(b.dataset.go);else if(b.dataset.do)act(b.dataset.do,b);else if(b.dataset.book)showNotebook(b.dataset.book)});
$('world').addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;if(shift().clocked){showNight();return}const r=$('world').getBoundingClientRect();const x=(e.clientX-r.left)/r.width*100,y=(e.clientY-r.top)/r.height*100;target={x:Math.max(7,Math.min(93,x)),y:Math.max(32,Math.min(68,y))};briefIntro=false;$('intro').hidden=true;$('destination').hidden=false;$('destination').style.left=target.x+'%';$('destination').style.top=target.y+'%';$('world').focus({preventScroll:true})});
function keyDirection(key){return {w:'up',ArrowUp:'up',a:'left',ArrowLeft:'left',s:'down',ArrowDown:'down',d:'right',ArrowRight:'right'}[key]}
document.addEventListener('keydown',e=>{if($('workDialog').open||e.ctrlKey||e.altKey||e.metaKey||['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;const dir=keyDirection(e.key);if(dir){e.preventDefault();if(shift().clocked){showNight();return}keys.add(dir);target=null;$('destination').hidden=true;briefIntro=false;$('intro').hidden=true;}if(e.key.toLowerCase()==='e'&&!e.repeat){e.preventDefault();const n=nearest();if(n.d<8)openStation(n.id);else toast(T('先走近一个工作站。','まずステーションに近づいてください。'))}});
document.addEventListener('keyup',e=>{const dir=keyDirection(e.key);if(dir){keys.delete(dir);save()}});window.addEventListener('blur',()=>{keys.clear();save()});window.addEventListener('pagehide',()=>save());
document.querySelectorAll('[data-dir]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();if(shift().clocked){showNight();return}b.setPointerCapture(e.pointerId);keys.add(b.dataset.dir);target=null;briefIntro=false;$('intro').hidden=true;$('destination').hidden=true});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>{keys.delete(b.dataset.dir);save()})});
$('interact').onclick=()=>{const n=nearest();if(n.d<8)openStation(n.id)};$('notebookButton').onclick=()=>showNotebook();$('guideButton').onclick=guide;$('closeDialog').onclick=()=>closeDialog();$('workDialog').addEventListener('cancel',()=>{openPlace=null;keys.clear()});
function tick(t){const dt=Math.min((t-frameAt)/1000,0.05)||0;frameAt=t;let moving=false;if(!$('workDialog').open&&!shift().clocked){let dx=(keys.has('right')?1:0)-(keys.has('left')?1:0),dy=(keys.has('down')?1:0)-(keys.has('up')?1:0);if(dx||dy){const n=Math.hypot(dx,dy);game.position.x=Math.max(7,Math.min(93,game.position.x+dx/n*22*dt));game.position.y=Math.max(32,Math.min(68,game.position.y+dy/n*33*dt));moving=true;if(dx)$('player').classList.toggle('left',dx<0);}else if(target){const dx=target.x-game.position.x,dy=(target.y-game.position.y)/1.5,n=Math.hypot(dx,dy);if(n<0.45){game.position={x:target.x,y:target.y};const id=target.station;target=null;$('destination').hidden=true;save();updatePosition();if(id)openStation(id);}else{const step=Math.min(n,22*dt);game.position.x+=dx/n*step;game.position.y+=dy/n*step*1.5;moving=true;if(Math.abs(dx)>.1)$('player').classList.toggle('left',dx<0);}}}if(moving)updatePosition();$('player').classList.toggle('walking',moving);requestAnimationFrame(tick)}
hud();requestAnimationFrame(tick);if(shift().clocked)showNight();
if($('langButton'))$('langButton').onclick=()=>{save();setLang(LANG==='ja'?'zh':'ja')};
if(document.modelContext?.registerTool){for(const tool of [{name:'read_fab_day',description:T('读取当前 RPG 工作日、角色位置与已解锁证据。不返回隐藏案例答案。','現在の RPG の勤務日、キャラクターの位置、取得済みのエビデンスを読み取ります。非公開のケースの答えは返しません。'),inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({day:game.day,time:E.time(game),energy:shift().energy,position:{...game.position},objectives:objectives(),evidence:shift().opened.map(i=>({id:i,...caseNow().evidence[i]}))})},{name:'start_walk_to_workstation',description:T('让 RPG 角色开始走向指定工作站；到达后显示工作站交互。此操作只开始移动，不完成调查或报告。','RPG のキャラクターを指定したステーションへ歩かせます。到着するとステーションの操作画面が表示されます。この操作は移動を開始するだけで、調査や報告は完了しません。'),inputSchema:{type:'object',properties:{station:{type:'string',enum:E.stations.map(s=>s.id)}},required:['station'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||!E.stations.some(s=>s.id===input.station))throw Error(T('无效工作站','無効なステーションです'));if(shift().clocked)throw Error(T('当天已下班，请先开始新一天','本日はすでに退勤済みです。先に新しい 1 日を開始してください'));go(input.station);return {walkingTo:input.station}}}]){try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{})}catch(e){}}}
