/* 量产值班模式界面（中文 / 日本語）。逻辑在 shiftsim.js，这里只负责显示与操作。 */
const DEMO=/[?&]demo=1/.test(location.search);
const L=CMP_LINE,LINE_KEY=DEMO?'cmp-fab-line-demo':'cmp-fab-line-v1',$=id=>document.getElementById(id);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const LANG_KEY='cmp-fab-lang';let st=L.fresh(),lang='ja',saveOk=true,resetArmed=false,toastTimer=null;
try{const raw=JSON.parse(localStorage.getItem(LINE_KEY)||'null');if(raw&&!DEMO)st=L.normalize(raw.state);if(DEMO)st=L.demo();const v=localStorage.getItem(LANG_KEY);if(v==='zh'||v==='ja')lang=v}catch(e){saveOk=false}

const TXT={zh:{
 title:'量产值班',qualIdle:'Tool {t} 没有在生产：等待保养后确认，已 {h} 小时没有出货。到 Tool {t} 面板顶部点「保养后确认」。',qualStopped:'Tool {t} 现在没有生产（已 {h} 小时没有出货）。',qualStartHint:'换过耗材的机台要先做「保养后确认」，合格后才会恢复生产。今天第一件事先处理它。',qualBar:'Tool {t} 还在等保养后确认，这一小时它不会生产。',done:'已执行：{a}',noPoints:'本小时的工时点已用完，操作按钮暂时不可用。推进 1 小时后恢复。',lang:'日本語',help:'? 说明',reset:'重新开始',back:'← 研修中心',book:'📖 手册',
 day:'值班第 {d} 天',clock:'时间',points:'本小时工时点',kLots:'已跑批',kGood:'合格出货',kHold:'扣留中',kDown:'停机小时',kCost:'成本',target:'目标 {n} 批',
 running:'生产中',down:'停机中 · 还需 {h} 小时',reason:'原因：{r}',
 chartTitle:'Tool {t} · 膜厚控制图（M1 在线量测，nm）',chartAria:'Tool {t} 最近 {n} 批的膜厚控制图',cl:'中心线',ucl:'控制上限',lcl:'控制下限',usl:'规格上限',lsl:'规格下限',noLots:'还没有数据。推进一小时开始生产。',
 recent:'最近批次',colLot:'批号',colTh:'膜厚',colNu:'非均匀度 %',colDef:'缺陷',colSt:'状态',
 stReleased:'已放行',stHold:'扣留',stReworked:'已返工',stScrapped:'已报废',
 time:'研磨时间 {s} s',timeNote:'调时间只是补偿，原因还在',
 aInspect:'检查实际反馈',aCondition:'修整研磨垫',aDresser:'更换修整盘',aFlowcal:'校准流量',aPresscal:'校准压力',aRing:'更换保持环',aPad:'更换研磨垫',aTimeUp:'+5 s',aTimeDown:'−5 s',aReference:'测标准片',aMetercal:'校准 M1',
 costLine:'{p} 工时点 · 停机 {d} h · 成本 {c}',costLine0:'{p} 工时点 · 不停机',
 alerts:'控制图报警',noAlerts:'目前没有报警。没有报警不等于没有变化，留意趋势。',
 r1:'Tool {t}：1 点超出 3σ 控制界限',r2:'Tool {t}：连续 3 点中有 2 点超出 2σ（同侧）',r3:'Tool {t}：连续 6 点在中心线同一侧',wNu:'Tool {t}：非均匀度 {v}% 接近规格 5%',wDef:'Tool {t}：缺陷 {v} 接近规格 15',
 holds:'扣留批 · 等你判定',noHolds:'没有扣留批。',holdWhy:'M1 膜厚 {m} nm · 非均匀度 {nu}% · 缺陷 {def}',m2:'M2 复测',m2val:'M2 复测：{v} nm',rework:'返工（补磨）',scrap:'报废',release:'按现状放行',holdNote:'膜偏厚可以补磨；偏薄补不回来。判定不耗工时点，M2 复测耗 1 点。',
 metro:'量测室',refLine:'{at} 标准片（200 nm）：M1 {m1} / M2 {m2}',noRef:'还没测过标准片。',
 checks:'检查记录',noChecks:'还没检查过机台。',checkLine:'{at} Tool {t}：压力 设定 {sp} / 实际 {ap} psi；流量 设定 {sf} / 实际 {af} mL/min；垫 {pa} 片；保持环磨损指数 {rw}',glazed:'垫表面发亮，有堵塞迹象。',dresserWorn:'修整盘金刚石已磨钝，修整效果变差。',checkOk:'垫表面与修整盘外观正常。',
 log:'操作记录',advance:'▶ 推进 1 小时',endShift:'写交接，结束今天',ended:'今天 8 小时已跑完。',
 noteTitle:'交接记录',notePh:'今天发生了什么（现象、时间、机台）？做了什么处置、结果如何？还有什么需要下一班跟进？事实和推测分开写。',noteHint:'写了交接记录才有记录分。内容不做自动评判，明天开工时会原样给你看。',confirmEnd:'交班，查看日结',
 reportTitle:'第 {d} 天 · 日结',score:'值班评分',sOutput:'产出',sQuality:'品质',sResponse:'异常响应',sRecord:'交接记录',
 cpkLine:'今日工序能力 Cpk（M1 膜厚）：Tool A {a} · Tool B {b}',cpkNote:'Cpk = min(规格上限 − 平均, 平均 − 规格下限) ÷ 3σ。一般要求 1.33 以上。平均偏了或波动大了都会变低；这里每天只有几批，数值仅供参考。',
 lifePad:'研磨垫',lifeRing:'保持环',lifeDresser:'修整盘',lifeUnitW:'片',lifeUnitL:'批',lifeWarn:'接近寿命',lifeOver:'超过寿命',qualWait:'等待保养后确认',qualWhy:'换过耗材后，先用监控片确认去除速率、均匀性、颗粒都合格，再放产品。',aQual:'保养后确认（监控片）',aSkipqual:'不确认，直接放产品',qualLine:'{at} Tool {t} 保养后确认：速率 {r} nm/min · 非均匀度 {n}% · 颗粒 {p} → {v}',qualPass:'合格，已放行',qualFail:'不合格，再跑一次确认',kQualSkip:'跳过保养后确认',demoBanner:'演示模式（从第 2 天 11:00 开始）：Tool B 的控制图从早上开始上漂，Tool A 正常。这里的操作不会影响你自己的存档。',demoExit:'退出演示',demoBtn:'演示',
 kEscape:'不良流出',kFalse:'误报废（其实合格）',kScrap:'报废',kRework:'返工',
 reveal:'已解决异常的复盘',noReveal:'今天没有解决任何异常。',openFaults:'还有 {n} 个异常没有解决，明天继续影响生产。不公布是什么。',noOpen:'目前没有遗留异常。',
 fDresser:'Tool {t} 修整盘磨钝：垫堵塞加快，去除速率逐批下降、膜厚上漂。修整垫只能暂时缓解，更换修整盘才是根本处置。',fFlow:'Tool {t} 实际流量逐渐低于设定：去除速率下降、膜厚上漂。流量校准后恢复。',fPressure:'Tool {t} 实际压力高于设定：去除速率跳升、膜厚突然偏薄，缺陷也增加。压力校准后恢复。',fMeter:'M1 量测偏差：读数整体偏低，两台机台同时“变薄”，真实膜厚其实正常。标准片可以发现，校准 M1 后恢复。',
 fTimeline:'发生 {o} → 发现 {d} → 解决 {f} · 受影响 {n} 批',
 next:'开始第 {d} 天',startTitle:'第 {d} 天 · 开工',startBody:'两台 CMP 机台连续生产，每小时各出 1 批。你每小时有 {p} 个工时点，用来检查、校准、换耗材或复测。今天的目标是合格出货 {n} 批。',lastNote:'上一班（昨天的你）留下的交接：',noLastNote:'昨天没有留下交接记录。',firstDay:'第一天的前两个小时不会出异常，先看看正常的控制图长什么样。',go:'开始值班',
 helpTitle:'量产值班怎么玩',helpBody:'<h3>你的工作</h3><p>机台自己在跑产品。你要做的是从控制图上发现“过程变了”，判断原因，用最小的停机代价处理，并对扣留的批次做出放行、返工或报废的决定。</p><h3>信息从哪来</h3><p>控制图只告诉你“变了”，不告诉你为什么。要知道原因，得花工时点去检查机台实际反馈、测标准片。两台机台同时朝一个方向变，和只有一台变，指向的原因不一样。</p><h3>代价</h3><p>校准和换耗材要停机，停机就少出货；不处理，不良会流出或者整批报废。把合格的批次误报废同样扣分。调研磨时间可以临时把膜厚拉回来，但原因还在。</p><h3>评分</h3><p>产出 30 + 品质 40 + 异常响应 20 + 交接记录 10。日结只公布你已经解决的异常，没解决的明天继续。</p><p class="small">全部数值为游戏设定的教学模型，不是实际设备数据。故障机理的说明见研修中心的学习手册。</p><h3>标准处置对照表</h3><div class="tableWrap"><table class="simTable"><thead><tr><th>看到的现象</th><th>先做什么确认</th><th>标准处置</th></tr></thead><tbody><tr><td>只有一台机台，膜厚逐批上漂</td><td>检查该机台实际反馈</td><td>显示“修整盘磨钝”→ 更换修整盘（只修整垫只能暂缓）；实际流量低于设定 → 校准流量；“垫表面发亮”→ 修整研磨垫</td></tr><tr><td>只有一台机台，膜厚突然变薄、缺陷增加</td><td>检查该机台实际反馈</td><td>实际压力高于设定 → 校准压力</td></tr><tr><td>两台机台同时变薄</td><td>测标准片</td><td>M1 读数低于 200 → 校准 M1。这期间被扣留的批先用 M2 复测，真实膜厚合格就放行；不要报废，也不要去调研磨时间</td></tr><tr><td>耗材寿命条变黄或变红</td><td>—</td><td>找产量压力小的时段更换；换完先做“保养后确认”，合格再放产品。跳过确认有概率带出两批缺陷</td></tr><tr><td>扣留批：膜偏厚，缺陷和均匀性合格</td><td>拿不准就 M2 复测</td><td>返工（补磨）</td></tr><tr><td>扣留批：膜偏薄</td><td>M2 复测</td><td>M2 合格 → 放行（多半是 M1 偏了）；M2 也偏薄 → 报废，补不回来</td></tr><tr><td>扣留批：缺陷或均匀性超标</td><td>—</td><td>报废，并检查该机台找原因</td></tr></tbody></table></div><p class="small">顺序永远是：先判断“一台还是两台”，再花工时点确认，最后才停机处置。调研磨时间只是临时补偿，不算解决。每小时只有 2 个工时点，先用在确认原因上。</p>',
 resetAsk:'确定清空量产值班的进度吗？',resetYes:'确定清空',resetNo:'保留',
 saveFail:'当前浏览器无法保存进度。',foot1:'量产值班 · 两台机台 · 耗材跨天延续',foot2:'教学模型，非实际设备数据。',
 'err.noqual':'这台机台现在不需要做保养后确认。','log.qual':'Tool {tool} 保养后确认','log.skipqual':'Tool {tool} 未做确认，直接放产品',
 'err.points':'这个小时的工时点用完了。','err.down':'机台正在停机中。','err.ended':'今天已经结束，请先交班。','err.rework':'只有膜偏厚、且缺陷和均匀性合格的批才能返工。','err.m2':'这批已经复测过了。','err.range':'研磨时间超出允许范围。','err.lot':'这批不在扣留状态。','err.action':'无效操作。','err.tool':'无效机台。',
 'log.inspect':'检查 Tool {tool} 实际反馈','log.condition':'Tool {tool} 停机修整研磨垫','log.dresser':'Tool {tool} 停机更换修整盘','log.flowcal':'Tool {tool} 停机校准流量','log.presscal':'Tool {tool} 停机校准压力','log.ring':'Tool {tool} 停机更换保持环','log.pad':'Tool {tool} 停机更换研磨垫（含磨合与确认）','log.reference':'测标准片','log.metercal':'校准 M1','log.timeUp':'Tool {tool} 研磨时间调到 {v} s','log.timeDown':'Tool {tool} 研磨时间调到 {v} s','log.m2':'{lot} 送 M2 复测','log.rework':'{lot} 返工','log.scrap':'{lot} 报废','log.release':'{lot} 按现状放行','log.up':'Tool {tool} 恢复生产'
},ja:{
 title:'量産シフト',qualIdle:'Tool {t} は生産していません：保養後確認待ちで、{h} 時間出荷がありません。Tool {t} パネル上部の「保養後確認」を押してください。',qualStopped:'Tool {t} は現在生産していません（{h} 時間出荷なし）。',qualStartHint:'消耗品を交換した号機は、まず「保養後確認」を行い、合格してから生産を再開します。今日は最初にこれを対応しましょう。',qualBar:'Tool {t} はまだ保養後確認待ちです。この1時間は生産されません。',done:'実行しました：{a}',noPoints:'この1時間の工数ポイントを使い切ったため、操作ボタンは一時的に使えません。1時間進めると回復します。',lang:'中文',help:'? 説明',reset:'最初から',back:'← 研修センター',book:'📖 ハンドブック',
 day:'シフト {d} 日目',clock:'時刻',points:'この1時間の工数ポイント',kLots:'処理ロット',kGood:'良品出荷',kHold:'ホールド中',kDown:'停止時間',kCost:'コスト',target:'目標 {n} ロット',
 running:'生産中',down:'停止中 · あと {h} 時間',reason:'理由：{r}',
 chartTitle:'Tool {t} · 膜厚管理図（M1 インライン測定、nm）',chartAria:'Tool {t} の直近 {n} ロットの膜厚管理図',cl:'中心線',ucl:'上方管理限界',lcl:'下方管理限界',usl:'規格上限',lsl:'規格下限',noLots:'まだデータがありません。1時間進めると生産が始まります。',
 recent:'直近のロット',colLot:'ロット',colTh:'膜厚',colNu:'面内均一性 %',colDef:'欠陥',colSt:'状態',
 stReleased:'リリース済',stHold:'ホールド',stReworked:'再研磨済',stScrapped:'廃棄',
 time:'研磨時間 {s} s',timeNote:'時間調整は補正にすぎず、原因は残ります',
 aInspect:'実測値を確認',aCondition:'パッドをドレッシング',aDresser:'ドレッサー交換',aFlowcal:'流量校正',aPresscal:'圧力校正',aRing:'リテーナリング交換',aPad:'パッド交換',aTimeUp:'+5 s',aTimeDown:'−5 s',aReference:'標準ウェーハ測定',aMetercal:'M1 校正',
 costLine:'{p} ポイント · 停止 {d} h · コスト {c}',costLine0:'{p} ポイント · 停止なし',
 alerts:'管理図アラーム',noAlerts:'現在アラームはありません。アラームがないことは、変化がないことを意味しません。傾向に注意してください。',
 r1:'Tool {t}：1点が3σ管理限界を超えました',r2:'Tool {t}：連続3点中2点が同じ側で2σを超えました',r3:'Tool {t}：6点連続で中心線の同じ側にあります',wNu:'Tool {t}：面内均一性 {v}% が規格 5% に近づいています',wDef:'Tool {t}：欠陥数 {v} が規格 15 に近づいています',
 holds:'ホールドロット · 判定待ち',noHolds:'ホールド中のロットはありません。',holdWhy:'M1 膜厚 {m} nm · 面内均一性 {nu}% · 欠陥 {def}',m2:'M2 で再測定',m2val:'M2 再測定：{v} nm',rework:'再研磨（リワーク）',scrap:'廃棄',release:'このままリリース',holdNote:'膜が厚い場合は追加研磨できますが、薄い場合は元に戻せません。判定にポイントは不要、M2 再測定は 1 ポイントです。',
 metro:'測定室',refLine:'{at} 標準ウェーハ（200 nm）：M1 {m1} / M2 {m2}',noRef:'まだ標準ウェーハを測定していません。',
 checks:'確認記録',noChecks:'まだ装置を確認していません。',checkLine:'{at} Tool {t}：圧力 設定 {sp} / 実測 {ap} psi、流量 設定 {sf} / 実測 {af} mL/min、パッド {pa} 枚、リテーナリング摩耗指数 {rw}',glazed:'パッド表面に光沢があり、目詰まりの兆候があります。',dresserWorn:'ドレッサーのダイヤモンドが摩耗し、ドレッシング効果が落ちています。',checkOk:'パッド表面とドレッサーの外観は正常です。',
 log:'操作ログ',advance:'▶ 1時間進める',endShift:'引き継ぎを書いて終了',ended:'本日の8時間が終了しました。',
 noteTitle:'引き継ぎ記録',notePh:'今日何が起きたか（現象、時刻、号機）。どんな処置をして結果はどうだったか。次のシフトに対応してほしいことは何か。事実と推測は分けて書きます。',noteHint:'引き継ぎを書くと記録点が入ります。内容の自動採点はしません。翌日の開始時にそのまま表示されます。',confirmEnd:'引き継いで日報を見る',
 reportTitle:'{d} 日目 · 日報',score:'シフト評価',sOutput:'生産量',sQuality:'品質',sResponse:'異常対応',sRecord:'引き継ぎ',
 cpkLine:'本日の工程能力 Cpk（M1 膜厚）：Tool A {a} · Tool B {b}',cpkNote:'Cpk = min(規格上限 − 平均, 平均 − 規格下限) ÷ 3σ。一般に 1.33 以上が求められます。平均のずれでも、ばらつきの増加でも低下します。1日数ロットのみのため、参考値です。',
 lifePad:'パッド',lifeRing:'リテーナリング',lifeDresser:'ドレッサー',lifeUnitW:'枚',lifeUnitL:'ロット',lifeWarn:'寿命間近',lifeOver:'寿命超過',qualWait:'立ち上げ確認待ち',qualWhy:'消耗品を交換した後は、モニターウェーハで研磨レート、面内均一性、パーティクルが合格であることを確認してから製品を流します。',aQual:'立ち上げ確認（モニターウェーハ）',aSkipqual:'確認せずに製品を流す',qualLine:'{at} Tool {t} 立ち上げ確認：レート {r} nm/min · 面内均一性 {n}% · パーティクル {p} → {v}',qualPass:'合格、リリース済み',qualFail:'不合格、もう一度確認',kQualSkip:'立ち上げ確認の省略',demoBanner:'デモモード（2日目 11:00 から開始）：Tool B の管理図が朝から上昇傾向、Tool A は正常です。ここでの操作は、ご自身のセーブデータに影響しません。',demoExit:'デモを終了',demoBtn:'デモ',
 kEscape:'不良流出',kFalse:'誤廃棄（実は良品）',kScrap:'廃棄',kRework:'再研磨',
 reveal:'解決した異常の振り返り',noReveal:'今日解決した異常はありません。',openFaults:'未解決の異常が {n} 件あり、明日も生産に影響します。内容は公開しません。',noOpen:'未解決の異常はありません。',
 fDresser:'Tool {t} のドレッサー摩耗：パッドの目詰まりが早まり、研磨レートがロットごとに低下、膜厚が上昇しました。ドレッシングは一時的な緩和で、ドレッサー交換が恒久対策です。',fFlow:'Tool {t} の実流量が設定より徐々に低下：研磨レートが下がり、膜厚が上昇しました。流量校正で回復します。',fPressure:'Tool {t} の実圧力が設定より高い状態：研磨レートが急に上がり、膜厚が薄くなり、欠陥も増えました。圧力校正で回復します。',fMeter:'M1 測定機のバイアス：測定値が全体に低く出て、両号機が同時に「薄く」見えましたが、実際の膜厚は正常でした。標準ウェーハで発見でき、M1 校正で回復します。',
 fTimeline:'発生 {o} → 発見 {d} → 解決 {f} · 影響 {n} ロット',
 next:'{d} 日目を開始',startTitle:'{d} 日目 · 始業',startBody:'2台のCMP装置が連続生産し、1時間ごとに各1ロットを処理します。1時間あたり {p} ポイントの工数で、確認・校正・消耗品交換・再測定を行います。本日の目標は良品出荷 {n} ロットです。',lastNote:'前シフト（昨日の自分）からの引き継ぎ：',noLastNote:'昨日の引き継ぎ記録はありません。',firstDay:'初日の最初の2時間は異常が発生しません。まず正常な管理図の姿を確認してください。',go:'シフト開始',
 helpTitle:'量産シフトの進め方',helpBody:'<h3>あなたの仕事</h3><p>装置は自動で製品を処理します。あなたの役割は、管理図から「工程が変化した」ことに気づき、原因を判断し、最小の停止時間で処置し、ホールドされたロットをリリース・再研磨・廃棄のいずれにするか決めることです。</p><h3>情報の取り方</h3><p>管理図は「変化した」ことしか教えてくれません。原因を知るには、工数ポイントを使って装置の実測値を確認したり、標準ウェーハを測定したりする必要があります。両号機が同じ方向に変化した場合と、片方だけが変化した場合では、疑うべき原因が違います。</p><h3>代償</h3><p>校正や消耗品交換には装置停止が必要で、停止すれば出荷が減ります。放置すれば不良が流出するか、ロットが廃棄になります。良品を誤って廃棄しても減点です。研磨時間の調整で膜厚を一時的に戻せますが、原因は残ります。</p><h3>評価</h3><p>生産量 30 + 品質 40 + 異常対応 20 + 引き継ぎ 10。日報では解決済みの異常だけを公開し、未解決のものは翌日に持ち越します。</p><p class="small">数値はすべてゲーム用の教育モデルであり、実際の装置データではありません。故障メカニズムの解説は研修センターのハンドブックにあります。</p><h3>標準の対処早見表</h3><div class="tableWrap"><table class="simTable"><thead><tr><th>見える現象</th><th>まず確認すること</th><th>標準の対処</th></tr></thead><tbody><tr><td>1 台だけ、膜厚がロットごとに上昇</td><td>その号機の実測値を確認</td><td>「ドレッサー摩耗」→ ドレッサー交換（パッドのドレッシングだけでは一時しのぎ）。実流量が設定より低い → 流量校正。「パッド表面に光沢」→ パッドをドレッシング</td></tr><tr><td>1 台だけ、膜厚が急に薄くなり欠陥も増加</td><td>その号機の実測値を確認</td><td>実圧力が設定より高い → 圧力校正</td></tr><tr><td>2 台同時に薄くなる</td><td>標準ウェーハを測定</td><td>M1 が 200 未満 → M1 校正。その間のホールドロットは M2 で再測定し、実際の膜厚が合格ならリリース。廃棄や研磨時間の調整はしない</td></tr><tr><td>消耗品の寿命バーが黄色または赤</td><td>—</td><td>生産に余裕のある時間帯に交換。交換後は「保養後確認」を行い、合格してから製品を流す。確認を省くと 2 ロット分の欠陥が出る可能性あり</td></tr><tr><td>ホールド：膜が厚い、欠陥と均一性は合格</td><td>迷ったら M2 再測定</td><td>再研磨（リワーク）</td></tr><tr><td>ホールド：膜が薄い</td><td>M2 再測定</td><td>M2 が合格 → リリース（多くは M1 の偏り）。M2 でも薄い → 廃棄（元には戻せない）</td></tr><tr><td>ホールド：欠陥または均一性が規格外</td><td>—</td><td>廃棄し、その号機を点検して原因を探す</td></tr></tbody></table></div><p class="small">順番は常に同じ：まず「1 台か 2 台か」を判断し、次に工数ポイントで確認し、最後に停止して対処します。研磨時間の調整は一時的な補正で、解決ではありません。工数ポイントは 1 時間に 2 つだけなので、まず原因の確認に使います。</p>',
 resetAsk:'量産シフトの進行状況を消去しますか？',resetYes:'消去する',resetNo:'残す',
 saveFail:'このブラウザでは進行状況を保存できません。',foot1:'量産シフト · 2号機 · 消耗品は日をまたいで継続',foot2:'教育用モデルであり、実際の装置データではありません。',
 'err.noqual':'この号機は現在、立ち上げ確認の必要がありません。','log.qual':'Tool {tool} 立ち上げ確認','log.skipqual':'Tool {tool} 立ち上げ確認を省略して製品を流した',
 'err.points':'この1時間の工数ポイントを使い切りました。','err.down':'装置は停止中です。','err.ended':'本日は終了しました。先に引き継ぎを行ってください。','err.rework':'再研磨できるのは、膜が厚く、欠陥と均一性が規格内のロットだけです。','err.m2':'このロットは再測定済みです。','err.range':'研磨時間が許容範囲外です。','err.lot':'このロットはホールド中ではありません。','err.action':'無効な操作です。','err.tool':'無効な号機です。',
 'log.inspect':'Tool {tool} の実測値を確認','log.condition':'Tool {tool} を停止してドレッシング','log.dresser':'Tool {tool} を停止してドレッサー交換','log.flowcal':'Tool {tool} を停止して流量校正','log.presscal':'Tool {tool} を停止して圧力校正','log.ring':'Tool {tool} を停止してリテーナリング交換','log.pad':'Tool {tool} を停止してパッド交換（慣らし・確認込み）','log.reference':'標準ウェーハを測定','log.metercal':'M1 を校正','log.timeUp':'Tool {tool} の研磨時間を {v} s に変更','log.timeDown':'Tool {tool} の研磨時間を {v} s に変更','log.m2':'{lot} を M2 で再測定','log.rework':'{lot} を再研磨','log.scrap':'{lot} を廃棄','log.release':'{lot} をこのままリリース','log.up':'Tool {tool} 生産再開'
}};
function t(key,args){let s=TXT[lang][key]??TXT.zh[key]??key;if(args)for(const [k,v] of Object.entries(args))s=s.replaceAll('{'+k+'}',v);return s}
function persist(){try{const copy={...st};delete copy._mem;localStorage.setItem(LINE_KEY,JSON.stringify({state:copy}));localStorage.setItem(LANG_KEY,lang)}catch(e){saveOk=false}}
function toast(s){clearTimeout(toastTimer);(h=>{if($('toast').parentNode!==h)h.appendChild($('toast'))})(document.querySelector('dialog[open]')||document.body);$('toast').textContent=s;$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,3800)}
function dialog(title,area,body,closable=true){$('dlgTitle').textContent=title;$('dlgArea').textContent=area;$('dialogBody').innerHTML=body;$('dlgClose').hidden=!closable;$('lineDialog').dataset.closable=closable?'1':'';if(!$('lineDialog').open)$('lineDialog').showModal();$('lineDialog').scrollTop=0}
const stamp=x=>x?`D${x.day} ${L.clock(x.hour)}`:'—';

function chartSVG(id){
  const pts=L.chart(st,id,24),W=560,H=210,x0=44,x1=W-12,y=v=>H-24-(Math.max(176,Math.min(224,v))-176)/48*(H-44),x=i=>x0+(pts.length<2?(x1-x0)/2:i*(x1-x0)/(Math.max(pts.length,12)-1));
  const {cl,sigma}=L.CHART,line=(v,cls,label)=>`<line x1="${x0}" x2="${x1}" y1="${y(v)}" y2="${y(v)}" class="${cls}"/><text x="4" y="${y(v)+4}" class="axis">${label}</text>`;
  if(!pts.length)return `<p class="small chartEmpty">${t('noLots')}</p>`;
  const seps=pts.map((p,i)=>i>0&&p.day!==pts[i-1].day?`<line x1="${(x(i)+x(i-1))/2}" x2="${(x(i)+x(i-1))/2}" y1="12" y2="${H-24}" class="daySep"/><text x="${(x(i)+x(i-1))/2+3}" y="${H-8}" class="axis">D${p.day}</text>`:'').join('');
  return `<svg class="spc" viewBox="0 0 ${W} ${H}" role="img" aria-label="${t('chartAria',{t:id,n:pts.length})}">${line(L.SPEC.hi,'spec',L.SPEC.hi)}${line(L.SPEC.lo,'spec',L.SPEC.lo)}${line(cl+3*sigma,'ctrl','UCL')}${line(cl-3*sigma,'ctrl','LCL')}${line(cl,'center',cl)}${seps}<polyline points="${pts.map((p,i)=>`${x(i)},${y(p.mTh)}`).join(' ')}" class="trace"/>${pts.map((p,i)=>`<circle cx="${x(i)}" cy="${y(p.mTh)}" r="${p.flag||p.status==='hold'?5:3.5}" class="${p.mTh>L.SPEC.hi||p.mTh<L.SPEC.lo?'oos':p.flag?'flag':'okpt'}"><title>${p.name}：${p.mTh} nm</title></circle>`).join('')}</svg><div class="chartLegend"><span class="lg center">${t('cl')} ${cl}</span><span class="lg ctrl">${t('ucl')}/${t('lcl')} ${(cl+3*sigma).toFixed(1)} / ${(cl-3*sigma).toFixed(1)}</span><span class="lg spec">${t('usl')}/${t('lsl')} ${L.SPEC.hi} / ${L.SPEC.lo}</span></div>`;
}
function actionButton(action,id,labelKey){const a=L.ACTIONS[action],dis=st.ended||st.points<a.points||(id&&st.down[id]>0&&action!=='inspect');return `<button data-act="${action}" ${id?`data-tool="${id}"`:''} ${dis?'disabled':''} title="${a.down?t('costLine',{p:a.points,d:a.down,c:a.cost}):t('costLine0',{p:a.points})}">${t(labelKey)}<small>${a.down?a.down+'h · ':''}${a.cost?a.cost:''}</small></button>`}
function toolPanel(id){
  const down=st.down[id],pendingQual=!down&&st.qual[id],lifeRows=L.life(st,id).map(([k,used,max])=>{const q=used/max,name={pad:'lifePad',ring:'lifeRing',dresser:'lifeDresser'}[k];return `<div class="lifeRow ${q>1?'over':q>=.85?'warn':''}"><span>${t(name)}</span><div class="meter"><i style="width:${Math.min(100,q*100)}%"></i></div><b>${used} / ${max} ${t(k==='dresser'?'lifeUnitL':'lifeUnitW')}${q>1?' · '+t('lifeOver'):q>=.85?' · '+t('lifeWarn'):''}</b></div>`}).join(''),lots=st.lots.filter(l=>l.tool===id).slice(-5).reverse(),stName={released:'stReleased',hold:'stHold',reworked:'stReworked',scrapped:'stScrapped'};
  return `<div class="toolHead"><h2>Tool ${id}</h2><span class="toolState ${down||pendingQual?'isDown':''}">${pendingQual?t('qualWait'):down?t('down',{h:down})+(st.downReason[id]?' · '+t('a'+st.downReason[id][0].toUpperCase()+st.downReason[id].slice(1)):''):t('running')}</span></div>${pendingQual?`<div class="notice"><p><b>${t('qualStopped',{t:id,h:idleHours(id)})}</b></p><p class="small">${t('qualWhy')}</p><div class="rowActions">${actionButton('qual',id,'aQual')}<button data-act="skipqual" data-tool="${id}">${t('aSkipqual')}</button></div></div>`:''}<div class="lifeBox">${lifeRows}</div><h3 class="chartTitle">${t('chartTitle',{t:id})}</h3>${chartSVG(id)}<div class="tableWrap"><table class="simTable"><thead><tr><th>${t('colLot')}</th><th>${t('colTh')}</th><th>${t('colNu')}</th><th>${t('colDef')}</th><th>${t('colSt')}</th></tr></thead><tbody>${lots.map(l=>`<tr><td>${l.name}</td><td class="${l.mTh>L.SPEC.hi||l.mTh<L.SPEC.lo?'fail':''}">${l.mTh}</td><td class="${l.nu>L.SPEC.nu?'fail':''}">${l.nu}</td><td class="${l.def>L.SPEC.def?'fail':''}">${l.def}</td><td>${t(stName[l.status])}</td></tr>`).join('')}${'<tr aria-hidden="true"><td colspan="5">&nbsp;</td></tr>'.repeat(5-lots.length)}</tbody></table></div><div class="timeRow"><span>${t('time',{s:st.recipes[id].time})}</span>${actionButton('timeDown',id,'aTimeDown')}${actionButton('timeUp',id,'aTimeUp')}<small>${t('timeNote')}</small></div><div class="actGrid">${actionButton('inspect',id,'aInspect')}${actionButton('condition',id,'aCondition')}${actionButton('dresser',id,'aDresser')}${actionButton('flowcal',id,'aFlowcal')}${actionButton('presscal',id,'aPresscal')}${actionButton('ring',id,'aRing')}${actionButton('pad',id,'aPad')}</div>`;
}
/* 等待保养后确认的机台不生产。界面必须把“它停着、停了多久”说清楚，否则很容易一停好几天。 */
function idleHours(id){const last=st.lots.filter(l=>l.tool===id).at(-1);return last?Math.max(0,(st.day-last.day)*L.HOURS+(st.hour-last.hour)-1):st.hour+(st.day-1)*L.HOURS}
function waitingQual(){return ['A','B'].filter(id=>st.qual[id]&&!(st.down[id]>0))}
function alertList(){
  const out=[];
  for(const id of waitingQual())out.push(['flag',t('qualIdle',{t:id,h:idleHours(id)})]);
  for(const id of ['A','B']){const pts=L.chart(st,id,24),last=pts.at(-1);if(!last)continue;if(last.flag)out.push(['flag',t(last.flag,{t:id})]);if(last.nu>4&&last.nu<=L.SPEC.nu)out.push(['warn',t('wNu',{t:id,v:last.nu})]);if(last.def>=12&&last.def<=L.SPEC.def)out.push(['warn',t('wDef',{t:id,v:last.def})])}
  return `<div class="alertBox ${out.length?'has':''}"><b>${t('alerts')}</b>${out.length?out.map(([c,s])=>`<span class="${c}">${s}</span>`).join(''):`<span class="none">${t('noAlerts')}</span>`}</div>`;
}
function sidePanel(){
  const holds=st.lots.filter(l=>l.status==='hold');
  return `<section class="section"><h3>${t('holds')}${holds.length?' · '+holds.length:''}</h3><div class="holdList">${holds.length?holds.map(l=>`<div class="holdLot"><b>${l.name}</b><p class="small">${t('holdWhy',{m:l.mTh,nu:l.nu,def:l.def})}${l.m2!==null?'<br>'+t('m2val',{v:l.m2}):''}</p><div class="rowActions"><button data-lot="${l.id}" data-what="m2" ${l.m2!==null||st.points<1?'disabled':''}>${t('m2')}</button><button data-lot="${l.id}" data-what="rework">${t('rework')}</button><button data-lot="${l.id}" data-what="scrap">${t('scrap')}</button><button data-lot="${l.id}" data-what="release">${t('release')}</button></div></div>`).join('')+`<p class="small">${t('holdNote')}</p>`:`<p class="small">${t('noHolds')}</p>`}</div></section><section class="section"><h3>${t('metro')}</h3><div class="actGrid">${actionButton('reference',null,'aReference')}${actionButton('metercal',null,'aMetercal')}</div>${st.refs.length?st.refs.slice(0,3).map(r=>`<p class="small">D${r.day} ${t('refLine',{at:r.at,m1:r.M1,m2:r.M2})}</p>`).join(''):`<p class="small">${t('noRef')}</p>`}</section><section class="section"><h3>${t('checks')}</h3>${st.checks.length?st.checks.slice(0,4).map(c=>`<p class="small">D${c.day} ${t('checkLine',{at:c.at,t:c.tool,sp:c.setP,ap:c.actP,sf:c.setF,af:c.actF,pa:c.padAge,rw:c.ringWear})}<br>${c.dresserWorn?t('dresserWorn'):c.glazed?t('glazed'):t('checkOk')}</p>`).join(''):`<p class="small">${t('noChecks')}</p>`}</section>${st.qualLog&&st.qualLog.length?`<section class="section"><h3>${t('aQual')}</h3>${st.qualLog.slice(0,3).map(q=>`<p class="small">D${q.day} ${t('qualLine',{at:q.at,t:q.tool,r:q.rate,n:q.nu,p:q.particles,v:t(q.pass?'qualPass':'qualFail')})}</p>`).join('')}</section>`:''}<section class="section"><h3>${t('log')}</h3><div class="lineLog">${st.log.slice(-10).reverse().map(l=>`<div class="logEntry"><time>D${l.day} ${l.at}</time><span>${t(l.key,l.args)}</span></div>`).join('')}</div></section>`;
}
function render(){
  document.documentElement.lang=lang==='ja'?'ja':'zh-CN';document.title=t('title')+' · Fab Days';
  $('appTitle').textContent=t('title');$('langButton').textContent=t('lang');$('helpButton').textContent=t('help');$('resetButton').textContent=t('reset');$('backLink').textContent=t('back');$('bookLink').textContent=t('book');$('foot1').textContent=t('foot1');$('foot2').textContent=saveOk?t('foot2'):t('saveFail');
  const d=st.today,holds=st.lots.filter(l=>l.status==='hold').length;
  $('hud').innerHTML=`<div class="day"><span class="overline">${t('day',{d:st.day})}</span><strong>${L.clock(Math.min(st.hour,L.HOURS))}</strong></div><div class="pointsBox"><span class="overline">${t('points')}</span><strong>${'●'.repeat(st.points)}${'○'.repeat(L.POINTS-st.points)}</strong></div><div class="kpis"><span>${t('kLots')} <b>${d.lots}</b></span><span>${t('kGood')} <b>${d.good}</b> <small>${t('target',{n:L.TARGET})}</small></span><span>${t('kHold')} <b class="${holds?'warnText':''}">${holds}</b></span><span>${t('kDown')} <b>${d.down}</b></span><span>${t('kCost')} <b>${d.cost}</b></span></div>`;
  $('alerts').innerHTML=(DEMO?`<div class="alertBox has"><b>DEMO</b><span class="flag">${t('demoBanner')}</span><a href="shift.html">${t('demoExit')}</a></div>`:'')+alertList();if($('demoLink')){$('demoLink').textContent=t('demoBtn');$('demoLink').hidden=DEMO}$('toolA').innerHTML=toolPanel('A');$('toolB').innerHTML=toolPanel('B');$('side').innerHTML=sidePanel();
  $('advanceBar').innerHTML=st.ended?`<span>${t('ended')}</span><button class="primary" data-ui="endShift">${t('endShift')}</button>`:`${waitingQual().length?`<span class="warnText">${t('qualBar',{t:waitingQual().join(' / ')})}</span>`:st.points<1?`<span>${t('noPoints')}</span>`:''}<button class="primary" data-ui="advance">${t('advance')}</button>`;
  persist();
}
function showStart(){dialog(t('startTitle',{d:st.day}),'SHIFT START',`<p>${t('startBody',{p:L.POINTS,n:L.TARGET})}</p>${st.day===1?`<div class="notice">${t('firstDay')}</div>`:`<section class="section"><h3>${t('lastNote')}</h3><p class="handover">${st.lastNote.trim()?esc(st.lastNote).replace(/\n/g,'<br>'):t('noLastNote')}</p></section>`}${waitingQual().map(id=>`<div class="notice"><b>${t('qualStopped',{t:id,h:idleHours(id)})}</b><br>${t('qualStartHint')}</div>`).join('')}<button class="primary" data-ui="closeDialog">${t('go')}</button>`)}
function showEndForm(){dialog(t('noteTitle'),'HANDOVER',`<textarea id="noteBox" placeholder="${t('notePh')}">${esc(st.note)}</textarea><p class="small">${t('noteHint')}</p><button class="primary" data-ui="confirmEnd">${t('confirmEnd')}</button>`)}
function showReport(h){
  const names={output:'sOutput',quality:'sQuality',response:'sResponse',record:'sRecord'},k=h.kpi,fKey={dresser:'fDresser',flow:'fFlow',pressure:'fPressure',meter:'fMeter'};
  dialog(t('reportTitle',{d:h.day}),'DAILY REPORT',`<div class="scoreHero"><div><strong>${h.score.total}<small style="font-size:16px"> / 100</small></strong><p>${t('score')}</p></div></div><div class="scoreGrid">${h.score.rows.map(r=>`<div class="scoreRow">${t(names[r[0]])}<b>${r[1]} / ${r[2]}</b><div class="meter"><i style="width:${r[1]/r[2]*100}%"></i></div></div>`).join('')}</div><div class="costSummary"><span>${t('kLots')} <b>${k.lots}</b></span><span>${t('kGood')} <b>${k.good}</b></span><span>${t('kRework')} <b>${k.rework}</b></span><span>${t('kScrap')} <b>${k.scrap}</b></span><span>${t('kFalse')} <b>${k.falseScrap}</b></span><span>${t('kEscape')} <b>${k.escape}</b></span><span>${t('kDown')} <b>${k.down}</b></span><span>${t('kCost')} <b>${k.cost}</b></span>${k.qualSkipped?`<span>${t('kQualSkip')} <b class="warnText">${k.qualSkipped}</b></span>`:''}</div>${h.cpk?`<p>${t('cpkLine',{a:h.cpk.A??'—',b:h.cpk.B??'—'})}</p><p class="small">${t('cpkNote')}</p>`:''}<h3>${t('reveal')}</h3>${h.revealed.length?h.revealed.map(f=>`<section class="section"><p>${t(fKey[f.type],{t:f.tool||''})}</p><p class="small">${t('fTimeline',{o:stamp(f),d:stamp(f.detectedAt),f:stamp(f.fixedAt),n:f.lotsBad})}</p></section>`).join(''):`<p class="small">${t('noReveal')}</p>`}<div class="notice ${h.open?'':'good'}">${h.open?t('openFaults',{n:h.open}):t('noOpen')}</div><button class="primary" data-ui="nextDay">${t('next',{d:st.day})}</button>`,false);
}
document.addEventListener('click',e=>{
  const b=e.target.closest('button');if(!b||b.disabled)return;
  try{
    if(b.dataset.act){const act=b.dataset.act,res=L.act(st,act,b.dataset.tool);render();toast(act==='inspect'?t('checkLine',{at:res.at,t:res.tool,sp:res.setP,ap:res.actP,sf:res.setF,af:res.actF,pa:res.padAge,rw:res.ringWear})+' '+t(res.dresserWorn?'dresserWorn':res.glazed?'glazed':'checkOk'):act==='reference'?t('refLine',{at:res.at,m1:res.M1,m2:res.M2}):act==='qual'?t('qualLine',{at:res.at,t:res.tool,r:res.rate,n:res.nu,p:res.particles,v:t(res.pass?'qualPass':'qualFail')}):t('done',{a:t('log.'+act,{tool:b.dataset.tool||'',v:typeof res==='number'?res:''})}))}
    else if(b.dataset.lot){L.lotAction(st,Number(b.dataset.lot),b.dataset.what);render()}
    else if(b.dataset.ui==='advance'){L.advance(st);render();if(st.ended)toast(t('ended'))}
    else if(b.dataset.ui==='endShift')showEndForm();
    else if(b.dataset.ui==='confirmEnd'){st.note=$('noteBox').value;const h=L.endDay(st);render();showReport(h)}
    else if(b.dataset.ui==='nextDay'){$('lineDialog').close();showStart()}
    else if(b.dataset.ui==='closeDialog')$('lineDialog').close();
    else if(b.dataset.ui==='resetYes'){st=L.fresh();resetArmed=false;$('lineDialog').close();render();showStart()}
  }catch(err){toast(t(err.message))}
});
document.addEventListener('input',e=>{if(e.target.id==='noteBox'){st.note=e.target.value;persist()}});
$('lineDialog').addEventListener('cancel',e=>{if(!$('lineDialog').dataset.closable)e.preventDefault()});
$('dlgClose').onclick=()=>$('lineDialog').close();
$('langButton').onclick=()=>{lang=lang==='zh'?'ja':'zh';render()};
$('helpButton').onclick=()=>dialog(t('helpTitle'),'HOW TO PLAY',t('helpBody'));
$('resetButton').onclick=()=>dialog(t('reset'),'RESET',`<p>${t('resetAsk')}</p><div class="rowActions"><button data-ui="resetYes">${t('resetYes')}</button><button class="primary" data-ui="closeDialog">${t('resetNo')}</button></div>`);
render();if(st.hour===0&&!st.ended&&!DEMO)showStart();
