/* Illustrative CMP process model, not calibrated to production equipment. */
(function(root){
const T=root.T||((zh)=>zh);
const bounds={pressure:[1.5,4.5,.1,T('压力','研磨圧力'),'psi'],speed:[30,100,5,T('研磨盘转速','定盤回転数'),'rpm'],flow:[100,300,10,T('研磨液流量','スラリー流量'),'mL/min'],time:[30,100,5,T('研磨时间','研磨時間'),'s'],temp:[20,30,.5,T('研磨盘温度','定盤温度'),'°C']};
const defaults=()=>({pressure:3,speed:60,flow:200,time:60,temp:23});
const scenarios=[
 {title:T('同样的配方，膜却磨不下去','同じレシピなのに、膜が削れない'),brief:T('Tool A 的加工后膜厚比历史高。配方没有改动，Pad 已使用较长时间。先用试片建立基准，再决定该调参数还是处理耗材。','Tool A の研磨後膜厚が過去の実績より高くなっています。レシピは変更されておらず、研磨パッドは長時間使用されています。まずテストウェーハでベースラインを取り、パラメータを調整すべきか、消耗品に対処すべきかを判断してください。'),debrief:T('本场景 Tool A 的研磨垫表面堵塞降低了有效接触。修整可恢复表面；更换新垫后还需要磨合。加压能补偿速率，但可能恶化缺陷。','本シナリオでは、Tool A の研磨パッド表面の目詰まりにより、有効な接触が低下していました。ドレッシングで表面を回復できます。新しいパッドに交換した場合は、さらに慣らしが必要です。圧力を上げれば研磨レートは補えますが、欠陥が悪化するおそれがあります。')},
 {title:T('设定流量与结果对不上','設定流量と結果が合わない'),brief:T('Tool A 去除量不足。流量设定仍为 200 mL/min，设备未报警。请对照实际反馈与试片结果，找到可重复的改善。','Tool A の除去量が不足しています。流量設定は 200 mL/min のままで、装置のアラームも出ていません。実測値とテストウェーハの結果を照らし合わせ、再現性のある改善策を見つけてください。'),debrief:T('本场景 Tool A 流量反馈存在比例偏差，实际供液约为设定的 {v}%。检查与校准能定位问题。改大设定也可能临时恢复供液，但不等于解释了偏差来源。','本シナリオでは、Tool A の流量フィードバックに比例的なずれがあり、実際の供給量は設定の約 {v}% でした。点検と校正で問題箇所を特定できます。設定値を大きくしても一時的に供給量は回復しますが、ずれの原因を説明したことにはなりません。')},
 {title:T('中心好好的，边缘出了问题','中心は良好なのに、エッジに問題が出ている'),brief:T('总体膜厚接近目标，但片内分布和缺陷开始恶化。不要只追求均值，看看晶圆地图，再选择你的干预。','全体の膜厚は目標に近いものの、面内分布と欠陥が悪化し始めています。平均値だけを追わず、ウェーハマップを確認してから対処方法を選んでください。'),debrief:T('本场景 Tool A 保持环磨损导致边缘局部去除和缺陷增加。换研磨垫不能消除这一因素；保持环更换前后的单变量比较更能支持原因判断。','本シナリオでは、Tool A のリテーナリングの摩耗により、エッジ部の局所的な除去と欠陥が増加していました。研磨パッドを交換してもこの要因は解消されません。リテーナリング交換前後の一因子比較のほうが、原因の判断をより強く裏付けます。')},
 {title:T('两个参数一起变了','二つのパラメータが同時に変わった'),brief:T('当前工艺温度为 27°C，流量为 150 mL/min。缺陷增加，去除量也不稳定。你可以分别调整，也可以设计自己的 2×2 实验。','現在のプロセスは温度 27°C、流量 150 mL/min です。欠陥が増え、除去量も安定していません。それぞれ個別に調整してもよいですし、自分で 2×2 実験を設計してもかまいません。'),debrief:T('本场景高温与低供液存在缺陷交互项。单独改变压力无法消除它；可以通过覆盖四个温度/流量组合来识别。有效方案可以不止一个。','本シナリオでは、高温と低い供給量の間に、欠陥に関する交互作用項があります。圧力だけを変えても解消できません。温度/流量の 4 つの組み合わせをすべて試すことで特定できます。有効な解決策は一つとは限りません。')},
 {title:T('读数正常，就真的正常吗','測定値が正常なら、本当に正常なのか'),brief:T('量测室 M1 的膜厚读数突然降低。你可以调配方，也可以让同一片晶圆在另一台量测设备上复测。先决定如何验证读数。','測定室の M1 で膜厚の測定値が突然低下しました。レシピを調整することも、同じウェーハを別の測定機で再測定することもできます。まず、測定値をどう検証するかを決めてください。'),debrief:T('本场景 M1 带有 {v} nm 的系统偏差，真实加工条件正常。仅按 M1 调整工艺，可能把原本合格的晶圆调坏。参考片、M2 交叉量测和量测校准提供区分证据。','本シナリオでは、M1 に {v} nm の系統的な偏りがあり、実際の加工条件は正常でした。M1 の値だけでプロセスを調整すると、本来合格だったウェーハを不良にしてしまうおそれがあります。標準ウェーハ、M2 とのクロス測定、測定機の校正が、切り分けの根拠になります。')},
 {title:T('A 和 B 的距离','A と B の距離'),brief:T('同一配方在两台设备上表现不同。你可以切换 Tool A/B、比较实际条件，更换部件或重新校准。请用实验建立机台间的可比关系。','同じレシピでも、2 台の装置で結果が異なります。Tool A/B の切り替え、実際の条件の比較、部品の交換、再校正ができます。実験を通じて、装置間で比較可能な関係を確立してください。'),debrief:T('本场景 Tool A 的实际压力高于设定约 {v}%。Tool B 可作为对照。压力校准恢复设定与实际的一致性；改变配方也能补偿，但需要记录工具差异。','本シナリオでは、Tool A の実際の圧力が設定より約 {v}% 高くなっていました。Tool B を対照として使えます。圧力校正により、設定値と実測値の一致が回復します。レシピの変更でも補正できますが、装置間の差を記録しておく必要があります。')}
];
/* 每个场景的参考解法：看什么 → 怎么定位 → 标准处置 → 常见误区。与 scenarios 顺序一致；文中的 Tool A 由 describe() 按本场实际机台替换。 */
const solutions=[
 {see:T('Tool A 基准片膜厚明显偏高（约 260–290 nm），非均匀度正常，缺陷略多。整片均匀地“磨不动”，说明是去除速率整体下降，不是边缘问题。','Tool A のベースラインは膜厚が明らかに高く（約 260–290 nm）、面内均一性は正常、欠陥はやや多め。全面が均一に「削れない」ので、エッジの問題ではなく研磨レート全体の低下です。'),find:T('到机台「实际反馈」点检查：压力、流量的设定与实际一致，但表面描述为“纹理变浅，局部有光滑区域”，垫使用量 2000 片以上——指向研磨垫表面堵塞。','号機の「実測値」で点検：圧力・流量は設定と実測が一致していますが、表面は「テクスチャが浅く、一部に平滑な領域」、パッド使用量は 2000 枚以上。研磨パッド表面の目詰まりを示しています。'),fix:T('「耗材与校准」里执行修整 120 秒（60 秒可能不够，膜厚会卡在 210 nm 上下）。加工 1 片并量测，和基准片建立对照——只差“修整时间”一项。之后不再动任何东西，重复加工 3 片。','「消耗品と校正」でドレッシング 120 秒を実行（60 秒では不足することがあり、膜厚が 210 nm 前後に留まります）。1 枚処理・測定し、ベースラインと比較を作成——差は「ドレッシング時間」の 1 つだけ。その後は何も触らず 3 枚繰り返します。'),trap:T('加压也能把膜厚拉回来，但压力超过约 3.25 psi 缺陷会快速增加，而且原因还在。直接换新垫也行，但新垫要先修整磨合，否则边缘不均、缺陷偏多，成本也高得多。','圧力を上げても膜厚は戻りますが、約 3.25 psi を超えると欠陥が急増し、原因も残ります。新しいパッドへの交換でも解決しますが、慣らしのドレッシングをしないとエッジの不均一と欠陥が増え、コストも大幅に高くなります。')},
 {see:T('Tool A 基准片膜厚偏高（约 270–310 nm），均匀性和缺陷正常。现象和垫堵塞很像，只看试片分不出来。','Tool A のベースラインは膜厚が高く（約 270–310 nm）、均一性と欠陥は正常。パッドの目詰まりと現象がよく似ており、ウェーハだけでは区別できません。'),find:T('关键在「实际反馈」：流量设定 200，实际只有 120–145 mL/min；垫表面正常。设定与实际不一致，就是线索。','決め手は「実測値」：流量の設定 200 に対し、実測は 120–145 mL/min。パッド表面は正常。設定と実測の不一致が手がかりです。'),fix:T('执行「流量校准」。加工 1 片并量测，与基准片建立对照——只差“流量校准版本”一项。再重复 3 片。','「流量校正」を実行。1 枚処理・測定し、ベースラインと比較——差は「流量校正バージョン」の 1 つだけ。さらに 3 枚繰り返します。'),trap:T('把流量设定调到 300 也能让实际供液回到够用的水平，读数会变好，但偏差还在，换个配方又会出问题。修整或换垫对这个场景没有用。','流量設定を 300 に上げても実供給量は足りる水準に戻り、読み値は良くなりますが、ずれは残り、別のレシピでまた問題になります。ドレッシングやパッド交換はこのシナリオでは効果がありません。')},
 {see:T('Tool A 基准片平均膜厚接近目标，但非均匀度超标、缺陷很多（常常 40 以上）。看晶圆地图：边缘一圈明显更薄。只看均值会以为没事。','Tool A のベースラインは平均膜厚こそ目標に近いものの、面内均一性が規格外で欠陥も非常に多い（40 以上になることも）。ウェーハマップではエッジ一周が明らかに薄くなっています。平均値だけ見ると問題なしに見えます。'),find:T('「实际反馈」里保持环磨损指数 0.8 以上、使用量约 8000 片；压力、流量正常。边缘问题 + 保持环磨损，指向保持环。','「実測値」でリテーナリング摩耗指数が 0.8 以上、使用量は約 8000 枚。圧力・流量は正常。エッジの問題＋リング摩耗で、リテーナリングが原因と分かります。'),fix:T('更换保持环。加工 1 片并量测，与基准片建立对照——只差“保持环”一项。再重复 3 片。','リテーナリングを交換。1 枚処理・測定し、ベースラインと比較——差は「リテーナリング」の 1 つだけ。さらに 3 枚繰り返します。'),trap:T('换研磨垫、修整、调参数都消除不了边缘问题。降压能少一点缺陷，但膜厚会跑出规格。','パッド交換、ドレッシング、パラメータ調整ではエッジの問題は解消しません。圧力を下げると欠陥は少し減りますが、膜厚が規格から外れます。')},
 {see:T('当前配方温度 27°C、流量 150 mL/min。基准片膜厚偏高（约 245–250 nm），缺陷超标（约 18）。两台机台一样，所以不是某台机台坏了，是配方的问题。','現在のレシピは温度 27°C、流量 150 mL/min。ベースラインは膜厚が高く（約 245–250 nm）、欠陥も規格外（約 18）。2 台とも同じなので、号機の故障ではなくレシピの問題です。'),find:T('缺陷来自“高温 × 低供液”的交互作用：温度高于 24°C 且实际流量低于 190 时才出现，两者缺一不可。用 2×2 DOE（温度 23/27 × 流量 150/200）可以直接看到：只有“27°C + 150”那一格缺陷高。','欠陥は「高温 × 低供給量」の交互作用によるもので、温度が 24°C 超かつ実流量が 190 未満のときだけ現れます。2×2 DOE（温度 23/27 × 流量 150/200）を行うと、「27°C + 150」のマスだけ欠陥が高いことが直接分かります。'),fix:T('先只把流量调回 200，加工 1 片并量测，与基准片建立对照（只差流量一项，缺陷应回到个位数）。再把温度调回 23°C，用“23°C + 200”重复加工 3 片作为最终方案。','まず流量だけを 200 に戻して 1 枚処理・測定し、ベースラインと比較（差は流量の 1 つだけ。欠陥は 1 桁に戻るはず）。次に温度を 23°C に戻し、「23°C + 200」で 3 枚繰り返して最終案とします。'),trap:T('一次把温度和流量都改掉，结果会变好，但建立的对照差 2 个因素，拿不到单变量对照的分，也说不清是谁起了作用。只调压力解决不了缺陷。','温度と流量を一度に変えると結果は良くなりますが、比較の差が 2 因子になり、一因子比較の点が取れず、どちらが効いたのかも説明できません。圧力だけの調整では欠陥は解消しません。')},
 {see:T('M1 读出的膜厚偏低（约 175–185 nm），看起来像“多磨了”。但均匀性、缺陷都正常，机台也没有任何变化记录。','M1 の膜厚の読み値が低く（約 175–185 nm）、「削りすぎ」のように見えます。しかし均一性も欠陥も正常で、号機側に変化の記録もありません。'),find:T('先怀疑量测：在量测室检查 200 nm 参考片，M1 读数比 200 低十几到二十几 nm，M2 正常；再把同一片试片用 M2 复测，读数约 200 nm。晶圆没有问题，是 M1 偏了。','まず測定を疑います：測定室で 200 nm 標準ウェーハを確認すると、M1 は 200 より十数〜二十数 nm 低く、M2 は正常。同じウェーハを M2 で再測定すると約 200 nm。ウェーハに問題はなく、M1 が偏っています。'),fix:T('校准 M1（或之后全部改用 M2）。配方和耗材一样都不要动。同一片在 M1、M2 各测一次就满足对照要求；再用原配方加工 3 片，用 M2 或校准后的 M1 量测。','M1 を校正（または以後すべて M2 を使用）。レシピと消耗品は一切変えません。同じウェーハを M1 と M2 の両方で測定すれば比較の要件を満たします。さらに元のレシピで 3 枚処理し、M2 または校正後の M1 で測定します。'),trap:T('按 M1 的读数去缩短研磨时间或降压，会把本来合格的晶圆磨得不够——这正是这一关的陷阱。校准前的 M1 读数不会自动修正，要重新量测。','M1 の読み値に合わせて研磨時間を短くしたり圧力を下げたりすると、本来合格だったウェーハが研磨不足になります——これがこのシナリオの罠です。校正前の M1 の読み値は自動では修正されないため、再測定が必要です。')},
 {see:T('Tool A 基准片膜厚明显偏薄（约 135–160 nm），缺陷偏多；换到 Tool B 用同一配方加工，结果正常。问题在 Tool A 身上。','Tool A のベースラインは膜厚が明らかに薄く（約 135–160 nm）、欠陥も多め。同じレシピで Tool B を使うと結果は正常。問題は Tool A 側にあります。'),find:T('Tool A 的「实际反馈」：压力设定 3.0 psi，实际约 3.4–3.7 psi；Tool B 设定与实际一致。实际压力偏高 → 去除过多、缺陷增加。','Tool A の「実測値」：圧力の設定 3.0 psi に対し、実測は約 3.4–3.7 psi。Tool B は設定と実測が一致。実圧力が高い → 削りすぎ、欠陥増加。'),fix:T('在 Tool A 上执行「压力校准」。加工 1 片并量测，与 Tool A 的基准片建立对照——只差“压力校准版本”一项。再重复 3 片。','Tool A で「圧力校正」を実行。1 枚処理・測定し、Tool A のベースラインと比較——差は「圧力校正バージョン」の 1 つだけ。さらに 3 枚繰り返します。'),trap:T('拿 Tool A 和 Tool B 的试片建立对照不算单变量：机台、垫、环同时不同。把 Tool A 的压力设定调低也能补偿，但两台机台从此用不同配方，必须留下记录，否则下一个人会踩坑。','Tool A と Tool B のウェーハ同士の比較は一因子比較になりません（号機・パッド・リングが同時に異なるため）。Tool A の圧力設定を下げて補正することもできますが、2 台のレシピが別々になるため、記録を残さないと次の担当者が困ります。')}
];
/* 本场的“关键动作”是否做过：用于结案后判断是消除了原因，还是只做了补偿。 */
function keyAction(sim){const n=sim.scenario,bad=sim.truth?.tool||'A',sv=sim.services.filter(s=>s.tool===bad).map(s=>s.action),final=sim.runs.find(r=>r.id===sim.finalId),p=final?.snapshot.recipe;if(n===0)return sv.includes('condition')||sv.includes('pad');if(n===1)return sv.includes('flow');if(n===2)return sv.includes('ring');if(n===3)return !!p&&(p.temp<=24||final.snapshot.actual.flow>=190);if(n===4)return sim.services.some(s=>s.action==='meter')||sim.runs.some(r=>r.measurements.some(m=>m.meter==='M2'));return sv.includes('pressure');}
/* 进行中显示的任务说明：只写现象，不点名原因方向。原 brief 结案后再显示。 */
const tasks=[
 T('Tool A 最近加工后的膜厚比历史值高。配方没有改动，设备没有报警。先用试片建立基准，再找出原因并验证。','Tool A の最近の研磨後膜厚が過去の実績より高くなっています。レシピは変更されておらず、装置のアラームもありません。まずテストウェーハでベースラインを取り、原因を特定して検証してください。'),
 T('Tool A 的去除量不足，膜厚偏高。配方没有改动，设备没有报警。找到可重复的改善，并说明原因。','Tool A の除去量が不足し、膜厚が高めです。レシピは変更されておらず、装置のアラームもありません。再現性のある改善策を見つけ、原因を説明してください。'),
 T('Tool A 的平均膜厚接近目标，但均匀性和缺陷开始恶化。找出原因并验证，注意不要只看均值。','Tool A の平均膜厚は目標に近いものの、均一性と欠陥が悪化し始めています。平均値だけで判断せず、原因を特定して検証してください。'),
 T('两台机台都出现缺陷增加、去除量不稳定。配方最近有过调整。找出原因并验证。','2 台とも欠陥が増え、除去量も安定していません。レシピは最近調整されています。原因を特定して検証してください。'),
 T('加工后膜厚的读数突然降低。机台没有变更记录，设备没有报警。先决定怎样确认这个现象，再决定是否调整工艺。','研磨後膜厚の測定値が急に低下しました。装置側に変更の記録はなく、アラームもありません。まずこの現象をどう確認するかを決め、そのうえでプロセスを調整するかどうかを判断してください。'),
 T('同一配方下，Tool A 最近的膜厚和缺陷与 Tool B 出现了差异。找出原因，并让两台机台重新可比。','同じレシピで、Tool A の最近の膜厚と欠陥が Tool B と異なっています。原因を特定し、2 台を再び比較可能な状態にしてください。')
];
const clone=o=>JSON.parse(JSON.stringify(o)),r=(x,n=2)=>Math.round(x*10**n)/10**n;
function random(seed){let a=seed>>>0;return ()=>{a+=0x6D2B79F5;let t=a;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return ((t^t>>>14)>>>0)/4294967296}}
function tool(id){return {id,pad:{serial:id+'-P0',type:'standard',age:600,glaze:0,ready:1,conditioning:0},ring:{serial:id+'-R0',wear:.08,age:1800},slurry:'L1',flowGain:1,pressureGain:1,calibration:0,flowCalibration:0,pressureCalibration:0};}
/* 每次开场随机：故障幅度、耗材使用量、片间波动。第二轮（第 7 天）起，问题机台可能是 B，并混入与原因无关的“看起来可疑”的耗材；
   第 3 天起偶尔发生研磨液换桶。随机结果存进 sim，读档后不变；truth 只在结案复盘里公布。 */
function init(day,scenario){const n=Number.isInteger(scenario)&&scenario>=0&&scenario<6?scenario:(day-1)%6,loop=Math.floor((day-1)/6),seed=Math.floor(Math.random()*2147483646)+1,rnd=random(seed),pick=(lo,hi,step)=>r(lo+Math.floor(rnd()*(Math.round((hi-lo)/step)+1))*step,3);
const tools={A:tool('A'),B:tool('B')},recipes={A:defaults(),B:defaults()},bad=loop>0&&rnd()<.5?'B':'A',f=tools[bad];let value=null,herring=null,event=null;
for(const t of Object.values(tools)){t.pad.age=pick(300,1100,50);t.ring.age=pick(1200,2600,100)}
if(n===0){f.pad.age=pick(2100,2700,50);f.pad.glaze=pick(.45,.65,.05)}if(n===1){f.flowGain=pick(.6,.72,.03);value=Math.round(f.flowGain*100)}if(n===2){f.ring.wear=pick(.8,.95,.05);f.ring.age=pick(7600,8800,100)}if(n===3){recipes.A.temp=27;recipes.A.flow=150;recipes.B.temp=27;recipes.B.flow=150}if(n===5){f.pressureGain=pick(1.14,1.22,.02);value=Math.round((f.pressureGain-1)*100)}
const bias=n===4?-pick(16,24,2):0;if(n===4)value='−'+(-bias);
if(loop>0){const kind=['pad','ring',null][Math.floor(rnd()*3)],t=tools[rnd()<.5?'A':'B'];if(kind==='pad'&&n!==0){t.pad.age=pick(1700,2000,50);herring={kind,tool:t.id}}if(kind==='ring'&&n!==2){t.ring.age=pick(5200,6400,100);herring={kind,tool:t.id}}}
if(day>2&&rnd()<.4)event={type:'slurry',after:pick(4,7,1),fired:false};
const free=n===3||n===4,startConfigs={};for(const id of free?['A','B']:[bad])startConfigs[id]=JSON.stringify(fingerprintRaw(recipes[id],tools[id]));
return {version:1,scenario:n,seed,noise:pick(.01,.016,.002),defNoise:3,truth:{tool:bad,value},herring,event,tool:'A',recipes,tools,bias,meterEpoch:0,referenceChecked:false,referenceLog:[],runs:[],checks:[],services:[],expense:0,serial:1,note:'',hypothesis:'',conclusion:'',finalId:null,compared:[],startRecipe:clone(recipes.A),startConfig:startConfigs[bad]||startConfigs.A,startConfigs};}
/* 场景文字：问题机台是 B 时对调 A/B；{v} 换成本场实际幅度；复盘附上干扰项与突发事件的说明。旧存档没有 truth 时用原始数值。 */
function describe(sim){const s=scenarios[sim.scenario],swap=sim.truth?.tool==='B',v=sim.truth?.value??[null,65,null,null,'−18',18][sim.scenario],fix=x=>{x=x.replace('{v}',v);return swap?x.replace(/Tool ([AB])/g,(m,k)=>'Tool '+(k==='A'?'B':'A')):x};let debrief=fix(s.debrief);
if(sim.herring)debrief+=' '+(sim.herring.kind==='pad'?T(`干扰项：Tool ${sim.herring.tool} 的研磨垫使用量偏高，但表面没有堵塞，不是本场原因。`,`紛らわしい点：Tool ${sim.herring.tool} の研磨パッドは使用量が多めでしたが、表面の目詰まりはなく、今回の原因ではありません。`):T(`干扰项：Tool ${sim.herring.tool} 的保持环使用量偏高，但磨损指数正常，不是本场原因。`,`紛らわしい点：Tool ${sim.herring.tool} のリテーナリングは使用量が多めでしたが、摩耗指数は正常で、今回の原因ではありません。`));
if(sim.event?.fired)debrief+=' '+T('突发事件：中途研磨液从 L1 换成 L2，L2 的去除速率约高 4.5%。换桶前后的试片不是同一条件。','突発イベント：途中でスラリーが L1 から L2 に切り替わりました。L2 は研磨レートが約 4.5% 高く、切り替え前後のウェーハは同一条件ではありません。');
if(sim.slips?.length)debrief+=' '+T('专注力不足时的操作失误：','集中力が低いときの操作ミス：')+sim.slips.map(x=>x.kind==='recipe'?T(`${x.at} 加工 #${x.run} 前，Tool ${x.tool} 的${bounds[x.key][3]}从 ${x.from} 误设为 ${x.to} ${bounds[x.key][4]}`,`${x.at} #${x.run} の処理前に、Tool ${x.tool} の${bounds[x.key][3]}を ${x.from} から ${x.to} ${bounds[x.key][4]} に誤設定`):T(`${x.at} 量测 ${x.runs.map(n=>'#'+n).join('、')} 时本想用 ${x.want}，实际用了 ${x.got}`,`${x.at} ${x.runs.map(n=>'#'+n).join('、')} の測定で ${x.want} のつもりが ${x.got} を使用`)).join(T('；','；'))+T('。这些都留在了记录里，你当时发现了吗？','。いずれも記録に残っていました。その場で気づけましたか？');
const so=solutions[sim.scenario];return {title:s.title,brief:fix(s.brief),task:fix(tasks[sim.scenario]),debrief,solution:{see:fix(so.see),find:fix(so.find),fix:fix(so.fix),trap:fix(so.trap)}};}
function fireEvent(g){const e=g.sim.event;if(!e||e.fired||g.sim.runs.length<e.after)return;const hit=Object.values(g.sim.tools).filter(t=>t.slurry==='L1');if(!hit.length){g.sim.event=null;return}e.fired=true;for(const t of hit)t.slurry='L2';const label=T('物料通知：L1 当前桶已用完，供液自动切到 L2（可在耗材页换回新一桶 L1）','資材連絡：L1 の現在の缶が空になり、供給が自動で L2 に切り替わりました（消耗品ページで新しい L1 に戻せます）');g.shift.log.push({at:CMP_RPG.time(g),text:label});g.sim.services.push({at:CMP_RPG.time(g),action:'event',arg:'',tool:hit.map(t=>t.id).join('/'),label});e.notice=label;}
/* 专注力低于 FOCUS 时，加工和量测可能出现操作失误。失误如实留在配方、快照和量测记录里，当场不提示，结案复盘才公布。
   休息的恢复量逐次递减（35、30、25…最低 15），所以靠反复休息硬撑一整天行不通。 */
const FOCUS=30;
function slipChance(g){const e=g.shift.energy;return e>=FOCUS?0:.15+(FOCUS-e)/FOCUS*.4}
function slipRoll(g,salt){return random((g.sim.seed??g.day)*31+g.shift.log.length*17+salt)}
function noteSlip(g,slip){(g.sim.slips??=[]).push({at:CMP_RPG.time(g),...slip})}
function restGain(g){return Math.max(15,35-5*g.shift.breaks)}
function rest(g){edit(g);if(g.shift.energy===100)throw Error(T('现在精力充足，休息角随时欢迎你。','今は集中力が十分です。休憩コーナーはいつでも利用できます。'));const gain=restGain(g);g.shift.minute+=20;g.shift.energy=Math.min(100,g.shift.energy+gain);g.shift.breaks++;g.shift.log.push({at:CMP_RPG.time(g),text:T(`休息 20 分钟，恢复 ${gain} 点专注力`,`20 分休憩し、集中力を ${gain} 回復`)});return gain;}
function active(g){return g.sim.tools[g.sim.tool]}
function edit(g){if(g.shift.report)throw Error(T('今日实验已结案。可以查看记录，或下班进入下一场。','本日の実験は完了済みです。記録を確認するか、退勤して次のシナリオへ進んでください。'))}
function spend(g,minutes,energy,money,text){edit(g);if(g.shift.energy<energy)throw Error(T('专注力不足，先去休息角恢复。','集中力が足りません。まず休憩コーナーで回復してください。'));g.shift.energy-=energy;g.shift.minute+=minutes;g.sim.expense+=money;g.shift.log.push({at:CMP_RPG.time(g),text});}
function configure(g,key,v){edit(g);if(!bounds[key])throw Error(T('未知参数','不明なパラメータです'));v=Number(v);const [lo,hi,step]=bounds[key];if(!Number.isFinite(v)||v<lo||v>hi)throw Error(T('参数超出教学台允许范围','パラメータが実習台の許容範囲を超えています'));v=r(lo+Math.round((v-lo)/step)*step,3);g.sim.recipes[g.sim.tool][key]=v;return v;}
function selectTool(g,id){edit(g);if(!['A','B'].includes(id))throw Error(T('未知设备','不明な装置です'));g.sim.tool=id;}
function fingerprintRaw(p,t){return {...p,tool:t.id,pad:t.pad.serial,padType:t.pad.type,conditioning:t.pad.conditioning,ring:t.ring.serial,slurry:t.slurry,flowCalibration:t.flowCalibration,pressureCalibration:t.pressureCalibration};}
function snapshot(g){const s=g.sim,t=active(g),p=s.recipes[s.tool];return {tool:s.tool,recipe:clone(p),pad:clone(t.pad),ring:clone(t.ring),slurry:t.slurry,calibration:t.calibration,actual:{pressure:r(p.pressure*t.pressureGain,3),flow:r(p.flow*t.flowGain,2),temp:p.temp},fingerprint:fingerprintRaw(p,t)};}
function metric(points,time,defects){const a=points.map(p=>p.t),mean=a.reduce((x,y)=>x+y,0)/a.length,rem=a.map(v=>500-v),remMean=500-mean,std=Math.sqrt(rem.reduce((s,v)=>s+(v-remMean)**2,0)/rem.length);return {thickness:r(mean),rr:r(remMean*60/time),uniformity:r(std/Math.max(1,remMean)*100),defects,min:r(Math.min(...a)),max:r(Math.max(...a))};}
function physics(g,snap,id){const p=snap.recipe,t=active(g),rng=random((g.sim.seed??g.day*13007)+id*997),noise=()=>rng()*2-1,amp=g.sim.noise??.008,defAmp=g.sim.defNoise??2;const actual=snap.actual,flow=Math.min(actual.flow/180,1.04),pad=(1-.38*t.pad.glaze)*(.86+.14*t.pad.ready),slurry=t.slurry==='L2'?1.045:1,temp=1+.012*(p.temp-23),hard=t.pad.type==='hard'?1.05:1;let rr=300*(actual.pressure/3)*(p.speed/60)*flow/1.04*pad*slurry*temp*hard*(1+noise()*amp);const rings=[[0,1],[.33,8],[.66,16],[.92,24]],points=[];const edge=.015+Math.max(0,t.ring.wear-.15)*.75+(1-t.pad.ready)*.18+Math.max(0,actual.pressure-3.5)*.08;let index=0;for(const [rad,count] of rings)for(let i=0;i<count;i++){const theta=i/count*Math.PI*2,spatial=1+edge*(rad**4-((8*.33**4+16*.66**4+24*.92**4)/49))+.012*Math.cos(theta*2)*rad+noise()*.004;const value=Math.max(0,500-rr*spatial*p.time/60);points.push({x:r(rad*Math.cos(theta),4),y:r(rad*Math.sin(theta),4),t:r(value,3),id:index++});}
const interact=Math.max(0,p.temp-24)*Math.max(0,190-actual.flow)/10;const defects=Math.max(0,Math.round(6+Math.max(0,actual.pressure-3.25)*22+Math.max(0,p.speed-75)*.35+Math.max(0,t.ring.wear-.2)*55+(1-t.pad.ready)*16+t.pad.glaze*6+interact+(t.pad.type==='hard'?3:0)+noise()*defAmp));const metrics=metric(points,p.time,defects);return {points,metrics};}
function oneRun(g){const sim=g.sim,id=sim.runs.length+1,snap=snapshot(g),truth=physics(g,snap,id),run={id,at:CMP_RPG.time(g),snapshot:snap,truth,measurements:[],baseline:!sim.runs.some(x=>x.snapshot.tool===snap.tool)&&JSON.stringify(snap.fingerprint)===(sim.startConfigs?sim.startConfigs[snap.tool]:sim.startConfig)};sim.runs.push(run);const t=active(g);t.pad.age++;t.pad.glaze=Math.min(1,t.pad.glaze+.0008);t.pad.ready=Math.min(1,t.pad.ready+.03);t.ring.age++;t.ring.wear=Math.min(1,t.ring.wear+.00003);fireEvent(g);return run;}
function run(g,count=1){if(!g.shift.briefed)throw Error(T('先在晨会领取实验任务。','まず朝会で実験課題を受け取ってください。'));if(![1,3,5].includes(count))throw Error(T('每组可运行 1、3 或 5 片','1 回に処理できるのは 1、3、5 枚のいずれかです'));const chance=slipChance(g),roll=slipRoll(g,7);spend(g,8+count*3,4+count*2,count*30,T(`Tool ${g.sim.tool} 运行 ${count} 片工程试片`,`Tool ${g.sim.tool} でテストウェーハ ${count} 枚を処理`));if(roll()<chance){const p=g.sim.recipes[g.sim.tool],keys=Object.keys(bounds),key=keys[Math.floor(roll()*keys.length)],[lo,hi,step]=bounds[key],from=p[key];let to=r(from+(roll()<.5?-step:step),3);if(to<lo||to>hi)to=r(2*from-to,3);p[key]=to;noteSlip(g,{kind:'recipe',tool:g.sim.tool,key,from,to,run:g.sim.runs.length+1});}const out=[];for(let i=0;i<count;i++)out.push(oneRun(g));g.shift.routine=true;return out;}
function inspect(g){const snap=snapshot(g),t=active(g);spend(g,10,3,0,T(`读取 Tool ${g.sim.tool} 实际反馈与耗材记录`,`Tool ${g.sim.tool} の実測値と消耗品記録を確認`));const record={at:CMP_RPG.time(g),tool:g.sim.tool,recipe:snap.recipe,actual:snap.actual,padAge:t.pad.age,ringAge:t.ring.age,surface:t.pad.glaze>.3?T('表面纹理变浅，局部有光滑区域','表面のテクスチャが浅くなり、一部に平滑な領域があります'):t.pad.ready<.8?T('新垫表面尚未完成磨合','新しいパッドの表面は、まだ慣らしが完了していません'):T('表面纹理均匀','表面のテクスチャは均一です'),ring:r(t.ring.wear,2)};g.sim.checks.push(record);return record;}
function maintenance(g,action,arg){const t=active(g);if(!['pad','condition','ring','flow','pressure','slurry','meter'].includes(action))throw Error(T('未知维护动作','不明なメンテナンス操作です'));if(action==='pad'&&!['standard','hard'].includes(arg))throw Error(T('请选择研磨垫类型','研磨パッドの種類を選択してください'));if(action==='condition'&&![30,60,120].includes(Number(arg)))throw Error(T('修整时间为 30、60 或 120 秒','ドレッシング時間は 30、60、120 秒のいずれかです'));if(action==='slurry'&&!['L1','L2'].includes(arg))throw Error(T('请选择批次','ロットを選択してください'));if(action==='slurry'&&t.slurry===arg)throw Error(T(`Tool ${t.id} 现在用的就是 ${arg}，没有切换。`,`Tool ${t.id} は現在すでに ${arg} を使用中です。切り替えは行われません。`));const cost={pad:[45,8,600],condition:[10,4,20],ring:[30,6,350],flow:[20,5,80],pressure:[20,5,80],slurry:[10,3,120],meter:[20,5,80]}[action];const labels={pad:T('更换研磨垫','研磨パッド交換'),condition:T('修整/磨合研磨垫','研磨パッドのドレッシング／慣らし'),ring:T('更换保持环','リテーナリング交換'),flow:T('校准实际流量','実流量の校正'),pressure:T('校准实际压力','実圧力の校正'),slurry:T('切换研磨液批次','スラリーロット切替'),meter:T('使用参考片校准 M1','標準ウェーハで M1 を校正')};spend(g,...cost,labels[action]+' '+(arg||''));const before=clone(t);if(action==='pad')t.pad={serial:t.id+'-P'+g.sim.serial++,type:arg,age:0,glaze:0,ready:0,conditioning:0};if(action==='condition'){t.pad.conditioning+=Number(arg);t.pad.glaze=Math.max(0,t.pad.glaze-Number(arg)/60*.55);t.pad.ready=Math.min(1,t.pad.ready+Number(arg)/60);t.pad.age+=.1;}if(action==='ring')t.ring={serial:t.id+'-R'+g.sim.serial++,wear:.02,age:0};if(action==='flow'){t.flowGain=1;t.calibration++;t.flowCalibration++}if(action==='pressure'){t.pressureGain=1;t.calibration++;t.pressureCalibration++}if(action==='slurry')t.slurry=arg;if(action==='meter'){g.sim.bias=0;g.sim.meterEpoch++;g.sim.referenceChecked=true;}g.sim.services.push({at:CMP_RPG.time(g),action,arg,tool:t.id,before,after:clone(t),label:labels[action]});}
function reference(g){spend(g,8,2,0,T('参考片对照：M1 与 M2','標準ウェーハ照合：M1 と M2'));const m={at:CMP_RPG.time(g),M1:r(200+g.sim.bias),M2:200,reference:200,epoch:g.sim.meterEpoch};g.sim.referenceLog.push(m);g.sim.referenceChecked=Math.abs(m.M1-200)<=1;if(g.sim.referenceChecked)for(const run of g.sim.runs)for(const mm of run.measurements)if(mm.meter==='M1'&&mm.epoch===g.sim.meterEpoch)mm.biasVerified=true;return m;}
function measure(g,ids,meter){if(!['M1','M2'].includes(meter))throw Error(T('无效量测设备','無効な測定機です'));if(!Array.isArray(ids)||!ids.length||ids.some(id=>!Number.isInteger(id)||!g.sim.runs.some(r=>r.id===id)))throw Error(T('请选择已有试片','既存のテストウェーハを選択してください'));ids=[...new Set(ids)];const want=meter,slipped=slipRoll(g,11)()<slipChance(g);if(slipped)meter=want==='M1'?'M2':'M1';spend(g,4+ids.length*2,2+Math.ceil(ids.length/3),ids.length*5,T(`${meter} 量测试片 ${ids.map(n=>'#'+n).join('、')}`,`${meter} でテストウェーハ ${ids.map(n=>'#'+n).join('、')} を測定`));if(slipped)noteSlip(g,{kind:'meter',want,got:meter,runs:ids});for(const id of ids){const run=g.sim.runs.find(r=>r.id===id),rng=random((g.sim.seed??g.day)*3571+id*73+(meter==='M1'?1:100)+run.measurements.length*19),bias=meter==='M1'?g.sim.bias:0;const points=run.truth.points.map(p=>({...p,t:r(p.t+bias+(rng()-.5)*.6,3)}));const m={meter,epoch:g.sim.meterEpoch,at:CMP_RPG.time(g),points,metrics:metric(points,run.snapshot.recipe.time,run.truth.metrics.defects),biasVerified:meter==='M2'||g.sim.referenceChecked};run.measurements.push(m);}return ids.length;}
function latest(run,meter){return [...run.measurements].reverse().find(m=>!meter||m.meter===meter)}
function pass(m){const x=m.metrics;return x.thickness>=185&&x.thickness<=215&&x.uniformity<=5&&x.defects<=15;}
function diff(a,b){const fa=a.snapshot.fingerprint,fb=b.snapshot.fingerprint;return Object.keys(fa).filter(k=>fa[k]!==fb[k]);}
function compare(g,a,b){const ra=g.sim.runs.find(r=>r.id===a),rb=g.sim.runs.find(r=>r.id===b);if(!ra||!rb||a===b)throw Error(T('请选择两片不同的试片','異なる 2 枚のテストウェーハを選択してください'));if(!latest(ra)||!latest(rb))throw Error(T('先量测两片试片','まず 2 枚のテストウェーハを測定してください'));const key=[a,b].sort((a,b)=>a-b).join('-');if(!g.sim.compared.includes(key))g.sim.compared.push(key);return {changed:diff(ra,rb),a:latest(ra),b:latest(rb)};}
function doe(g,a,lowA,highA,b,lowB,highB,reps=1){if(a===b||!bounds[a]||!bounds[b])throw Error(T('请选择两个不同的参数','異なる 2 つのパラメータを選択してください'));if(![1,2,3].includes(reps))throw Error(T('重复数为 1–3','繰り返し数は 1～3 です'));const vals=[[a,Number(lowA),Number(highA)],[b,Number(lowB),Number(highB)]];for(const [k,lo,hi] of vals){if(!Number.isFinite(lo)||!Number.isFinite(hi)||lo>=hi||lo<bounds[k][0]||hi>bounds[k][1])throw Error(T('低/高水平须递增，且位于参数范围内','低/高水準は「低 < 高」とし、パラメータ範囲内で指定してください'));for(const v of [lo,hi])if(Math.abs((v-bounds[k][0])/bounds[k][2]-Math.round((v-bounds[k][0])/bounds[k][2]))>1e-6)throw Error(T('DOE 水平请使用参数规定的步长','DOE の水準は、パラメータ規定の刻み幅に合わせてください'));}if(!g.shift.briefed)throw Error(T('先领取实验任务','まず実験課題を受け取ってください'));const n=4*reps;spend(g,10+n*3,4+n*2,n*30,T(`2×2 DOE：${bounds[a][3]} × ${bounds[b][3]}，每组合 ${reps} 片`,`2×2 DOE：${bounds[a][3]} × ${bounds[b][3]}、各組み合わせ ${reps} 枚`));const base=clone(g.sim.recipes[g.sim.tool]),combos=[];for(let i=0;i<reps;i++)for(const x of [Number(lowA),Number(highA)])for(const y of [Number(lowB),Number(highB)])combos.push([x,y]);const rand=random((g.sim.seed??g.day)*999+g.sim.runs.length);for(let i=combos.length-1;i>0;i--){const j=Math.floor(rand()*(i+1));[combos[i],combos[j]]=[combos[j],combos[i]];}const batch='DOE-'+(g.sim.runs.length+1);for(const [x,y]of combos){g.sim.recipes[g.sim.tool]={...base,[a]:x,[b]:y};const trial=oneRun(g);trial.doe={batch,a,b,lowA:Number(lowA),highA:Number(highA),lowB:Number(lowB),highB:Number(highB),reps};}g.sim.recipes[g.sim.tool]=base;g.shift.routine=true;return batch;}
function score(g){const sim=g.sim,measured=sim.runs.filter(r=>r.measurements.length),final=sim.runs.find(r=>r.id===sim.finalId),finalM=final&&latest(final),validFinal=finalM&&finalM.biasVerified&&pass(finalM);let pairs=false;for(const pair of sim.compared){const [a,b]=pair.split('-').map(Number),ra=sim.runs.find(r=>r.id===a),rb=sim.runs.find(r=>r.id===b);if(ra&&rb&&diff(ra,rb).length===1&&latest(ra).meter===latest(rb).meter)pairs=true;}const repeat=final?measured.filter(r=>JSON.stringify(r.snapshot.fingerprint)===JSON.stringify(final.snapshot.fingerprint)&&latest(r).biasVerified&&pass(latest(r))).length:0;const sameWafer=measured.some(r=>latest(r,'M1')&&latest(r,'M2'));if(sameWafer)pairs=true;const cross=sameWafer||sim.referenceLog.length>0;return [[T('基准记录','ベースライン'),measured.some(r=>r.baseline)?15:0,15],[T('可追溯试验','追跡可能な試験'),Math.min(15,measured.length*5),15],[T('单变量对照','一因子比較'),pairs?20:0,20],[T('重复确认','繰り返し確認'),repeat>=3?20:repeat>=2?10:0,20],[T('最终方案达标','最終案の合格'),validFinal?20:0,20],[T('量测核查','測定の検証'),cross?10:0,10]];}
function submit(g){if(g.shift.report)throw Error(T('已结案','すでに完了済みです'));const measured=g.sim.runs.filter(r=>r.measurements.length);if(measured.length<3)throw Error(T('至少运行并量测 3 片，再提交实验记录。','少なくとも 3 枚を処理・測定してから、実験記録を提出してください。'));if(!g.sim.finalId||!measured.some(r=>r.id===g.sim.finalId))throw Error(T('请选一片已量测试片作为最终方案记录。','測定済みのテストウェーハを 1 枚、最終案の記録として選択してください。'));spend(g,15,4,0,T('提交自主实验报告','自主実験レポートを提出'));g.shift.report=true;const total=score(g).reduce((n,r)=>n+r[1],0);g.shift.xpAward=total+10;g.xp+=g.shift.xpAward;return total;}
/* Pure helper for the production-line mode: one wafer on tool state t with a recipe; no game state touched. */
function simulate(t,recipe,seed){const g={day:seed,sim:{tool:t.id,tools:{[t.id]:t},recipes:{[t.id]:recipe}}};return physics(g,snapshot(g),0)}
root.CMP_SIM={newTool:tool,simulate,bounds,defaults,scenarios,describe,keyAction,FOCUS,slipChance,restGain,rest,init,active,configure,selectTool,snapshot,run,inspect,maintenance,reference,measure,latest,pass,diff,compare,doe,score,submit,clone};
})(globalThis);
